import {archiveDb} from '@/lib/archive-db';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import {resolveArchiveActor} from '@/lib/archive-identity';
import {sameOrigin} from '@/lib/archive-comments';
import {timelineRevision,saveTimelineSelection} from '@/lib/archive-timeline-selections';
export async function GET(req:Request){try{await requireArchiveAction(req,'manageTimeline');const db=archiveDb(),url=new URL(req.url);const snapshot=url.searchParams.get('snapshot');if(snapshot){const version=await db.prepare('SELECT * FROM timeline_selections WHERE id=?').bind(snapshot).first();if(!version)return Response.json({error:'Auswahl nicht gefunden.'},{status:404});const members=await db.prepare('SELECT entry_id FROM timeline_selection_members WHERE snapshot_id=?').bind(snapshot).all();return Response.json({version,selected:members.results.map(r=>r.entry_id)},{headers:{'Cache-Control':'no-store'}})}
 const revision=await timelineRevision();const entries=await db.prepare('SELECT e.id,e.data,e.timeline_visible,e.publication_status,r.reference FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id WHERE e.deleted=0 ORDER BY e.updated DESC').all();const offset=Math.max(0,Math.floor(Number(url.searchParams.get('offset'))||0));const snapshots=await db.prepare('SELECT * FROM timeline_selections ORDER BY created DESC,id DESC LIMIT 51 OFFSET ?').bind(offset).all();const revisionAfter=await timelineRevision();if(revision!==revisionAfter)return Response.json({error:'Die Auswahl wurde gerade geändert. Bitte erneut laden.'},{status:409});
 return Response.json({revision,entries:entries.results.map((r:any)=>{const d=JSON.parse(r.data);return {id:r.id,reference:r.reference,title:d.title,category:d.category,place:d.place,tags:d.tags,status:d.status,start:d.start,end:d.end,period:d.period,selected:!!r.timeline_visible,publicationStatus:r.publication_status,images:d.files.some((f:any)=>f.type.startsWith('image/')),audio:d.files.some((f:any)=>f.type.startsWith('audio/')),documents:d.files.some((f:any)=>!f.type.startsWith('image/')&&!f.type.startsWith('audio/'))}}),snapshots:snapshots.results.slice(0,50),more:snapshots.results.length>50},{headers:{'Cache-Control':'no-store'}})
 }catch(e){console.error(e);return accessResponse(e)||Response.json({error:'Die Zeitleistenverwaltung konnte nicht geladen werden.'},{status:503})}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});await requireArchiveAction(req,'manageTimeline');const actor=await resolveArchiveActor(req),d=await req.json() as any;const valid=(a:any)=>Array.isArray(a)&&a.length<=500000&&a.every((id:any)=>typeof id==='string'&&/^[a-f0-9-]{36}$/.test(id));if(!valid(d.add)||!valid(d.remove)||typeof d.baseRevision!=='string'||typeof d.label!=='string'||d.label.length>150)return Response.json({error:'Bitte die Auswahl prüfen.'},{status:400});if(d.add.some((id:string)=>d.remove.includes(id)))return Response.json({error:'Widersprüchliche Auswahl.'},{status:400});const current=await timelineRevision();if(current!==d.baseRevision)return Response.json({error:'Die Auswahl wurde inzwischen geändert. Ihr Entwurf bleibt erhalten. Bitte den aktuellen Stand neu laden.'},{status:409});const revision=await saveTimelineSelection({add:[...new Set<string>(d.add)],remove:[...new Set<string>(d.remove)],baseRevision:d.baseRevision,label:d.label.trim()||'Auswahl übernommen',actorName:actor!.name,actorId:actor!.id});return Response.json({revision})}catch(e){console.error(e);return accessResponse(e)||Response.json({error:'Die Auswahl konnte nicht übernommen werden. Ihr Entwurf bleibt erhalten.'},{status:503})}}
