import {env} from '@/lib/runtime-env';
import {archiveAccess,accessResponse} from '@/lib/archive-access';
import {archiveRequestOrigin} from '@/lib/archive-request-origin';
import {pushService} from '@/lib/archive-push';
import {messageService} from '@/server/message-service.mjs';
const headers={'Cache-Control':'no-store'};
async function context(req:Request){const a=await archiveAccess(req);if(!a||a.role==='public')return {response:Response.json({error:'Bitte mit einem internen Konto anmelden.'},{status:a?403:401,headers})};if((env as any).ARCHIVE_HOSTING_RUNTIME!=='linux')return {response:Response.json({available:false,unread:0,reason:'Interne Nachrichten stehen auf der Linux-Installation mit eigenen Benutzerkonten zur Verfügung.'},{headers})};return {role:a.role,actor:a.identity.subject,service:messageService((env as any).DB.database)}}
export async function GET(req:Request){try{const c=await context(req);if(c.response)return c.response;const p=new URL(req.url).searchParams,s=c.service!,actor=c.actor!;if(p.has('review')){if(!['admin','manager'].includes(c.role!))return Response.json({error:'Nur Admin oder Verwalter.'},{status:403,headers});return Response.json(s.reviewDraft(actor,p.get('review')),{headers})}if(p.has('entry'))return Response.json(s.entry(actor,p.get('entry')),{headers});if(p.has('thread')){const t=s.detail(actor,p.get('thread'),p.has('before')?p.get('before'):undefined);if(t.entry&&!['admin','manager'].includes(c.role!))t.entry.pending=null;return Response.json(t,{headers})}if(p.has('count'))return Response.json({available:true,unread:s.count(actor)},{headers});return Response.json({available:true,unread:s.count(actor),threads:s.list(actor),openRequests:s.openRequests(actor),recipients:s.recipients(actor),actor},{headers})}catch(e:any){return accessResponse(e)||Response.json({error:e.message||'Nachrichten konnten nicht geladen werden.'},{status:400,headers})}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==archiveRequestOrigin(req))return Response.json({error:'Anfrage von einer anderen Adresse abgewiesen.'},{status:403,headers});const c=await context(req);if(c.response)return c.response;const reader=req.body?.getReader();if(!reader)return new Response(null,{status:400});let size=0,text='';const decoder=new TextDecoder();while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>65536){await reader.cancel();return new Response(null,{status:413})}text+=decoder.decode(r.value,{stream:true})}text+=decoder.decode();const d=JSON.parse(text),s=c.service!,actor=c.actor!;if(d.action==='hide')return Response.json(s.hide(actor,d.threadId,d.throughId),{headers});if(d.action==='read')return Response.json(s.read(actor,d.threadId,d.lastId),{headers});if(d.action!=='send')return Response.json({error:'Unbekannte Aktion.'},{status:400,headers});if(d.announcement&&c.role!=='admin')return Response.json({error:'Nur Admins dürfen Mitteilungen an alle senden.'},{status:403,headers});const result=s.send(actor,d);try{const push=pushService();push.scan();await push.deliver(1)}catch{console.error('Nachricht gespeichert; Push-Zustellung wird erneut versucht.')}return Response.json(result,{status:201,headers})}catch(e:any){return accessResponse(e)||Response.json({error:e.message||'Nachricht konnte nicht gespeichert werden.'},{status:400,headers})}}
