import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {sqliteBinding} from '../server/linux-storage.mjs';
import {authService,initializeAuth} from '../server/auth-service.mjs';
import {accountCode} from '../server/account-management.mjs';
import {messageService} from '../server/message-service.mjs';
import {initializePush} from '../server/push-service.mjs';
const root=await fs.mkdtemp(path.resolve('.update-test-accounts-')),store=sqliteBinding(path.join(root,'archive.sqlite'),path.resolve('drizzle')),db=store.database;
try{
 initializeAuth(db);initializePush(db);
 function add(id,role,name='Gleicher Name'){db.prepare('INSERT INTO linux_accounts VALUES(?,?,?,0)').run(id,id+'@example.test',name);db.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').run(id,'linux',id,name,'now',role)}
 add('admin','admin','Admin');add('guest','guest');add('other','guest');add('user','user');
 const s=authService(db,{origin:'https://archive.example.test',sessionKey:'b'.repeat(64)}),m=messageService(db),code=accountCode(db,'guest');
 assert.notEqual(code,accountCode(db,'other'));assert.equal(code,accountCode(db,'guest'));assert.equal(s.accounts().filter(a=>a.name==='Gleicher Name').length,3);
 const poll=m.send('admin',{subject:'Zugriff',body:'Frage',recipients:['guest','other'],poll:{question:'Weiter gebraucht?',options:['Ja','Nein']}});m.vote('guest',poll.threadId,0);
 assert.throws(()=>s.rename('guest','Neu','user'));assert.throws(()=>s.rename('guest',' ','admin'));assert.throws(()=>s.delete('admin','admin',accountCode(db,'admin')));assert.throws(()=>s.delete('guest','user',code));assert.throws(()=>s.delete('guest','admin','wrong'));assert.equal(db.prepare("SELECT name FROM linux_accounts WHERE id='guest'").get().name,'Gleicher Name');
 s.rename('guest','Neuer Name','admin');assert.equal(accountCode(db,'guest'),code);assert.equal(m.detail('admin',poll.threadId).poll.answers[0].name,'Neuer Name');assert.equal(db.prepare("SELECT display_name FROM archive_users WHERE id='guest'").get().display_name,'Neuer Name');
 s.edit('guest','guest',true,'admin');assert.throws(()=>m.list('guest'));s.edit('guest','guest',false,'admin');assert.equal(m.detail('guest',poll.threadId).poll.answers.length,1);
 const privateThread=m.send('user',{subject:'Alt',body:'Freier Text bleibt',recipients:['admin']});
 db.prepare("INSERT INTO linux_credentials VALUES('key','guest','public',0,'[]')").run();db.prepare("INSERT INTO linux_credential_metadata VALUES('key','Mobiltelefon','now','now')").run();db.prepare("INSERT INTO linux_account_security VALUES('guest','handle')").run();db.prepare("INSERT INTO linux_login_metadata VALUES('guest','now')").run();db.prepare("INSERT INTO linux_invites VALUES('old-invite','guest@example.test','Neuer Name','guest',9999999999,1)").run();db.prepare("INSERT INTO linux_challenges VALUES('proof','x','manage-proof','guest',9999999999),('registration','x','register','old-invite',9999999999)").run();
 db.prepare("INSERT INTO linux_push_subscriptions(id,account_id,endpoint,data,created) VALUES('device','guest','https://example.test/device','{}','now')").run();
 db.prepare("INSERT INTO archive_settings VALUES('welcome:guest','{}','now','system')").run();
 db.prepare("INSERT INTO entries(id,data,updated) VALUES('entry','{}','now')").run();db.prepare("INSERT INTO entry_versions(entry_id,data,created,action,actor_id,actor_name) VALUES('entry','{}','now','edit','guest','Neuer Name')").run();db.prepare("INSERT INTO archive_comments(id,entry_id,author_id,author_name,body,created) VALUES('comment','entry','guest','Neuer Name','Text','now')").run();
 db.prepare("INSERT INTO timeline_selections VALUES('selection','Test','now','Neuer Name',0)").run();db.prepare("INSERT INTO archive_settings VALUES('timeline-actor:selection','\"guest\"','now','guest')").run();
 db.prepare("INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES('system-publication-notices','system','publication','System','now','user')").run();
 db.prepare("INSERT INTO archive_message_threads VALUES('notice','Anfrage','now',1)").run();db.prepare("INSERT INTO archive_messages(thread_id,sender_id,sender_name,body,created) VALUES('notice','system-publication-notices','Archiv-Benachrichtigung','Angefragt von: Neuer Name'||char(10)||'Hinweis','now')").run();db.prepare("INSERT INTO archive_settings VALUES('publication-requester:notice','\"guest\"','now','guest')").run();
 // Force a late failure: every earlier change must roll back in the same transaction.
 db.exec("CREATE TRIGGER reject_delete BEFORE INSERT ON archive_settings WHEN NEW.key='deleted-account:guest' BEGIN SELECT RAISE(ABORT,'fixture'); END");assert.throws(()=>s.delete('guest','admin',code));assert.equal(db.prepare("SELECT email FROM linux_accounts WHERE id='guest'").get().email,'guest@example.test');assert.ok(db.prepare("SELECT 1 FROM linux_credentials WHERE id='key'").get());db.exec('DROP TRIGGER reject_delete');
 s.delete('guest','admin',code);const alias='Gelöschtes Konto · '+code,a=db.prepare("SELECT * FROM linux_accounts WHERE id='guest'").get();assert.equal(a.name,alias);assert.equal(a.email,'deleted:guest');assert.equal(a.disabled,1);assert.equal(db.prepare("SELECT count(*) AS n FROM linux_push_subscriptions WHERE account_id='guest'").get().n,0);assert.match(db.prepare("SELECT body FROM archive_messages WHERE thread_id='notice'").get().body,new RegExp(code));assert.ok(!s.accounts().some(a=>a.id==='guest'));assert.ok(!m.recipients('admin').some(a=>a.id==='guest'));assert.throws(()=>s.edit('guest','guest',false,'admin'));assert.throws(()=>s.rename('guest','Again','admin'));assert.throws(()=>m.list('guest'));
 for(const table of ['linux_credentials','linux_credential_metadata','linux_account_security','linux_login_metadata','linux_challenges','linux_invites'])assert.equal(db.prepare('SELECT count(*) AS n FROM '+table).get().n,0,table);
 assert.equal(db.prepare("SELECT actor_name FROM entry_versions WHERE actor_id='guest'").get().actor_name,alias);assert.equal(db.prepare("SELECT author_name FROM archive_comments WHERE author_id='guest'").get().author_name,alias);assert.equal(db.prepare("SELECT actor_name FROM timeline_selections WHERE id='selection'").get().actor_name,alias);assert.ok(!db.prepare("SELECT 1 FROM archive_settings WHERE key='welcome:guest'").get());assert.equal(m.detail('admin',poll.threadId).poll.answers[0].name,alias);assert.equal(m.detail('admin',poll.threadId).poll.answers[0].accountId,'guest');assert.equal(db.prepare("SELECT name FROM linux_accounts WHERE id='other'").get().name,'Gleicher Name');
 // Original email is available again, but a replacement has its own ID, code and no historical membership.
 assert.ok(s.invite({email:'guest@example.test',name:'Gleicher Name',role:'guest'}));add('replacement','guest');assert.notEqual(accountCode(db,'replacement'),code);assert.throws(()=>m.detail('replacement',poll.threadId));assert.throws(()=>m.detail('replacement',privateThread.threadId));assert.equal(accountCode(db,'guest'),code);
 console.log('PASS: duplicate names, stable IDs/codes, admin-only rename/delete, self protection, exact confirmation, deactivate/reactivate, atomic rollback, credential/contact erasure, retained poll/history references and isolated replacement account.');
}finally{store.close();await fs.rm(root,{recursive:true,force:true})}
