import assert from 'node:assert/strict';
import {sortArchive,matchesArchiveYears} from '../lib/archive-order.mjs';
const data=[{id:'undated',title:'A',start:'',status:'Unsicher'},{id:'ancient',title:'B',start:'-100',end:'2000',status:'Offen'},{id:'zero',title:'C',start:'0',status:'In Bearbeitung'},{id:'new',title:'D',start:'2020',status:'Quellengeprüft'},{id:'invalid',title:'Z',start:'circa 1900'}];
const ids=order=>sortArchive(data,order).map(x=>x.id);
assert.deepEqual(ids('Datierung: älteste zuerst'),['ancient','zero','new','undated','invalid']);assert.deepEqual(ids('Datierung: neueste zuerst'),['new','zero','ancient','undated','invalid']);assert.deepEqual(ids('Forschungsstand'),['ancient','zero','new','undated','invalid']);assert.deepEqual(ids('Titel Z–A'),['invalid','new','zero','ancient','undated']);
assert.deepEqual(sortArchive([{title:'Äpfel 10'},{title:'Äpfel 2'}],'Titel A–Z').map(x=>x.title),['Äpfel 2','Äpfel 10']);
const revisions=[{id:'older',title:'B',updated:'2026-01-01T00:00:00.000Z:revision',created:'2020-01-01T00:00:00.000Z'},{id:'newer',title:'A',updated:'2026-02-01T00:00:00.000Z',created:'2019-01-01T00:00:00.000Z'},{id:'unknown',title:'A'}];assert.deepEqual(sortArchive(revisions).map(x=>x.id),['newer','older','unknown']);assert.deepEqual(sortArchive(revisions,'Neu angelegt').map(x=>x.id),['older','newer','unknown']);assert.equal(data[0].id,'undated');
assert.equal(matchesArchiveYears({start:'1800',end:'1900'},'1850','1860'),true);assert.equal(matchesArchiveYears({start:'',end:'1900'},'1899','1901'),true);assert.equal(matchesArchiveYears({start:'',end:''},'1800',''),false);assert.equal(matchesArchiveYears({start:'-200',end:'-100'},'-150','0'),true);assert.equal(sortArchive([{title:'Unknown'},{title:'Known',end:'1900'}],'Datierung: älteste zuerst')[0].title,'Known');
console.log('PASS: date directions, unknown/invalid always last, negative and year zero, period starts, status order, German/numeric titles, metadata, immutable input.');
