import assert from 'node:assert/strict';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),esbuild=require(require.resolve('esbuild',{paths:[require.resolve('vite')]}));
const jsx='export const jsx=(type,props)=>({type,props});export const jsxs=jsx;';
const result=await esbuild.build({entryPoints:['components/archive/entry-save-choice.tsx'],bundle:true,platform:'node',format:'cjs',jsx:'automatic',write:false,plugins:[{name:'dependencies',setup(build){build.onResolve({filter:/^(react\/jsx-runtime|@\/)/},args=>({path:args.path,namespace:'mock'}));build.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:args.path==='react/jsx-runtime'?jsx:'export const Dialog="Dialog",DialogContent="DialogContent",DialogTitle="DialogTitle",DialogDescription="DialogDescription";',loader:'js'}))}}]});
let focused=false,closed=false,choice=null;const scope={module:{exports:{}},document:{getElementById(id){assert.equal(id,'entry-save-button');return {focus(){focused=true}}}}};vm.runInNewContext(result.outputFiles[0].text,scope);const {EntrySaveChoice}=scope.module.exports;
function all(n){return !n||typeof n!=='object'?[]:[n,...(Array.isArray(n.props?.children)?n.props.children:[n.props?.children]).flatMap(all)]}
const render=busy=>all(EntrySaveChoice({open:true,busy,error:'Fixture error',onOpenChange:o=>closed=!o,onSave:r=>choice=r}));let nodes=render(false);assert.ok(nodes.some(n=>n.props?.role==='alert'));nodes.find(n=>n.type==='button'&&n.props.children==='Nur speichern').props.onClick();assert.equal(choice,false);nodes.find(n=>n.type==='button'&&n.props.children==='Speichern und Veröffentlichung beantragen').props.onClick();assert.equal(choice,true);nodes.find(n=>n.type==='button'&&n.props.children==='Zurück zur Bearbeitung').props.onClick();assert.equal(closed,true);nodes.find(n=>n.type==='DialogContent').props.onCloseAutoFocus({preventDefault(){}});assert.equal(focused,true);
closed=false;nodes=render(true);assert.ok(nodes.filter(n=>n.type==='button').every(n=>n.props.disabled));nodes.find(n=>n.type==='Dialog').props.onOpenChange(false);assert.equal(closed,false);assert.equal(nodes.find(n=>n.type==='DialogContent').props.showCloseButton,false);let prevented=false;nodes.find(n=>n.type==='DialogContent').props.onEscapeKeyDown({preventDefault(){prevented=true}});assert.equal(prevented,true);
console.log('PASS: two distinct save actions, return without saving, retained error/focus and busy dismissal protection.');
