import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createHmac} from 'node:crypto';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url),{Miniflare}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler')]})),key='a'.repeat(64);
const modules=[{type:'ESModule',path:resolve('dist/server/index.js')},...readdirSync('dist/server',{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js').map(p=>({type:'ESModule',path:resolve('dist/server',p)}))];
async function instance(linux){const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],bindings:{ARCHIVE_BOOTSTRAP_ADMIN_EMAIL:'admin@example.test',ARCHIVE_INITIAL_PLACE:'Testort',ARCHIVE_INITIAL_ASSOCIATION:'Testverein',...(linux?{ARCHIVE_HOSTING_RUNTIME:'linux',ARCHIVE_SESSION_KEY:key}:{})},d1Databases:['DB'],r2Buckets:['BUCKET']});const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const s of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(s.trim())await db.prepare(s).run();return mf;}
const oai={'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'admin@example.test'};
function session(exp=Math.floor(Date.now()/1000)+3600){const payload=Buffer.from(JSON.stringify({issuer:'archive-linux-session-v1',subject:'linux-admin',email:'admin@example.test',name:'Test Admin',iat:Math.floor(Date.now()/1000),exp})).toString('base64url');return 'archive_session='+payload+'.'+createHmac('sha256',key).update(payload).digest('base64url');}
const sites=await instance(false),linux=await instance(true);
try{let r=await sites.dispatchFetch('https://archive.test/api/updates',{headers:oai});assert.equal(r.status,200);assert.equal((await r.json()).enabled,false);r=await sites.dispatchFetch('https://archive.test/api/updates',{method:'POST',headers:{...oai,Origin:'https://archive.test','Content-Type':'application/json'},body:JSON.stringify({action:'install',tag:'v1.0.0'})});assert.equal(r.status,409);r=await linux.dispatchFetch('https://archive.test/api/updates',{headers:oai});assert.equal(r.status,401);r=await linux.dispatchFetch('https://archive.test/api/updates',{headers:{Cookie:session()}});assert.equal(r.status,200);assert.equal((await r.json()).enabled,false);r=await linux.dispatchFetch('https://archive.test/api/updates?hosting',{headers:{Cookie:session()}});const h=await r.json();assert.equal(h.runtime,'linux');assert.equal(h.updates,false);assert.equal(JSON.stringify(h).includes(key),false);for(const cookie of [session(1),session().slice(0,-5)+'invalid'])assert.equal((await linux.dispatchFetch('https://archive.test/api/updates',{headers:{Cookie:cookie,...oai}})).status,401);console.log('PASS: Sites updates disabled, Linux ignores OAI headers, signed sessions verified, expired/tampered sessions rejected, unconfigured updater blocked and secrets hidden.');}finally{await sites.dispose();await linux.dispose()}
