import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
const {version:applicationVersion,databaseSchemaVersion:applicationSchema}=JSON.parse(readFileSync('version.json','utf8'));
const require=createRequire(import.meta.url),{Miniflare}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler')]}));
const modules=[{type:'ESModule',path:resolve('dist/server/index.js')},...readdirSync('dist/server',{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js').map(p=>({type:'ESModule',path:resolve('dist/server',p)}))];
const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],bindings:{ARCHIVE_BOOTSTRAP_ADMIN_EMAIL:'admin@example.test'},d1Databases:['DB'],r2Buckets:['BUCKET']});
const admin={'oai-authenticated-user-id':'new-admin','oai-authenticated-user-email':'admin@example.test'},user={'oai-authenticated-user-id':'visitor','oai-authenticated-user-email':'visitor@example.test'};
const call=(route,identity=admin,data)=>mf.dispatchFetch('https://archive.test'+route,{method:data?'POST':'GET',headers:{...identity,...(data?{Origin:'https://archive.test','Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});
try{const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const s of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(s.trim())await db.prepare(s).run();let r=await call('/api/installation');let config=await r.json();assert.equal(config.completed,false);assert.equal(config.subtitle,'Digitale Heimatforschung');assert.equal(config.canSetup,true);r=await call('/api/installation',user,{place:'Ort',association:'Verein'});assert.equal(r.status,403);r=await call('/api/installation',admin,{place:'',association:'Verein'});assert.equal(r.status,400);r=await call('/api/installation',admin,{place:'Neuer Ort',association:'Neuer Verein',domain:''});assert.equal(r.status,200);config=await (await call('/api/installation')).json();assert.equal(config.place,'Neuer Ort');assert.equal(config.association,'Neuer Verein');assert.equal(config.completed,true);assert.equal((await call('/api/installation',admin,{place:'Überschreiben',association:'Anderer Verein'})).status,409);assert.equal((await db.prepare('SELECT count(*) AS n FROM entries').first()).n,0);
assert.equal((await call('/api/design',admin,{theme:'plum',expectedTheme:'sage'})).status,200);
assert.equal((await call('/api/installation',user,{action:'save-title',title:'Fremder Titel'})).status,403);
assert.equal((await call('/api/installation',admin,{action:'save-title',title:'Geschichte unseres Ortes'})).status,200);
assert.equal((await (await call('/api/installation')).json()).title,'Geschichte unseres Ortes');
const appManifest=await (await call('/manifest.webmanifest',{})).json();assert.equal(appManifest.name,'Geschichte unseres Ortes');assert.equal(appManifest.short_name,appManifest.name);assert.equal(appManifest.id,'/');assert.equal(appManifest.start_url,'/');
const brandedHtml=await (await call('/',{})).text();assert.match(brandedHtml,/<meta[^>]*name="apple-mobile-web-app-title"[^>]*content="Geschichte unseres Ortes"/);assert.match(brandedHtml,/<meta[^>]*name="application-name"[^>]*content="Geschichte unseres Ortes"/);

assert.equal((await call('/api/installation',admin,{action:'save-title',title:''})).status,200);
assert.equal((await (await call('/manifest.webmanifest',{})).json()).name,'Geschichte Neuer Orts');
assert.equal((await call('/api/installation',user,{action:'save-branding',title:'Titel',association:'Fremder Verein'})).status,403);
for(const association of ['', ' '.repeat(3), 'x'.repeat(201), 'Name\nVerein'])assert.equal((await call('/api/installation',admin,{action:'save-branding',title:'',association})).status,400);
assert.equal((await call('/api/installation',admin,{action:'save-branding',title:'',association:'  Umbenannter Verein  ',place:'Nicht ändern',domain:'https://nicht-aendern.test'})).status,200);
const renamed=await (await call('/api/installation')).json();assert.equal(renamed.association,'Umbenannter Verein');assert.equal(renamed.place,'Neuer Ort');assert.equal((await db.prepare('SELECT count(*) AS n FROM entries').first()).n,0);
// Names: admin-only subtitle updates, legacy compatibility and portable metadata.
assert.equal((await call('/api/installation',user,{action:'save-branding',title:'',association:'Umbenannter Verein',subtitle:'Nicht erlaubt'})).status,403);
for(const subtitle of ['', '   ', 'x'.repeat(121), 'Zeile\nZwei', 123])assert.equal((await call('/api/installation',admin,{action:'save-branding',title:'',association:'Umbenannter Verein',subtitle})).status,400);
assert.equal((await call('/api/installation',admin,{action:'save-branding',title:'',association:'Umbenannter Verein',subtitle:'  Unser digitales Archiv  '})).status,200);
assert.equal((await (await call('/api/installation')).json()).subtitle,'Unser digitales Archiv');
assert.equal((await call('/api/installation',admin,{action:'save-title',title:''})).status,200);
assert.equal((await call('/api/installation',admin,{action:'save-branding',title:'',association:'Umbenannter Verein'})).status,200);
assert.equal((await (await call('/api/installation')).json()).subtitle,'Unser digitales Archiv');
const smtp=await (await call('/api/system-settings',admin,{action:'smtp-test',to:'test@example.test'})).json();assert.equal(smtp.available,false);assert.match(smtp.message,/Sites/);
const push=await (await call('/api/push')).json();assert.equal(push.available,false);assert.equal(push.topics.length,6);assert.equal((await call('/api/push',admin,{action:'save',enabled:true,preferences:{qr:true}})).status,409);
const initialIntro=await (await call('/api/public-intro')).json();assert.equal(initialIntro.heading,'');assert.match(initialIntro.defaults.heading,/Neuer Ort damals/);assert.equal((await call('/api/public-intro',user,{heading:'No',text:'No',expected:{heading:'',text:''}})).status,403);assert.equal((await call('/api/public-intro',admin,{heading:'Eigene Überschrift',text:'Willkommen! https://example.test',expected:{heading:'',text:''}})).status,200);assert.equal((await call('/api/public-intro',admin,{heading:'Stale',text:'Stale',expected:{heading:'',text:''}})).status,409);assert.equal((await (await call('/api/public-intro',{})).json()).text,'Willkommen! https://example.test');
// Analytics retain ISO storage while displaying German CSV dates and a seven-day default.
await db.prepare("INSERT INTO public_page_views(day,entry_id,source,views,authenticated_views) VALUES('2026-10-10','','direct',3,0)").run();
const analytics=await (await call('/api/analytics?to=2026-10-10')).json();assert.equal(analytics.from,'2026-10-04');assert.equal(analytics.to,'2026-10-10');assert.equal(analytics.totals.total,3);
const csv=await (await call('/api/analytics?format=csv&from=2026-10-10&to=2026-10-10')).text();assert.match(csv,/10\.10\.2026/);assert.doesNotMatch(csv,/2026-10-10/);
const mobileHtml=await (await call('/')).text(),viewportTag=mobileHtml.match(/<meta[^>]*name="viewport"[^>]*>/)?.[0];assert.ok(viewportTag);assert.match(viewportTag,/width=device-width/);assert.match(viewportTag,/initial-scale=1/);assert.doesNotMatch(viewportTag,/maximum-scale|minimum-scale|user-scalable=no/);
// Sites guest preview and stored role enforce selected fields and current-file access.
const guest={'oai-authenticated-user-id':'guest','oai-authenticated-user-email':'guest@example.test'},manager={'oai-authenticated-user-id':'manager','oai-authenticated-user-email':'manager@example.test'};
for(const [identity,role] of [[guest,'guest'],[manager,'manager']])await db.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),'chatgpt',identity['oai-authenticated-user-id'],role,new Date().toISOString(),role).run();
const entryId=crypto.randomUUID(),fileKey=crypto.randomUUID(),oldFileKey=crypto.randomUUID();const fileBucket=await mf.getR2Bucket('BUCKET');await fileBucket.put(fileKey,'private document',{httpMetadata:{contentType:'application/pdf'}});
const entry={id:entryId,title:'Guest visible title',category:'Artefakt',period:'1900',start:'',end:'',place:'Secret place',description:'Guest description',sources:'Secret source',interpretation:'Secret interpretation',uncertainty:'',rights:'Secret rights',tags:'',status:'Offen',files:[{key:fileKey,name:'Secret document.pdf',type:'application/pdf'}]};assert.equal((await call('/api/entries',user,entry)).status,200);await fileBucket.put(oldFileKey,'historical private document',{httpMetadata:{contentType:'application/pdf'}});await db.prepare('INSERT INTO entry_versions(entry_id,data,created,action) VALUES(?,?,?,?)').bind(entryId,JSON.stringify({...entry,files:[{key:oldFileKey,name:'Old.pdf',type:'application/pdf'}]}),new Date().toISOString(),'Ausgangsstand').run();
assert.equal((await call('/api/public-fields',manager)).status,403);assert.equal((await call('/api/activity',user)).status,403);assert.equal((await call('/api/activity',manager)).status,200);
for(const path of ['/api/activity','/api/public-fields','/api/guest-fields','/api/system-settings','/api/publication?id='+entryId,'/api/messages','/api/qr-access-alerts','/api/storage-places','/api/entries?history='+entryId,'/api/entries?deleted=1','/api/comments?entry='+entryId])assert.equal((await call(path,guest)).status,403,path);
assert.equal((await call('/api/guest-fields',admin,{fields:['title','description']})).status,200);let projected=await (await call('/api/entries',guest)).json();assert.equal(projected.length,1);assert.equal(projected[0].title,entry.title);assert.equal(projected[0].description,entry.description);assert.equal(projected[0].sources,'');assert.equal(projected[0].place,'');assert.deepEqual(projected[0].files,[]);assert.doesNotMatch(JSON.stringify(projected),/Secret/);
assert.equal((await call('/api/files?key='+fileKey,guest)).status,403);assert.equal((await call('/api/entries',guest,{...entry,title:'Illegal'})).status,403);assert.equal((await call('/api/guest-fields',guest,{fields:['rights']})).status,403);
assert.equal((await call('/api/guest-fields',admin,{fields:['title','documents']})).status,200);assert.equal((await call('/api/files?key='+fileKey,guest)).status,200);assert.equal((await call('/api/files?key='+oldFileKey,guest)).status,403);assert.equal((await (await call('/api/entries',guest)).json())[0].files[0].key,fileKey);
const preview=await call('/api/entries',{...admin,'x-archive-preview-role':'guest'});assert.equal((await preview.json())[0].description,'');
assert.equal((await call('/api/guest-fields',admin,{fields:[]})).status,200);assert.equal((await call('/api/files?key='+fileKey,guest)).status,403);projected=await (await call('/api/entries',guest)).json();assert.equal(projected[0].title,'Beitrag');assert.doesNotMatch(JSON.stringify(projected),/Guest visible title|Secret/);
assert.equal((await call('/api/guest-fields',admin,{fields:['not-a-field']})).status,400);
console.log('PASS: Sites guests cannot read hidden fields, historical files, comments or administrative data; admin preview matches and field revocation takes effect.');
// A new export carries portable installation metadata without passwords.
const created=await (await call('/api/backups',admin,{action:'create',destination:'local'})).json();assert.ok(created.id);let job;for(let i=0;i<30;i++){const response=await call('/api/backups',admin,{action:'advance',id:created.id});assert.equal(response.status,200);job=await response.json();if(job.status==='complete')break;}assert.equal(job.status,'complete');const bucket=await mf.getR2Bucket('BUCKET'),manifest=await (await bucket.get('_backups/'+created.id+'/manifest.json')).json();assert.equal(manifest.format,'history-archive-backup-v2');assert.equal(manifest.installation.place,'Neuer Ort');assert.equal(manifest.installation.association,'Umbenannter Verein');assert.equal(manifest.installation.subtitle,'Unser digitales Archiv');assert.match(manifest.schema.sha256,/^[a-f0-9]{64}$/);assert.equal(manifest.applicationVersion,applicationVersion);assert.equal(manifest.databaseSchemaVersion,applicationSchema);assert.equal(manifest.backupFormatVersion,2);assert.equal(manifest.passwordsIncluded,false);const exportedSettings=await (await bucket.get('_backups/'+created.id+'/tables/archive_settings.json')).json();assert.equal(JSON.parse(exportedSettings.find(x=>x.key==='design').data).theme,'plum');assert.equal(JSON.parse(exportedSettings.find(x=>x.key==='public_intro').data).heading,'Eigene Überschrift');console.log('PASS: mandatory admin-only setup, locked completion, neutral branding and portable backup metadata.');}finally{await mf.dispose()}
