import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url),{Miniflare}=require(require.resolve('miniflare',{paths:[require.resolve('wrangler')]}));
const modules=[{type:'ESModule',path:resolve('dist/server/index.js')},...readdirSync('dist/server',{recursive:true}).filter(p=>p.endsWith('.js')&&p!=='index.js').map(p=>({type:'ESModule',path:resolve('dist/server',p)}))];
const mf=new Miniflare({modules,modulesRoot:resolve('dist/server'),modulesRules:[{type:'ESModule',include:['**/*.js','**/*.mjs'],fallthrough:true}],compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],bindings:{ARCHIVE_BOOTSTRAP_ADMIN_EMAIL:'admin@example.test'},d1Databases:['DB'],r2Buckets:['BUCKET']});
const admin={'oai-authenticated-user-id':'new-admin','oai-authenticated-user-email':'admin@example.test'},user={'oai-authenticated-user-id':'visitor','oai-authenticated-user-email':'visitor@example.test'};
const call=(route,identity=admin,data)=>mf.dispatchFetch('https://archive.test'+route,{method:data?'POST':'GET',headers:{...identity,...(data?{Origin:'https://archive.test','Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});
try{const db=await mf.getD1Database('DB');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const s of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(s.trim())await db.prepare(s).run();let r=await call('/api/installation');let config=await r.json();assert.equal(config.completed,false);assert.equal(config.canSetup,true);r=await call('/api/installation',user,{place:'Ort',association:'Verein'});assert.equal(r.status,403);r=await call('/api/installation',admin,{place:'',association:'Verein'});assert.equal(r.status,400);r=await call('/api/installation',admin,{place:'Neuer Ort',association:'Neuer Verein',domain:''});assert.equal(r.status,200);config=await (await call('/api/installation')).json();assert.equal(config.place,'Neuer Ort');assert.equal(config.association,'Neuer Verein');assert.equal(config.completed,true);assert.equal((await call('/api/installation',admin,{place:'Überschreiben',association:'Anderer Verein'})).status,409);assert.equal((await db.prepare('SELECT count(*) AS n FROM entries').first()).n,0);
assert.equal((await call('/api/design',admin,{theme:'plum',expectedTheme:'sage'})).status,200);
// A new export carries portable installation metadata without passwords.
const created=await (await call('/api/backups',admin,{action:'create',destination:'local'})).json();assert.ok(created.id);let job;for(let i=0;i<30;i++){const response=await call('/api/backups',admin,{action:'advance',id:created.id});assert.equal(response.status,200);job=await response.json();if(job.status==='complete')break;}assert.equal(job.status,'complete');const bucket=await mf.getR2Bucket('BUCKET'),manifest=await (await bucket.get('_backups/'+created.id+'/manifest.json')).json();assert.equal(manifest.format,'history-archive-backup-v2');assert.equal(manifest.installation.place,'Neuer Ort');assert.match(manifest.schema.sha256,/^[a-f0-9]{64}$/);assert.equal(manifest.applicationVersion,'0.2.0');assert.equal(manifest.databaseSchemaVersion,15);assert.equal(manifest.backupFormatVersion,2);assert.equal(manifest.passwordsIncluded,false);const exportedSettings=await (await bucket.get('_backups/'+created.id+'/tables/archive_settings.json')).json();assert.equal(JSON.parse(exportedSettings.find(x=>x.key==='design').data).theme,'plum');console.log('PASS: mandatory admin-only setup, locked completion, neutral branding and portable backup metadata.');}finally{await mf.dispose()}
