import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash,generateKeyPairSync,randomBytes,sign} from 'node:crypto';
import {sqliteBinding,fileBucket} from '../server/linux-storage.mjs';
import {authService} from '../server/auth-service.mjs';
const root=await fs.mkdtemp(path.resolve('.update-test-linux-')),storage=sqliteBinding(path.join(root,'archive.sqlite'),path.resolve('drizzle')),db=storage.database;
// Small CBOR encoder used only to emulate a real software authenticator in this test.
function cbor(v){const header=(major,n)=>n<24?Buffer.from([major*32+n]):n<256?Buffer.from([major*32+24,n]):Buffer.from([major*32+25,n>>8,n&255]);if(typeof v==='number')return header(v>=0?0:1,v>=0?v:-1-v);if(Buffer.isBuffer(v))return Buffer.concat([header(2,v.length),v]);if(typeof v==='string'){const b=Buffer.from(v);return Buffer.concat([header(3,b.length),b])}if(v instanceof Map)return Buffer.concat([header(5,v.size),...[...v].flatMap(([k,x])=>[cbor(k),cbor(x)])]);throw Error('Unsupported fixture type')}
const origin='http://localhost:8080',key='a'.repeat(64),service=authService(db,{origin,sessionKey:key}),rpHash=createHash('sha256').update('localhost').digest();
function credential(options,overrideOrigin=origin){const {publicKey,privateKey}=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),j=publicKey.export({format:'jwk'}),id=randomBytes(32),cose=cbor(new Map([[1,2],[3,-7],[-1,1],[-2,Buffer.from(j.x,'base64url')],[-3,Buffer.from(j.y,'base64url')]])),length=Buffer.alloc(2);length.writeUInt16BE(id.length);const authData=Buffer.concat([rpHash,Buffer.from([0x45]),Buffer.alloc(4),Buffer.alloc(16),length,id,cose]),client=Buffer.from(JSON.stringify({type:'webauthn.create',challenge:options.challenge,origin:overrideOrigin,crossOrigin:false}));return {id:id.toString('base64url'),privateKey,response:{id:id.toString('base64url'),rawId:id.toString('base64url'),type:'public-key',response:{clientDataJSON:client.toString('base64url'),attestationObject:cbor(new Map([['fmt','none'],['attStmt',new Map()],['authData',authData]])).toString('base64url'),transports:['internal']},clientExtensionResults:{}}}}
function assertion(options,k,counter=1){const n=Buffer.alloc(4);n.writeUInt32BE(counter);const authData=Buffer.concat([rpHash,Buffer.from([5]),n]),client=Buffer.from(JSON.stringify({type:'webauthn.get',challenge:options.challenge,origin,crossOrigin:false}));return {id:k.id,rawId:k.id,type:'public-key',response:{authenticatorData:authData.toString('base64url'),clientDataJSON:client.toString('base64url'),signature:sign('sha256',Buffer.concat([authData,createHash('sha256').update(client).digest()]),k.privateKey).toString('base64url')},clientExtensionResults:{}}}
try{
 const bucket=fileBucket(path.join(root,'bucket'));await bucket.put('../../key','abcdef',{httpMetadata:{contentType:'text/plain'},customMetadata:{name:'sample'}});assert.equal(await (await bucket.get('../../key')).text(),'abcdef');assert.equal(await new Response((await bucket.get('../../key',{range:{offset:1,length:3}})).body).text(),'bcd');await bucket.put('other','two');const list=await bucket.list({limit:1});assert.equal(list.truncated,true);assert.equal((await bucket.list({cursor:list.cursor})).objects.length,1);
 const first=service.invite({email:'admin@example.test',name:'Test Admin',role:'admin'},true),registration=await service.registrationOptions(first),k=credential(registration.options);const session=await service.register(registration.challenge,k.response);assert.ok(session.includes('.'));assert.equal(service.accounts()[0].role,'admin');await assert.rejects(()=>service.register(registration.challenge,k.response));assert.throws(()=>service.invite({email:'other@example.test',name:'Other',role:'admin'},true));await assert.rejects(()=>service.registrationOptions(first));
 const login=await service.loginOptions();assert.ok(await service.login(login.challenge,assertion(login.options,k)));await assert.rejects(()=>service.login(login.challenge,assertion(login.options,k,2)));
 const wrong=service.invite({email:'user@example.test',name:'Test User',role:'user'}),options=await service.registrationOptions(wrong);await assert.rejects(()=>service.register(options.challenge,credential(options.options,'https://attacker.test').response));assert.equal(service.accounts().length,1);
 const secondOptions=await service.registrationOptions(wrong),k2=credential(secondOptions.options);await service.register(secondOptions.challenge,k2.response);const accounts=service.accounts(),admin=accounts.find(a=>a.role==='admin'),user=accounts.find(a=>a.role==='user');service.edit(user.id,'manager',false,admin.id);assert.equal(service.accounts().find(a=>a.id===user.id).role,'manager');service.edit(user.id,'manager',true,admin.id);const blocked=await service.loginOptions();await assert.rejects(()=>service.login(blocked.challenge,assertion(blocked.options,k2)));assert.throws(()=>service.edit(admin.id,'user',true,admin.id));
 const before=db.prepare('SELECT count(*) AS n FROM archive_users').get().n;await assert.rejects(()=>storage.batch([storage.prepare("INSERT INTO archive_settings(key,data,updated,updated_by) VALUES('rollback-test','{}','now','test')"),storage.prepare('INSERT INTO nonexistent_table VALUES(1)')]));assert.equal(db.prepare("SELECT key FROM archive_settings WHERE key='rollback-test'").get(),undefined);assert.equal(db.prepare('SELECT count(*) AS n FROM archive_users').get().n,before);
 console.log('PASS: SQLite migrations/atomic rollback, file storage/ranges/pagination, real signed WebAuthn registration/login, origin verification, single-use challenges/invites, roles and disabled accounts.');
}finally{storage.close();await fs.rm(root,{recursive:true,force:true})}
