import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createHmac} from 'node:crypto';
import {sqliteBinding} from '../server/linux-storage.mjs';
import {initializeAuth} from '../server/auth-service.mjs';
const root=await fs.mkdtemp(path.resolve('.update-test-http-')),key='b'.repeat(64),storage=sqliteBinding(path.join(root,'archive.sqlite'),path.resolve('drizzle'));
initializeAuth(storage.database);for(const role of ['admin','manager','user','guest']){storage.database.prepare('INSERT INTO linux_accounts(id,email,name) VALUES(?,?,?)').run(role,role+'@example.test','Test '+role);storage.database.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').run(role,'linux',role,'Test '+role,new Date().toISOString(),role)}storage.close();
const port=18404,origin='http://localhost:'+port,standalone=process.env.ARCHIVE_TEST_STANDALONE_ROOT;await fs.writeFile(path.join(root,'app.env'),`ARCHIVE_ORIGIN=${origin}\nARCHIVE_SESSION_KEY=${key}\nARCHIVE_SETTINGS_KEY=${key}\nARCHIVE_RUNNER_KEY=${key}\n`);const server=spawn(process.execPath,standalone?['scripts/linux-start.mjs']:['node_modules/next/dist/bin/next','start','-H','127.0.0.1','-p',String(port)],{cwd:standalone||process.cwd(),env:{...process.env,PORT:String(port),ARCHIVE_CONFIG_FILE:path.join(root,'app.env'),ARCHIVE_BUILD_TARGET:'linux',ARCHIVE_ORIGIN:origin,ARCHIVE_SESSION_KEY:key,ARCHIVE_SETTINGS_KEY:key,ARCHIVE_RUNNER_KEY:key,ARCHIVE_DATA_DIR:root,ARCHIVE_MAINTENANCE_FILE:path.join(root,'maintenance'),ARCHIVE_INITIAL_PLACE:'Testort',ARCHIVE_INITIAL_ASSOCIATION:'Testverein',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
function cookie(role){const t=Math.floor(Date.now()/1000),p=Buffer.from(JSON.stringify({issuer:'archive-linux-session-v1',subject:role,email:role+'@example.test',name:'Test '+role,iat:t,exp:t+3600})).toString('base64url');return 'archive_session='+p+'.'+createHmac('sha256',key).update(p).digest('base64url')}
async function request(url,role,body){return fetch(origin+url,{method:body?'POST':'GET',headers:{...(role?{Cookie:cookie(role)}:{}),...(body?{Origin:origin,'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined})}
try{let ready=false;for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}assert.ok(ready,output);assert.equal((await request('/api/auth')).status,200);assert.equal((await request('/api/entries')).status,401);assert.equal((await fetch(origin+'/api/entries',{headers:{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'admin@example.test'}})).status,401);for(const role of ['admin','manager','user']){const r=await request('/api/session',role);const session=await r.json();assert.equal(session.role,role);assert.equal(session.canLogout,true);assert.equal((await request('/api/entries',role)).status,200)}assert.equal((await request('/api/system-settings','user')).status,403);assert.equal((await request('/api/auth','manager',{action:'invite',email:'new@example.test',name:'New',role:'admin'})).status,403);let r=await request('/api/auth','admin',{action:'invite',email:'new@example.test',name:'New',role:'user'});assert.equal(r.status,200);assert.match((await r.json()).url,/\/anmelden#einladung=/);r=await fetch(origin+'/api/auth',{method:'POST',headers:{Origin:'https://attacker.test','Content-Type':'application/json',Cookie:cookie('admin')},body:JSON.stringify({action:'login-options'})});assert.equal(r.status,403);for(const p of ['/api/backups/run','/api/timeline-rotation/run'])assert.equal((await request(p)).status,403);r=await fetch(origin+'/api/backups/run',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.equal((await r.json()).enabled,false);r=await request('/api/backups','admin',{action:'create',destination:'local'});assert.equal(r.status,201);const backup=(await r.json()).id;let completed=false;for(let i=0;i<20;i++){r=await request('/api/backups','admin',{action:'advance',id:backup});assert.equal(r.status,200);const status=await r.json();if(status.status==='complete'){completed=true;break;}assert.notEqual(status.status,'error',JSON.stringify(status));}assert.ok(completed);const backupList=await (await request('/api/backups','admin')).json();const savedBackup=backupList.find(b=>b.id===backup);assert.equal(savedBackup.status,'complete');assert.equal(savedBackup.applicationVersion,JSON.parse(await fs.readFile('version.json','utf8')).version);r=await request('/api/backups?download='+backup,'admin');assert.equal(r.status,200);assert.ok((await r.arrayBuffer()).byteLength>1024);assert.equal((await fetch(origin+'/anmelden')).status,200);assert.equal((await fetch(origin+'/')).status,200);
 for(const role of ['admin','manager','user']){const keys=await (await request('/api/auth?passkeys',role)).json();assert.equal(keys.authenticated,true);assert.deepEqual(keys.passkeys,[]);assert.equal((await request('/api/auth',role,{action:'passkey-rename',id:'foreign',name:'No'})).status,400)}assert.equal((await request('/api/auth',null,{action:'passkey-auth-options'})).status,401);const adminAccounts=await (await request('/api/auth','admin')).json();assert.ok(adminAccounts.accounts.every(a=>a.passkeyCount===0&&a.lastLogin===null));assert.equal(adminAccounts.mailAvailable,true);assert.equal((await request('/api/system-settings','user',{action:'smtp-test',to:'test@example.test'})).status,403);assert.equal((await request('/api/system-settings','admin',{action:'smtp-test',to:'bad'})).status,400);

 assert.equal((await request('/api/push')).status,401);
 for(const role of ['admin','manager','user']){const p=await (await request('/api/push',role)).json();assert.equal(p.available,true);assert.equal(p.enabled,false);assert.equal(p.preferences.qr,true);assert.equal(p.topics.length,role==='admin'?6:role==='manager'?3:2);assert.equal(p.topics.some(t=>t.id==='publication'),false);assert.equal((await request('/api/push',role,{action:'save',enabled:false,preferences:p.preferences,account_id:'admin'})).status,200)}
 assert.equal((await request('/api/push','user',{action:'save',enabled:true,preferences:{backup:true}})).status,400);
 assert.equal((await request('/api/push','user',{action:'subscribe',subscription:{endpoint:'https://127.0.0.1/internal',keys:{}}})).status,400);
 assert.equal((await fetch(origin+'/api/push',{method:'POST',headers:{Origin:'https://attacker.test','Content-Type':'application/json',Cookie:cookie('admin')},body:'{}'})).status,403);
 assert.equal((await request('/api/push/run',null,{})).status,403);
 const pushRun=await fetch(origin+'/api/push/run',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:'{}'});assert.equal(pushRun.status,200);assert.equal((await pushRun.json()).sent,0);
 assert.equal((await request('/push-worker.js')).status,200);const manifest=await (await request('/manifest.webmanifest')).json();assert.equal(manifest.display,'standalone');assert.equal(manifest.start_url,'/');
 assert.equal((await request('/api/messages')).status,401);
 const mailbox=await (await request('/api/messages','user')).json();assert.equal(mailbox.available,true);assert.equal(mailbox.unread,0);assert.equal(mailbox.recipients.length,2);
 const message=await request('/api/messages','user',{action:'send',subject:'Private subject',body:'Private body',recipients:['manager'],sender_id:'admin'});assert.equal(message.status,201);const threadId=(await message.json()).threadId;
 assert.equal((await request('/api/messages?thread='+threadId,'admin')).status,400);
 assert.equal((await request('/api/messages','admin',{action:'send',threadId,body:'Intrusion'})).status,400);
 const unread=await (await request('/api/messages?count=1','manager')).json();assert.equal(unread.unread,1);
 const conversation=await (await request('/api/messages?thread='+threadId,'manager')).json();assert.equal(conversation.messages[0].sender_id,'user');assert.equal(conversation.members.length,2);
 assert.equal((await request('/api/messages','manager',{action:'read',threadId,lastId:conversation.messages[0].id})).status,200);assert.equal((await (await request('/api/messages?count=1','manager')).json()).unread,0);
 assert.equal((await fetch(origin+'/api/messages',{method:'POST',headers:{Origin:'https://attacker.test','Content-Type':'application/json',Cookie:cookie('user')},body:JSON.stringify({action:'send',threadId,body:'Bad origin'})})).status,403);
 assert.equal((await fetch(origin+'/api/messages',{headers:{Cookie:cookie('admin'),'x-archive-preview-role':'public'}})).status,403);
 const preview=await fetch(origin+'/api/session',{headers:{Cookie:cookie('admin'),'x-archive-preview-role':'user'}});const previewSession=await preview.json();assert.equal(previewSession.role,'admin');assert.equal(previewSession.canPreview,true);assert.equal(previewSession.canLogout,true);
 const logout=await request('/api/auth','user',{action:'logout'});assert.equal(logout.status,200);assert.match(logout.headers.get('set-cookie'),/archive_session=;.*Max-Age=0/);assert.equal((await (await request('/api/session')).json()).canLogout,false);
 const originalManifest=await (await fetch(origin+'/manifest.webmanifest')).json();assert.equal(originalManifest.name,'Geschichte Testorts');assert.equal(originalManifest.short_name,originalManifest.name);
 assert.equal((await request('/api/installation','admin',{action:'save-title',title:'Testarchiv Produktion'})).status,200);
 const updatedManifest=await (await fetch(origin+'/manifest.webmanifest')).json();assert.equal(updatedManifest.name,'Testarchiv Produktion');assert.equal(updatedManifest.short_name,'Testarchiv Produktion');assert.equal(updatedManifest.id,originalManifest.id);
 const installedHtml=await (await fetch(origin+'/')).text();assert.match(installedHtml,/<meta[^>]*name="apple-mobile-web-app-title"[^>]*content="Testarchiv Produktion"/);assert.match(installedHtml,/<meta[^>]*name="application-name"[^>]*content="Testarchiv Produktion"/);
 const mobileHtml=await (await fetch(origin+'/')).text(),viewportTag=mobileHtml.match(/<meta[^>]*name="viewport"[^>]*>/)?.[0];assert.ok(viewportTag);assert.match(viewportTag,/width=device-width/);assert.match(viewportTag,/initial-scale=1/);assert.doesNotMatch(viewportTag,/maximum-scale|minimum-scale|user-scalable=no/);
 console.log('PASS: native Linux HTTP runtime, anonymous/OAI access denied, signed roles, admin-only invitations/settings, cross-origin protection, authenticated background runners, login and public pages.');
const entryId=crypto.randomUUID();let published=await request('/api/entries','user',{id:entryId,title:'Veröffentlichungsanfrage',category:'Ereignis',period:'1900',start:'',end:'',place:'Testort',description:'Bitte prüfen.',sources:'',interpretation:'',uncertainty:'',rights:'',tags:'',status:'Offen',files:[]});assert.equal(published.status,200,await published.clone().text());
 // Guest role: all current entries, exact field projection, no indirect administrative leaks.
 assert.equal((await request('/api/auth','admin',{action:'invite',email:'new-guest@example.test',name:'Gast',role:'guest'})).status,200);
 assert.equal((await (await request('/api/session','guest')).json()).role,'guest');
 for(const path of ['/api/activity','/api/public-fields','/api/guest-fields','/api/system-settings','/api/publication?id='+entryId,'/api/messages','/api/qr-access-alerts','/api/storage-places','/api/entries?history='+entryId,'/api/entries?deleted=1','/api/comments?entry='+entryId])assert.equal((await request(path,'guest')).status,403,path);
 assert.equal((await request('/api/activity','user')).status,403);assert.equal((await request('/api/activity','manager')).status,200);
 assert.equal((await request('/api/public-fields','manager')).status,403);
 assert.equal((await request('/api/guest-fields','admin',{fields:['title']})).status,200);
 let guestEntries=await (await request('/api/entries','guest')).json();assert.equal(guestEntries[0].title,'Veröffentlichungsanfrage');assert.equal(guestEntries[0].description,'');assert.equal(guestEntries[0].period,'');assert.deepEqual(guestEntries[0].files,[]);assert.equal('qrPrintedUrls' in guestEntries[0],false);
 assert.equal((await request('/api/entries','guest',{id:entryId,title:'Overwrite'})).status,403);
 assert.equal((await request('/api/guest-fields','guest',{fields:['sources']})).status,403);
 assert.equal((await request('/api/guest-fields','admin',{fields:['title','description']})).status,200);guestEntries=await (await request('/api/entries','guest')).json();assert.equal(guestEntries[0].description,'Bitte prüfen.');
 const guestPreview=await fetch(origin+'/api/entries',{headers:{Cookie:cookie('admin'),'x-archive-preview-role':'guest'}});assert.equal((await guestPreview.json())[0].period,'');
 console.log('PASS: Linux guest invitations, current entry field projection, admin-only field controls and blocked guest/user administrative access.');
 const meta=(await (await request('/api/publication?id='+entryId,'user')).json())[0],requestData={action:'request',id:entryId,updated:meta.updated,version:meta.currentVersion};published=await request('/api/publication','user',requestData);assert.equal(published.status,200,await published.clone().text());assert.equal((await request('/api/publication','user',requestData)).status,409);
 const notifications=await (await request('/api/messages','admin')).json();assert.equal(notifications.unread,1);assert.equal(notifications.openRequests[0].id,entryId);assert.equal(notifications.openRequests[0].requester,'Test user');assert.equal((await (await request('/api/messages','user')).json()).openRequests.length,0);assert.equal((await (await request('/api/messages?count=1','manager')).json()).unread,1);assert.equal((await (await request('/api/messages?count=1','user')).json()).unread,0);
 const notification=notifications.threads.find(t=>t.notification);assert.ok(notification);const linked=await (await request('/api/messages?thread='+notification.id,'admin')).json();assert.equal(linked.entry.id,entryId);assert.equal(linked.requester,'Test user');assert.equal(notification.requester,'Test user');assert.match(linked.messages[0].body,/^Angefragt von: Test user\n/);assert.equal(linked.entry.pending,null);assert.equal((await request('/api/messages?thread='+notification.id,'user')).status,400);
 assert.equal((await request('/api/messages','user',{action:'hide',threadId:notification.id,throughId:notification.lastMessageId})).status,400);assert.equal((await request('/api/messages','admin',{action:'hide',threadId:notification.id,throughId:notification.lastMessageId})).status,200);const afterDelete=await (await request('/api/messages','admin')).json();assert.equal(afterDelete.unread,0);assert.ok(!afterDelete.threads.some(t=>t.id===notification.id));assert.equal(afterDelete.openRequests[0].id,entryId);assert.equal((await (await request('/api/messages?count=1','manager')).json()).unread,1);
 published=await request('/api/publication','admin',{...requestData,action:'approve'});assert.equal(published.status,200,await published.clone().text());assert.equal((await published.json()).status,'approved');assert.equal((await (await request('/api/messages','admin')).json()).openRequests.length,0);
 console.log('PASS: authenticated Linux publication request creates one linked notification for each reviewer; duplicate and ordinary-user access rejected; existing approval endpoint retained.');
 await fs.writeFile(path.join(root,'maintenance'),'1');assert.equal((await request('/api/entries','admin')).status,503);assert.equal((await request('/api/backups/run')).status,503);const health=await (await fetch(origin+'/api/health')).json();assert.equal(health.ok,true);assert.equal(health.schema,JSON.parse(await fs.readFile('version.json','utf8')).databaseSchemaVersion);assert.equal((await request('/api/updates','admin')).status,200);await fs.writeFile(path.join(root,'maintenance'),'0');assert.equal((await request('/api/entries','admin')).status,200);console.log('PASS: maintenance blocks authenticated writes and background endpoints; health and updater stay reachable.');
}finally{server.kill('SIGTERM');await new Promise(resolve=>{if(server.exitCode!==null)return resolve();server.once('exit',resolve)});await fs.rm(root,{recursive:true,force:true})}
