import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createHmac} from 'node:crypto';
import {sqliteBinding} from '../server/linux-storage.mjs';
import {initializeAuth} from '../server/auth-service.mjs';
const root=await fs.mkdtemp(path.resolve('.update-test-http-')),key='b'.repeat(64),storage=sqliteBinding(path.join(root,'archive.sqlite'),path.resolve('drizzle'));
initializeAuth(storage.database);for(const role of ['admin','manager','user']){storage.database.prepare('INSERT INTO linux_accounts(id,email,name) VALUES(?,?,?)').run(role,role+'@example.test','Test '+role);storage.database.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').run(role,'linux',role,'Test '+role,new Date().toISOString(),role)}storage.close();
const port=18404,origin='http://localhost:'+port,server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-H','127.0.0.1','-p',String(port)],{env:{...process.env,ARCHIVE_BUILD_TARGET:'linux',ARCHIVE_ORIGIN:origin,ARCHIVE_SESSION_KEY:key,ARCHIVE_SETTINGS_KEY:key,ARCHIVE_RUNNER_KEY:key,ARCHIVE_DATA_DIR:root,ARCHIVE_INITIAL_PLACE:'Testort',ARCHIVE_INITIAL_ASSOCIATION:'Testverein',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']});let output='';server.stdout.on('data',b=>output+=b);server.stderr.on('data',b=>output+=b);
function cookie(role){const t=Math.floor(Date.now()/1000),p=Buffer.from(JSON.stringify({issuer:'archive-linux-session-v1',subject:role,email:role+'@example.test',name:'Test '+role,iat:t,exp:t+3600})).toString('base64url');return 'archive_session='+p+'.'+createHmac('sha256',key).update(p).digest('base64url')}
async function request(url,role,body){return fetch(origin+url,{method:body?'POST':'GET',headers:{...(role?{Cookie:cookie(role)}:{}),...(body?{Origin:origin,'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined})}
try{let ready=false;for(let i=0;i<100;i++){try{if((await fetch(origin+'/api/health')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}assert.ok(ready,output);assert.equal((await request('/api/auth')).status,200);assert.equal((await request('/api/entries')).status,401);assert.equal((await fetch(origin+'/api/entries',{headers:{'oai-authenticated-user-id':'admin','oai-authenticated-user-email':'admin@example.test'}})).status,401);for(const role of ['admin','manager','user']){const r=await request('/api/session',role);assert.equal((await r.json()).role,role);assert.equal((await request('/api/entries',role)).status,200)}assert.equal((await request('/api/system-settings','user')).status,403);assert.equal((await request('/api/auth','manager',{action:'invite',email:'new@example.test',name:'New',role:'admin'})).status,403);let r=await request('/api/auth','admin',{action:'invite',email:'new@example.test',name:'New',role:'user'});assert.equal(r.status,200);assert.match((await r.json()).url,/\/anmelden#einladung=/);r=await fetch(origin+'/api/auth',{method:'POST',headers:{Origin:'https://attacker.test','Content-Type':'application/json',Cookie:cookie('admin')},body:JSON.stringify({action:'login-options'})});assert.equal(r.status,403);for(const p of ['/api/backups/run','/api/timeline-rotation/run'])assert.equal((await request(p)).status,403);r=await fetch(origin+'/api/backups/run',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.equal((await r.json()).enabled,false);r=await request('/api/backups','admin',{action:'create',destination:'local'});assert.equal(r.status,201);const backup=(await r.json()).id;let completed=false;for(let i=0;i<20;i++){r=await request('/api/backups','admin',{action:'advance',id:backup});assert.equal(r.status,200);const status=await r.json();if(status.status==='complete'){completed=true;break;}assert.notEqual(status.status,'error',JSON.stringify(status));}assert.ok(completed);r=await request('/api/backups?download='+backup,'admin');assert.equal(r.status,200);assert.ok((await r.arrayBuffer()).byteLength>1024);assert.equal((await fetch(origin+'/anmelden')).status,200);assert.equal((await fetch(origin+'/')).status,200);
 console.log('PASS: native Linux HTTP runtime, anonymous/OAI access denied, signed roles, admin-only invitations/settings, cross-origin protection, authenticated background runners, login and public pages.');
}finally{server.kill('SIGTERM');await new Promise(resolve=>{if(server.exitCode!==null)return resolve();server.once('exit',resolve)});await fs.rm(root,{recursive:true,force:true})}
