import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createECDH,randomBytes} from 'node:crypto';
import webpush from 'web-push';
import {sqliteBinding} from '../server/linux-storage.mjs';
import {initializeAuth} from '../server/auth-service.mjs';
import {initializePush,pushService,validSubscription} from '../server/push-service.mjs';
const root=await fs.mkdtemp(path.resolve('.update-test-push-')),storage=sqliteBinding(path.join(root,'archive.sqlite'),path.resolve('drizzle')),db=storage.database;
const fixture=i=>{const ecdh=createECDH('prime256v1');ecdh.generateKeys();return {endpoint:'https://fcm.googleapis.com/fcm/send/fixture-'+i,keys:{p256dh:ecdh.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}}};
try{initializeAuth(db);for(const role of ['admin','manager','user']){db.prepare('INSERT INTO linux_accounts VALUES(?,?,?,0)').run(role,role+'@example.test',role);db.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').run(role,'linux',role,role,'now',role)}initializePush(db);const sent=[];let failure=null;const service=pushService(db,{origin:'https://archive.example.test',send:async(s,p,o)=>{if(failure)throw failure;const request=webpush.generateRequestDetails(s,p,o);assert.ok(request.body.length>0);assert.ok(request.headers.Authorization);assert.ok(!request.body.includes(Buffer.from(JSON.parse(p).body)));sent.push({endpoint:s.endpoint,payload:JSON.parse(p)})}});
for(const role of ['admin','manager','user']){const state=service.settings(role);assert.equal(state.enabled,false);assert.equal(state.preferences.qr,true);assert.equal(state.preferences.update,role==='admin'?false:undefined);service.subscribe(role,fixture(role));service.configure(role,true,state.preferences)}
assert.throws(()=>service.configure('user',true,{backup:true}));assert.throws(()=>service.configure('manager',true,{update:true}));assert.throws(()=>validSubscription({...fixture('bad'),endpoint:'https://127.0.0.1/private'}));assert.throws(()=>validSubscription({...fixture('bad'),endpoint:'https://fcm.googleapis.com.attacker.test/path'}));assert.throws(()=>validSubscription({...fixture('bad'),endpoint:'http://fcm.googleapis.com/path'}));assert.throws(()=>service.subscribe('user',JSON.parse(db.prepare("SELECT data FROM linux_push_subscriptions WHERE account_id='admin'").get().data)));
const id='entry';db.prepare("INSERT INTO entries(id,data,updated,publication_status,requested_at) VALUES(?,?,?,?,?)").run(id,JSON.stringify({title:'Sensitive title'}),'now','pending','first');service.scan();service.scan();assert.equal((await service.deliver()).sent,2);assert.equal(sent.filter(x=>x.payload.tag==='archive-publication').length,2);assert.ok(sent.every(x=>!x.payload.body.includes('Sensitive')));
db.prepare("INSERT INTO archive_comments(id,entry_id,author_name,body,status,created) VALUES('comment',?,'Secret Person','Secret body','pending','now')").run(id);service.scan();assert.equal((await service.deliver()).sent,2);assert.ok(sent.every(x=>!x.payload.body.includes('Secret')));
db.prepare("INSERT INTO qr_access_alerts VALUES(?,1,'now')").run(id);service.scan();assert.equal((await service.deliver()).sent,3);db.prepare('UPDATE qr_access_alerts SET attempts=attempts+1').run();service.scan();assert.equal((await service.deliver()).sent,0);db.prepare("INSERT INTO entries(id,data,updated) VALUES('second','{}','now')").run();db.prepare("INSERT INTO qr_access_alerts VALUES('second',1,'now')").run();service.scan();assert.equal((await service.deliver()).sent,0);db.prepare('DELETE FROM qr_access_alerts').run();service.scan();assert.equal((await service.deliver()).sent,3);assert.match(sent.at(-1).payload.body,/behoben/);
db.prepare("INSERT INTO archive_backups VALUES('backup','now',NULL,'error','local','{}','Private error',NULL,'test')").run();service.scan();assert.equal((await service.deliver()).sent,1);
service.updates([{tag:'v1.0.0'}]);assert.equal((await service.deliver()).sent,0);service.configure('admin',true,{...service.settings('admin').preferences,update:true});service.updates([{tag:'v1.0.1',skipped:true},{tag:'v1.0.2'}]);assert.equal((await service.deliver()).sent,1);service.updates([{tag:'v1.0.2'}]);assert.equal((await service.deliver()).sent,0);
db.prepare("INSERT INTO linux_accounts VALUES('new','new@example.test','Secret Name',0)").run();db.prepare("INSERT INTO linux_credentials VALUES('key','new','public',0,'[]')").run();service.scan();assert.equal((await service.deliver()).sent,1);
db.prepare("UPDATE entries SET requested_at='second' WHERE id=?").run(id);service.scan();db.prepare("UPDATE archive_users SET role='user' WHERE identity_subject='manager'").run();assert.equal((await service.deliver()).sent,1);
db.prepare("UPDATE entries SET requested_at='third' WHERE id=?").run(id);service.scan();failure={statusCode:503};assert.equal((await service.deliver()).sent,0);assert.equal(service.settings('admin').deliveryErrors,1);assert.ok(db.prepare('SELECT attempts FROM linux_push_queue').get().attempts===1);failure=null;db.prepare('UPDATE linux_push_queue SET next_attempt=0').run();assert.equal((await service.deliver()).sent,1);
db.prepare("UPDATE entries SET requested_at='fourth' WHERE id=?").run(id);service.scan();service.configure('admin',false,service.settings('admin').preferences);assert.equal((await service.deliver()).sent,0);service.configure('admin',true,service.settings('admin').preferences);
db.prepare("UPDATE entries SET requested_at='fifth' WHERE id=?").run(id);service.scan();failure={statusCode:410};await service.deliver();assert.equal(service.settings('admin').devices,0);assert.equal(db.prepare('SELECT count(*) AS n FROM linux_push_queue').get().n,0);
initializePush(db);const seen=db.prepare('SELECT count(*) AS n FROM linux_push_seen').get().n;service.scan();assert.equal(db.prepare('SELECT count(*) AS n FROM linux_push_seen').get().n,seen);
console.log('PASS: role defaults, account ownership, SSRF rejection, encrypted Web Push payload, deduplicated requests, QR state transitions, activation/update/backup events, role revocation, disable, retry and expired device cleanup.');
}finally{storage.close();await fs.rm(root,{recursive:true,force:true})}
