import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import tls from 'node:tls';
import net from 'node:net';
import {spawnSync} from 'node:child_process';
import {sendSmtp} from '../server/smtp-service.mjs';
if(!process.env.SMTP_TEST_CERT){const dir=await fs.mkdtemp(path.resolve('.update-test-smtp-'));try{const cert=path.join(dir,'cert.pem'),key=path.join(dir,'key.pem');const c=spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=localhost','-addext','subjectAltName=DNS:localhost,IP:127.0.0.1']);assert.equal(c.status,0,c.stderr?.toString());const r=spawnSync(process.execPath,[process.argv[1]],{env:{...process.env,NODE_EXTRA_CA_CERTS:cert,SMTP_TEST_CERT:cert,SMTP_TEST_KEY:key},encoding:'utf8'});process.stdout.write(r.stdout);assert.equal(r.status,0,r.stderr)}finally{await fs.rm(dir,{recursive:true,force:true})}}else{
 const config={key:await fs.readFile(process.env.SMTP_TEST_KEY),cert:await fs.readFile(process.env.SMTP_TEST_CERT)},context=tls.createSecureContext(config);
 for(const mode of ['tls','starttls']){const messages=[],sockets=new Set();function track(s){sockets.add(s);s.on('close',()=>sockets.delete(s));s.on('error',()=>{})}function protocol(s,greet=true){track(s);if(greet)s.write('220 localhost SMTP\r\n');let buffer='',data=false,body='';const receive=chunk=>{buffer+=chunk.toString();while(buffer.includes('\r\n')){const n=buffer.indexOf('\r\n'),line=buffer.slice(0,n);buffer=buffer.slice(n+2);if(data){if(line==='.') {messages.push(body);body='';data=false;s.write('250 Queued\r\n')}else body+=line+'\r\n';continue}if(/^EHLO/.test(line))s.write('250-localhost\r\n250-STARTTLS\r\n250 AUTH PLAIN\r\n');else if(line==='STARTTLS'){s.write('220 Go TLS\r\n');s.removeListener('data',receive);const secure=new tls.TLSSocket(s,{isServer:true,secureContext:context});protocol(secure,false);return}else if(/^AUTH/.test(line))s.write('235 Authenticated\r\n');else if(/^MAIL FROM|^RCPT TO/.test(line))s.write('250 OK\r\n');else if(line==='DATA'){data=true;s.write('354 Send message\r\n')}else if(line==='QUIT'){s.end('221 Bye\r\n')}else s.write('250 OK\r\n')}};s.on('data',receive)}
 const server=mode==='tls'?tls.createServer(config,s=>protocol(s)):net.createServer(s=>protocol(s));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const settings={host:'127.0.0.1',port:server.address().port,tls:mode,from:'archive@example.test',sender:'Test Archive',username:'test',password:'fixture-secret'};assert.deepEqual(await sendSmtp(settings,{to:'recipient@example.test',subject:'SMTP check',text:'Test message'}),{accepted:true});assert.equal(messages.length,1);assert.match(messages[0],/To: recipient@example.test/);assert.match(messages[0],/Test message/);assert.doesNotMatch(messages[0],/fixture-secret/);await assert.rejects(()=>sendSmtp(settings,{to:'bad\r\nBcc: attacker@example.test',subject:'x',text:'x'}));await assert.rejects(()=>sendSmtp({...settings,tls:'none'},{to:'recipient@example.test',subject:'x',text:'x'}));}finally{for(const s of sockets)s.destroy();await new Promise(r=>server.close(r))}}
 console.log('PASS: SMTP sends actual local TLS and STARTTLS messages, destination/header validation and mandatory encryption.');
}
