import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {UpdateEngine} from '../server/update-engine.mjs';
const base=await fs.mkdtemp(path.resolve('.update-test-'));
async function fixture(name,fail=''){const dir=path.join(base,name),root=path.join(dir,'updater'),dataRoot=path.join(dir,'data'),configRoot=path.join(dir,'config'),old=path.join(root,'releases','old'),next=path.join(root,'releases','next');for(const p of [old,next,dataRoot,configRoot])await fs.mkdir(p,{recursive:true,mode:0o700});await fs.writeFile(path.join(dataRoot,'records.json'),'original');const db=new DatabaseSync(path.join(dataRoot,'archive.sqlite'));db.exec("CREATE TABLE records(id INTEGER PRIMARY KEY, title TEXT); INSERT INTO records VALUES(1,'preserved');");db.close();await fs.writeFile(path.join(configRoot,'secret.json'),'private configuration');for(const [p,v] of [[old,'0.2.1'],[next,'0.3.0']])await fs.writeFile(path.join(p,'version.json'),JSON.stringify({version:v,codeCommit:'a'.repeat(40),databaseSchemaVersion:15,backupFormatVersion:2}));await fs.symlink(old,path.join(root,'current'));const phases=[];const driver=async(action,code)=>{phases.push(action+':'+code);if(action==='migrate'){await fs.writeFile(path.join(dataRoot,'records.json'),'migrated');if(fail==='migrate')throw Error('migration failed')}if(action==='health'&&code===next&&fail==='health')throw Error('health failed')};const options={root,dataRoot,configRoot,driver,listReleases:async()=>[{tag:'v0.3.0',prerelease:false,draft:false},{tag:'v0.4.0',prerelease:true,draft:false}],prepareRelease:async(release,report)=>{await report('downloading');await report('building');return next},validateRestore:async(data,config)=>{if(fail==='backup')throw Error('restore trial failed');assert.equal(await fs.readFile(path.join(data,'records.json'),'utf8'),'original');assert.equal(await fs.readFile(path.join(config,'secret.json'),'utf8'),'private configuration')}};return {engine:await new UpdateEngine(options).init(),options,old,next,dataRoot,configRoot,phases};}
try{
 const f=await fixture('success');let s=await f.engine.check();assert.equal(s.releases.length,1);await f.engine.skip('v0.3.0');assert.equal((await f.engine.status()).releases.length,0);s=await f.engine.check(true);assert.equal(s.releases[0].skipped,true);s=await f.engine.startUpdate('v0.3.0');assert.equal(s.job.status,'complete');assert.deepEqual(s.job.events.map(e=>e.status),['preparing','downloading','building','stopping','backing_up','verifying_backup','migrating','starting','checking','complete']);assert.ok(s.job.events.every(e=>Number.isFinite(Date.parse(e.at))));assert.equal(s.job.previousVersion,'0.2.1');assert.ok(s.job.finished);assert.equal(s.currentVersion,'0.3.0');assert.equal(s.lastBackup.restoreTested,true);const manifest=JSON.parse(await fs.readFile(path.join(s.job.backup,'manifest.json')));assert.equal(manifest.applicationVersion,'0.2.1');assert.equal(manifest.codeCommit,'a'.repeat(40));assert.equal(await fs.readFile(path.join(s.job.backup,'data','records.json'),'utf8'),'original');
 for(const failure of ['migrate','health','backup']){const t=await fixture(failure,failure);const r=await t.engine.startUpdate('v0.3.0');assert.equal(r.job.status,'rolled_back',JSON.stringify(r.job));assert.equal(r.currentVersion,'0.2.1');assert.equal(r.job.events.at(-1).status,'rolled_back');assert.equal(await fs.readFile(path.join(t.dataRoot,'records.json'),'utf8'),'original');if(failure==='backup')assert.equal(t.phases.some(p=>p.startsWith('migrate:')),false);}
 // Simulate an interrupted migration: the independent agent recovers before serving new work.
 f.engine.state.job.status='migrating';f.engine.state.job.error='interrupted';await f.engine.persist();const recovered=await new UpdateEngine(f.options).init();assert.equal((await recovered.status()).currentVersion,'0.2.1');assert.equal(recovered.state.job.status,'rolled_back');assert.equal(await fs.readFile(path.join(f.dataRoot,'records.json'),'utf8'),'original');
 const corrupt=await fixture('corrupt');await corrupt.engine.startUpdate('v0.3.0');await fs.writeFile(path.join(corrupt.engine.state.job.backup,'data','records.json'),'corrupted');corrupt.engine.state.job.status='migrating';await corrupt.engine.persist();const blocked=await new UpdateEngine(corrupt.options).init();assert.equal(blocked.state.job.status,'error');assert.match(blocked.state.job.recoveryError,/beschädigt/);await assert.rejects(()=>blocked.startUpdate('v0.3.0'),/Wiederherstellung/);
 console.log('PASS: skip/manual rediscovery, stable-only releases, verified full snapshot, failed migrations/health, failed restore rehearsal, restart recovery and corrupted-backup blocking.');
}finally{await fs.rm(base,{recursive:true,force:true})}
