import {qrOrigin} from '@/lib/archive-qr-domain';
import {archiveDb} from '@/lib/archive-db';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import {resolveArchiveActor} from '@/lib/archive-identity';
import {ensureReference,entryReferencePath} from '@/lib/archive-references';
import {sameOrigin} from '@/lib/archive-comments';
function authorize(req:Request,kind:string){return requireArchiveAction(req,kind==='single'?'qrSingle':'qrBulk')}
export async function GET(req:Request){try{const access=await requireArchiveAction(req);const actor=await resolveArchiveActor(req);const params=new URL(req.url).searchParams;if(params.has('list')){await authorize(req,'bulk');const origin=await qrOrigin(req),r=await archiveDb().prepare("SELECT e.id,e.publication_status,r.reference,EXISTS(SELECT 1 FROM qr_print_items q WHERE q.entry_id=e.id AND q.printed=1) AS previouslyPrinted,(SELECT json_group_array(DISTINCT q.url) FROM qr_print_items q WHERE q.entry_id=e.id AND q.printed=1) AS urls FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id WHERE e.deleted=0").all();return Response.json(r.results.map((e:any)=>{const url=origin+entryReferencePath(e.reference)+'?quelle=qr',printed=JSON.parse(e.urls||'[]').some((v:string)=>{const u=new URL(v);u.search='';u.hash='';return u.href===origin+entryReferencePath(e.reference)});return {id:e.id,url,printed,published:e.publication_status==='approved',needsReprint:!!e.previouslyPrinted&&!printed}}),{headers:{'Cache-Control':'no-store'}})}const id=params.get('id');const row=await archiveDb().prepare('SELECT * FROM qr_print_jobs WHERE id=? AND created_by=?').bind(id,actor!.id).first<any>();if(!row)return Response.json({error:'Druckansicht nicht gefunden.'},{status:404});await authorize(req,row.kind);return Response.json({...row,labels:JSON.parse(row.labels)},{headers:{'Cache-Control':'no-store'}})}catch(e){return accessResponse(e)||Response.json({error:'Druckansicht konnte nicht geladen werden.'},{status:503})}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});const d=await req.json() as any;const actor=await resolveArchiveActor(req);if(!actor){await requireArchiveAction(req)}const db=archiveDb();
 if(d.action==='confirm'){const row=await db.prepare('SELECT kind,answer FROM qr_print_jobs WHERE id=? AND created_by=?').bind(d.jobId,actor!.id).first<any>();if(!row)return Response.json({error:'Druckansicht nicht gefunden.'},{status:404});await authorize(req,row.kind);if(!['yes','no'].includes(d.answer))return Response.json({error:'Bitte Ja oder Nein auswählen.'},{status:400});if(row.answer!=='pending')return Response.json({error:'Diese Druckansicht wurde bereits bestätigt.'},{status:409});const result=await db.batch([db.prepare("UPDATE qr_print_jobs SET answer=?,confirmed_at=? WHERE id=? AND created_by=? AND answer='pending'").bind(d.answer,new Date().toISOString(),d.jobId,actor!.id),db.prepare("UPDATE qr_print_items SET printed=1 WHERE job_id=? AND EXISTS(SELECT 1 FROM qr_print_jobs WHERE id=? AND answer='yes')").bind(d.jobId,d.jobId)]);if(!result[0].meta.changes)return Response.json({error:'Diese Druckansicht wurde bereits bestätigt.'},{status:409});return Response.json({answer:d.answer})}
 if(d.action!=='prepare'||!['single','bulk'].includes(d.kind)||!Array.isArray(d.entryIds)||!d.entryIds.length||d.entryIds.length>5000||d.kind==='single'&&d.entryIds.length!==1||d.entryIds.some((id:any)=>typeof id!=='string'||!/^[a-f0-9-]{36}$/.test(id)))return Response.json({error:'Bitte 1 bis 5000 Beiträge auswählen.'},{status:400});await authorize(req,d.kind);
 const origin=await qrOrigin(req);const labels=[];for(const id of [...new Set<string>(d.entryIds)]){const row=await db.prepare('SELECT data,publication_status FROM entries WHERE id=? AND deleted=0').bind(id).first<any>();if(!row)return Response.json({error:'Ein ausgewählter Beitrag ist nicht mehr vorhanden.'},{status:409});const reference=await ensureReference(id);labels.push({entryId:id,reference,title:JSON.parse(row.data).title,url:origin+entryReferencePath(reference)+'?quelle=qr',published:row.publication_status==='approved'})}
 const jobId=crypto.randomUUID(),now=new Date().toISOString();await db.prepare('INSERT INTO qr_print_jobs(id,kind,labels,created,created_by) VALUES(?,?,?,?,?)').bind(jobId,d.kind,JSON.stringify(labels),now,actor!.id).run();try{for(let at=0;at<labels.length;at+=50)await db.batch(labels.slice(at,at+50).map(label=>db.prepare('INSERT INTO qr_print_items(id,job_id,entry_id,url,created) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),jobId,label.entryId,label.url,now)))}catch(e){await db.batch([db.prepare('DELETE FROM qr_print_items WHERE job_id=?').bind(jobId),db.prepare('DELETE FROM qr_print_jobs WHERE id=?').bind(jobId)]);throw e}return Response.json({jobId,labels},{status:201});
 }catch(e){console.error(e);return accessResponse(e)||Response.json({error:'Die Druckansicht konnte nicht gespeichert werden. Bitte erneut versuchen.'},{status:503})}}
