import {requireArchiveAction,accessResponse,archiveAccess} from '@/lib/archive-access';
import {publicFileAllowed} from '@/lib/archive-public';
import {env} from 'cloudflare:workers';
import {authenticatedIdentity} from '@/lib/archive-identity';
const bucket=()=> (env as unknown as {BUCKET:R2Bucket}).BUCKET;
const types:Record<string,string>={mp3:'audio/mpeg',wav:'audio/wav',m4a:'audio/mp4',mp4:'audio/mp4',aac:'audio/aac',ogg:'audio/ogg',oga:'audio/ogg',webm:'audio/webm',flac:'audio/flac'};
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});await requireArchiveAction(req,'edit');if(!authenticatedIdentity(req))return Response.json({error:'Bitte zum Hochladen anmelden. Öffnen Sie die Website direkt im Browser.'},{status:401});const f=(await req.formData()).get('file');if(!(f instanceof File)||!f.size)return Response.json({error:'Bitte eine Datei auswählen.'},{status:400});const ext=f.name.split('.').pop()?.toLowerCase()||'';const audio=types[ext];const type=audio||f.type;if(audio&&f.size>50*1024*1024||!audio&&(f.size>10*1024*1024||!['image/jpeg','image/png','image/webp','application/pdf'].includes(type)))return Response.json({error:'Bitte eine Audiodatei bis 50 MB oder JPG, PNG, WebP bzw. PDF bis 10 MB wählen.'},{status:400});const key=crypto.randomUUID();await bucket().put(key,f.stream(),{httpMetadata:{contentType:type},customMetadata:{name:f.name}});return Response.json({key,name:f.name,type});}catch(e){const denied=accessResponse(e);if(denied)return denied;console.error(e);return Response.json({error:'Datei konnte nicht gespeichert werden.'},{status:503})}}
export async function GET(req:Request){try{const u=new URL(req.url),key=u.searchParams.get('key');if(!key||! /^[a-f0-9-]{36}$/.test(key))return new Response(null,{status:400});const access=await archiveAccess(req);if(new URL(req.url).searchParams.has('public')||access?.role==='public'){if(!await publicFileAllowed(key))return new Response('Diese Datei ist nicht öffentlich freigegeben.',{status:403})}else if(!access)return new Response('Bitte anmelden.',{status:401});const head=await bucket().head(key);if(!head)return new Response(null,{status:404});if(u.searchParams.has('download')&&(u.searchParams.has('public')||!access||access.role==='public')&&(head.httpMetadata?.contentType?.startsWith('audio/')||/\.(mp3|wav|m4a|mp4|aac|ogg|oga|webm|flac)$/i.test(head.customMetadata?.name||'')))return new Response('Audio-Downloads sind nur für angemeldete Nutzer, Verwalter und Administratoren verfügbar.',{status:403});const headers:Record<string,string>={'Content-Type':head.httpMetadata?.contentType||'application/octet-stream','X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store','Accept-Ranges':'bytes'};if(u.searchParams.has('download'))headers['Content-Disposition']="attachment; filename*=UTF-8''"+encodeURIComponent((head.customMetadata?.name||'Datei').replace(/[\r\n]/g,''));const range=req.headers.get('range');let start=0,end=head.size-1;if(range){const m=/^bytes=(\d*)-(\d*)$/.exec(range);if(!m||!m[1]&&!m[2])return new Response(null,{status:416,headers:{'Content-Range':`bytes */${head.size}`}});if(!m[1])start=Math.max(0,head.size-Number(m[2]));else{start=Number(m[1]);if(m[2])end=Math.min(end,Number(m[2]))}if(start>end||start>=head.size)return new Response(null,{status:416,headers:{'Content-Range':`bytes */${head.size}`}});headers['Content-Range']=`bytes ${start}-${end}/${head.size}`}
const f=await bucket().get(key,range?{range:{offset:start,length:end-start+1}}:{});if(!f)return new Response(null,{status:404});headers['Content-Length']=String(end-start+1);return new Response(f.body,{status:range?206:200,headers});}catch(e){const denied=accessResponse(e);if(denied)return denied;console.error(e);return new Response('Datei nicht erreichbar',{status:503})}}
