import {guestFields,projectGuestEntry} from '@/lib/archive-guest';
import {archiveRequestOrigin} from '@/lib/archive-request-origin';
import {validPersonTags,withPersonTags,peopleIndex,personNameKey} from '@/lib/archive-people';
import {validDescriptionLinks} from '@/lib/archive-description-links';
import {ensureReference,entryMetadata,randomReference} from '@/lib/archive-references';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import { archiveDb } from '@/lib/archive-db';
import {resolveArchiveActor} from '@/lib/archive-identity';
const uuid=(s:any)=>typeof s==='string'&&/^[a-f0-9-]{36}$/.test(s);
const fields=['title','category','period','start','end','place','description','sources','interpretation','uncertainty','rights','tags','status'];
function origin(req:Request){return !req.headers.get('origin')||req.headers.get('origin')===archiveRequestOrigin(req)}
export async function GET(req:Request){try{const access=await requireArchiveAction(req,'readEntries');const u=new URL(req.url), id=u.searchParams.get('history');const db=archiveDb();if(access.role==='guest'){if(id||u.searchParams.get('deleted')==='1')return Response.json({error:'Versionen und gelöschte Einträge sind für Gäste nicht verfügbar.'},{status:403});const selected=await guestFields();const rows=await db.prepare("SELECT e.data,r.reference,p.name AS storagePlace FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id LEFT JOIN storage_places p ON p.id=json_extract(e.data,'$.storagePlaceId') WHERE e.deleted=0 ORDER BY e.updated DESC").all();return Response.json(rows.results.map((r:any)=>projectGuestEntry(JSON.parse(r.data),selected,r.reference||'',r.storagePlace||'')),{headers:{'Cache-Control':'no-store'}})}if(id){if(!uuid(id))return Response.json({error:'Ungültiger Eintrag.'},{status:400});const r=await db.prepare('SELECT version,data,created,action,actor_id AS actorId,actor_name AS actorName FROM entry_versions WHERE entry_id=? ORDER BY version DESC').bind(id).all();return Response.json(r.results.map((x:any)=>({...x,data:JSON.parse(x.data)})),{headers:{'Cache-Control':'no-store'}})}const missing=await db.prepare('SELECT e.id FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id WHERE r.entry_id IS NULL AND e.deleted=0').all();for(let offset=0;offset<missing.results.length;offset+=50){await db.batch(missing.results.slice(offset,offset+50).map(row=>db.prepare('INSERT OR IGNORE INTO entry_references(entry_id,reference,created) VALUES(?,?,?)').bind(row.id,randomReference(),new Date().toISOString())))}const r=await db.prepare("SELECT e.data,r.reference,EXISTS(SELECT 1 FROM qr_print_items WHERE entry_id=e.id) AS qrGenerated,EXISTS(SELECT 1 FROM qr_print_items WHERE entry_id=e.id AND printed=1) AS qrPrinted,(SELECT url FROM qr_print_items WHERE entry_id=e.id AND printed=1 ORDER BY created DESC,id DESC LIMIT 1) AS qrPrintedUrl,(SELECT json_group_array(DISTINCT url) FROM qr_print_items WHERE entry_id=e.id AND printed=1) AS qrPrintedUrls FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id WHERE e.deleted=? ORDER BY e.updated DESC").bind(u.searchParams.get('deleted')==='1'?1:0).all();return Response.json(await Promise.all(r.results.map(async (x:any)=>({...withPersonTags(JSON.parse(x.data)),reference:x.reference||await ensureReference(JSON.parse(x.data).id),qrGenerated:!!x.qrGenerated,qrPrinted:!!x.qrPrinted,qrPrintedUrl:x.qrPrintedUrl,qrPrintedUrls:JSON.parse(x.qrPrintedUrls||'[]')}))),{headers:{'Cache-Control':'no-store'}})}catch(e){const denied=accessResponse(e);if(denied)return denied;console.error(e);return Response.json({error:'Der Bestand ist gerade nicht erreichbar. Bitte erneut versuchen.'},{status:503})}}
export async function POST(req:Request){try{if(!origin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});const access=await requireArchiveAction(req,'edit');const actor=await resolveArchiveActor(req);if(!actor)return Response.json({error:'Bitte zum Speichern anmelden. Öffnen Sie die Website direkt im Browser.'},{status:401});let input=await req.json() as any;if(input.category==='Person / Familie')input=withPersonTags(input);const d:any={};for(const key of fields)d[key]=typeof input[key]==='string'?input[key]:'';
if(!d.title.trim()||d.title.length>250||!['Ereignis','Ort / Gebäude','Thema','Bild / Dokument','Artefakt'].includes(d.category)||!['Offen','In Bearbeitung','Quellengeprüft','Unsicher'].includes(d.status)||JSON.stringify(input).length>200000)return Response.json({error:'Bitte Titel, Bereich und Forschungsstatus prüfen.'},{status:400});
if(d.start&&!/^-?\d{1,4}$/.test(d.start)||d.end&&!/^-?\d{1,4}$/.test(d.end)||d.start&&d.end&&Number(d.start)>Number(d.end))return Response.json({error:'Bitte einen gültigen Zeitraum eingeben.'},{status:400});
if(d.status==='Quellengeprüft'&&!d.sources.trim())return Response.json({error:'Für quellengeprüfte Einträge ist ein Beleg erforderlich.'},{status:400});
if(!Array.isArray(input.files)||input.files.length>100||input.files.some((f:any)=>!uuid(f.key)||typeof f.name!=='string'||typeof f.type!=='string'))return Response.json({error:'Bitte die Dateizuordnungen prüfen.'},{status:400});d.files=input.files.map((f:any)=>({key:f.key,name:f.name,type:f.type}));d.id=uuid(input.id)?input.id:crypto.randomUUID();d.updated=new Date().toISOString()+'-'+crypto.randomUUID();const db=archiveDb();const expected=typeof input.updated==='string'?input.updated:'';
if(access.role!=='admin'&&(await db.prepare('SELECT deleted FROM entries WHERE id=?').bind(d.id).first<{deleted:number}>())?.deleted)return Response.json({error:'Nur ein Admin kann gelöschte Einträge wiederherstellen.'},{status:403});
const personTags=input.personTags??[];if(!validPersonTags(personTags,d.description))return Response.json({error:'Bitte die Personen- und Familienzuordnungen prüfen.'},{status:400});const otherEntries=await db.prepare('SELECT data FROM entries WHERE deleted=0').all();const knownPeople=peopleIndex(otherEntries.results.map((r:any)=>JSON.parse(r.data)));d.personTags=personTags.map(t=>{const known=knownPeople.find(p=>p.entityId===t.entityId)||knownPeople.find(p=>p.kind===t.kind&&personNameKey(p.name)===personNameKey(t.name));return {...t,name:known?.name||t.name.trim(),kind:known?.kind||t.kind,entityId:known?.entityId||t.entityId}});
const descriptionLinks=input.descriptionLinks??[];if(!validDescriptionLinks(descriptionLinks,d.description))return Response.json({error:'Bitte die Verknüpfungen in der Beschreibung prüfen.'},{status:400});if(descriptionLinks.length){const refs=await db.prepare('SELECT reference FROM entry_references WHERE reference IN (SELECT value FROM json_each(?))').bind(JSON.stringify(descriptionLinks.map(l=>l.reference))).all();const known=new Set(refs.results.map(r=>r.reference));if(descriptionLinks.some(l=>!known.has(l.reference)))return Response.json({error:'Ein verknüpfter Beitrag wurde nicht gefunden. Bitte das Linkziel prüfen.'},{status:400})}d.descriptionLinks=descriptionLinks.map(({start,end,reference})=>({start,end,reference}));
d.storagePlaceId=input.storagePlaceId??'';if(typeof d.storagePlaceId!=='string'||d.storagePlaceId&&(!uuid(d.storagePlaceId)||!await db.prepare('SELECT id FROM storage_places WHERE id=?').bind(d.storagePlaceId).first()))return Response.json({error:'Der Aufbewahrungsort ist nicht mehr verfügbar. Bitte einen vorhandenen Ort wählen oder die Zuordnung entfernen.'},{status:400});
const r=await db.batch([
 db.prepare("INSERT INTO entry_versions(entry_id,data,created,action) SELECT id,data,substr(updated,1,24),'Ausgangsstand' FROM entries WHERE id=? AND updated=? AND NOT EXISTS(SELECT 1 FROM entry_versions WHERE entry_id=?)").bind(d.id,expected,d.id),
 db.prepare("INSERT INTO entries(id,data,updated,deleted,created_by,updated_by,timeline_visible) VALUES(?,?,?,0,?,?,0) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated,deleted=0,updated_by=excluded.updated_by,publication_status='draft',approved_version=NULL,approved_by=NULL,approved_at=NULL,requested_version=NULL,requested_by=NULL,requested_at=NULL,review_token=NULL WHERE entries.updated=?").bind(d.id,JSON.stringify(d),d.updated,actor.id,actor.id,expected),
 db.prepare("INSERT INTO entry_versions(entry_id,data,created,action,actor_id,actor_name) SELECT id,data,?,'Gespeichert',?,? FROM entries WHERE id=? AND updated=?").bind(new Date().toISOString(),actor.id,actor.name,d.id,d.updated)
]);if(!r[1].meta.changes)return Response.json({error:'Der Eintrag wurde inzwischen geändert. Bitte den aktuellen Eintrag neu öffnen; Ihren Entwurf können Sie herunterladen.'},{status:409});await ensureReference(d.id);return Response.json({...d,...await entryMetadata(d.id)});
}catch(e){const denied=accessResponse(e);if(denied)return denied;console.error(e);return Response.json({error:'Speichern fehlgeschlagen. Ihre Eingaben bleiben erhalten.'},{status:503})}}
export async function DELETE(req:Request){try{if(!origin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});await requireArchiveAction(req,'delete');const actor=await resolveArchiveActor(req);if(!actor)return Response.json({error:'Bitte zum Löschen anmelden. Öffnen Sie die Website direkt im Browser.'},{status:401});const {id,updated}=await req.json() as any;if(!uuid(id)||typeof updated!=='string')return Response.json({error:'Ungültiger Eintrag.'},{status:400});const db=archiveDb();const deletedUpdated=new Date().toISOString()+'-'+crypto.randomUUID();const r=await db.batch([
 db.prepare("INSERT INTO entry_versions(entry_id,data,created,action,actor_id,actor_name) SELECT id,data,?,'Gelöscht',?,? FROM entries WHERE id=? AND updated=? AND deleted=0").bind(new Date().toISOString(),actor.id,actor.name,id,updated),
 db.prepare("UPDATE entries SET deleted=1,updated=?,data=json_set(data,'$.updated',?),updated_by=?,publication_status='draft',approved_version=NULL,approved_by=NULL,approved_at=NULL,requested_version=NULL,requested_by=NULL,requested_at=NULL,review_token=NULL WHERE id=? AND updated=? AND deleted=0").bind(deletedUpdated,deletedUpdated,actor.id,id,updated)
]);if(!r[1].meta.changes)return Response.json({error:'Der Eintrag wurde inzwischen geändert. Bitte neu laden.'},{status:409});return Response.json({id,deleted:true})}catch(e){const denied=accessResponse(e);if(denied)return denied;console.error(e);return Response.json({error:'Löschen fehlgeschlagen. Bitte erneut versuchen.'},{status:503})}}
