import {archiveDb} from '@/lib/archive-db';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import {sameOrigin} from '@/lib/archive-comments';
import {rotationPlan} from '@/lib/archive-timeline-rotation';
import {validRotationFilters,validFirstLocal,localToUtc,nextRotation} from '@/lib/archive-timeline-rotation-rules';
export async function GET(req:Request){try{await requireArchiveAction(req,'manageTimeline');return Response.json(await rotationPlan(),{headers:{'Cache-Control':'no-store'}})}catch(e){return accessResponse(e)||Response.json({error:'Planung konnte nicht geladen werden.'},{status:503})}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});await requireArchiveAction(req,'manageTimeline');const d=await req.json() as any,old=await rotationPlan();if(typeof d.baseRevision!=='string'||d.baseRevision!==old.revision)return Response.json({error:'Die Planung wurde inzwischen geändert. Bitte neu laden.'},{status:409});const now=new Date(),revision=crypto.randomUUID();
 if(d.action==='pause'||d.action==='disable'){const r=await archiveDb().prepare("UPDATE timeline_rotation SET enabled=0,revision=?,updated=?,last_result=? WHERE id='main' AND revision=?").bind(revision,now.toISOString(),d.action==='disable'?'Planung ausgeschaltet.':'Planung pausiert.',old.revision).run();if(!r.meta.changes)return Response.json({error:'Planung wurde inzwischen geändert.'},{status:409});return Response.json(await rotationPlan())}
 if(d.action!=='save'||!validRotationFilters(d.filters)||!Number.isInteger(d.amount)||d.amount<1||d.amount>500000||!['weekly','monthly'].includes(d.cadence)||!validFirstLocal(d.firstLocal)||typeof d.enabled!=='boolean')return Response.json({error:'Bitte Filter, Anzahl und Termin prüfen. Uhrzeiten sind in vollen Stunden anzugeben.'},{status:400});
 const first=localToUtc(d.firstLocal);const nextRun=first>now.toISOString()?first:nextRotation(d.firstLocal,d.cadence,now);
 const r=await archiveDb().prepare("UPDATE timeline_rotation SET revision=?,enabled=?,filters=?,amount=?,cadence=?,first_local=?,next_run=?,updated=?,last_result=? WHERE id='main' AND revision=?").bind(revision,d.enabled?1:0,JSON.stringify(d.filters),d.amount,d.cadence,d.firstLocal,nextRun,now.toISOString(),d.enabled?'Planung aktiviert.':'Planung gespeichert und pausiert.',old.revision).run();if(!r.meta.changes)return Response.json({error:'Planung wurde inzwischen geändert.'},{status:409});return Response.json(await rotationPlan());
 }catch(e){console.error(e);return accessResponse(e)||Response.json({error:'Die Planung konnte nicht gespeichert werden.'},{status:503})}}
