import {sendArchiveMail,mailAvailable} from '@/lib/archive-mail';
import {domainConfirmation,normalizeHostingDomain,checkHostingDomain} from '@/lib/archive-qr-domain';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import {archiveDb} from '@/lib/archive-db';
import {systemSettings,sanitizedSettings,sealSecret,testWebdav,webdavBase} from '@/lib/archive-system-settings';
import {sameOrigin} from '@/lib/archive-comments';
export async function GET(req:Request){try{await requireArchiveAction(req,'manageSettings');return Response.json(sanitizedSettings(await systemSettings()),{headers:{'Cache-Control':'no-store'}})}catch(e){return accessResponse(e)||Response.json({error:'Einstellungen konnten nicht geladen werden.'},{status:503})}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});const access=await requireArchiveAction(req,'manageSettings'),d=await req.json() as any,old=await systemSettings();if(d.action==='domain-test')return Response.json(await checkHostingDomain(d.domain));if(d.action==='domain-save'){if(d.confirmation!==domainConfirmation)return Response.json({error:'Bitte den Bestätigungstext exakt abtippen.'},{status:400});if(d.expectedDomain!==old.domain)return Response.json({error:'Die Domain wurde inzwischen geändert. Bitte neu laden.'},{status:409});const domain=normalizeHostingDomain(d.domain),check=await checkHostingDomain(domain);if(!check.reachable&&d.allowUnreachable!==true)return Response.json({warning:true,check});const next={...old,domain};const result=await archiveDb().prepare("INSERT INTO archive_settings(key,data,updated,updated_by) VALUES('system_settings',?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated=excluded.updated,updated_by=excluded.updated_by WHERE archive_settings.data=?").bind(JSON.stringify(next),new Date().toISOString(),access.identity.subject,JSON.stringify(old)).run();if(!result.meta.changes)return Response.json({error:'Einstellungen wurden inzwischen geändert. Bitte neu laden.'},{status:409});return Response.json({domain,check})}if(d.action==='smtp-test'){if(!mailAvailable())return Response.json({available:false,message:'SMTP ist in Sites nicht verfügbar. Der echte Testmail-Versand läuft auf dem eigenen Linux-Server.'});if(typeof d.to!=='string'||d.to.length>250||!/^\S+@[^\s@]+\.[^\s@]+$/.test(d.to))throw Error('Bitte eine gültige Zieladresse für die Testmail angeben.');await sendArchiveMail(d.to,'Geschichtsarchiv: SMTP-Verbindung geprüft','Diese Testmail wurde aus Ihrem Geschichtsarchiv versendet. Der SMTP-Server hat die Nachricht angenommen. Bitte prüfen Sie auch den Spamordner.');return Response.json({available:true,message:'SMTP-Server hat die Testmail angenommen. Bitte Posteingang und Spamordner prüfen.'})}if(d.action==='webdav-test'){const tested=await testWebdav(old.webdav);old.webdav.tested=tested;await archiveDb().prepare("INSERT INTO archive_settings(key,data,updated,updated_by) VALUES('system_settings',?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated=excluded.updated,updated_by=excluded.updated_by").bind(JSON.stringify(old),new Date().toISOString(),access.identity.subject).run();return Response.json({tested,message:'WebDAV erfolgreich geprüft: Testdatei geschrieben, gelesen und entfernt.'})}
 if(d.action!=='save'||!d.settings||JSON.stringify(d.settings).length>16000)return Response.json({error:'Ungültige Einstellungen.'},{status:400});const s=d.settings;if(s.domain!==old.domain)return Response.json({error:'Die Hosting-Domain muss separat mit dem Bestätigungstext geändert werden. Bitte neu laden.'},{status:409});const w=s.webdav,m=s.smtp,i=s.invitations;
 if(!w||!m||!i||typeof s.domain!=='string'||s.domain.length>250||typeof w.url!=='string'||w.url.length>1000||typeof w.folder!=='string'||typeof w.username!=='string'||w.username.length>250||typeof w.password!=='string'||w.password.length>2000||typeof w.daily!=='boolean'||!Number.isInteger(w.hour)||w.hour<0||w.hour>23||!Number.isInteger(w.retention)||w.retention<1||w.retention>365||typeof m.host!=='string'||m.host.length>250||!Number.isInteger(m.port)||m.port<1||m.port>65535||!['starttls','tls'].includes(m.tls)||typeof m.username!=='string'||typeof m.password!=='string'||m.password.length>2000||typeof m.from!=='string'||m.from.length>250||typeof m.sender!=='string'||m.sender.length>250||!Number.isInteger(i.expiryDays)||i.expiryDays<1||i.expiryDays>30||!['user','manager','admin'].includes(i.defaultRole))return Response.json({error:'Bitte alle Angaben prüfen.'},{status:400});if(s.domain){const u=new URL(s.domain);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Die künftige Domain muss eine HTTPS-Adresse ohne Pfad sein.')}if(w.url)webdavBase(w);if(m.from&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(m.from))throw Error('Bitte eine gültige Absenderadresse angeben.');const changed=['url','folder','username'].some(k=>w[k]!==old.webdav[k])||!!w.password;const next={domain:s.domain,webdav:{url:w.url,folder:w.folder,username:w.username,password:w.clearPassword?'':w.password?await sealSecret(w.password):old.webdav.password,daily:w.daily,hour:w.hour,retention:w.retention,tested:changed||w.clearPassword?null:old.webdav.tested},smtp:{host:m.host,port:m.port,tls:m.tls,username:m.username,password:m.clearPassword?'':m.password?await sealSecret(m.password):old.smtp.password,from:m.from,sender:m.sender},invitations:{expiryDays:i.expiryDays,defaultRole:i.defaultRole}};
 if(next.webdav.daily&&(!next.webdav.tested||!next.webdav.password))throw Error('Bitte zuerst WebDAV speichern und testen; danach die tägliche Sicherung aktivieren.');await archiveDb().prepare("INSERT INTO archive_settings(key,data,updated,updated_by) VALUES('system_settings',?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated=excluded.updated,updated_by=excluded.updated_by").bind(JSON.stringify(next),new Date().toISOString(),access.identity.subject).run();return Response.json(sanitizedSettings(next));
 }catch(e:any){return accessResponse(e)||Response.json({error:e.message||'Einstellungen konnten nicht gespeichert werden.'},{status:400})}}
