import {publicationRequestStatements} from '@/lib/archive-publication-request';
import {scanPush} from '@/lib/archive-push';
import {archiveRequestOrigin} from '@/lib/archive-request-origin';
import {archiveDb} from '@/lib/archive-db';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import {resolveArchiveActor} from '@/lib/archive-identity';
const currentVersion="(SELECT max(v.version) FROM entry_versions v WHERE v.entry_id=e.id AND v.action='Gespeichert' AND json_extract(v.data,'$.updated')=e.updated)";
export async function GET(req:Request){try{await requireArchiveAction(req);const id=new URL(req.url).searchParams.get('id');const rows=await archiveDb().prepare(`SELECT e.id,e.updated,e.data,e.publication_status AS status,e.timeline_visible AS timelineVisible,e.requested_version AS requestedVersion,e.requested_at AS requestedAt,u.display_name AS requestedBy,${currentVersion} AS currentVersion FROM entries e LEFT JOIN archive_users u ON u.id=e.requested_by WHERE e.deleted=0 ${id?'AND e.id=?':"AND e.publication_status='pending'"} ORDER BY e.requested_at DESC`).bind(...(id?[id]:[])).all();return Response.json(rows.results.map((r:any)=>({...r,data:JSON.parse(r.data)})),{headers:{'Cache-Control':'no-store'}})}catch(e){return accessResponse(e)||Response.json({error:'Veröffentlichungsanfragen konnten nicht geladen werden.'},{status:503})}}
export async function POST(req:Request){try{
 if(req.headers.get('origin')&&req.headers.get('origin')!==archiveRequestOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});
 const d=await req.json() as any;if(!['request','approve','reject','withdraw','cancel'].includes(d.action)||typeof d.id!=='string'||typeof d.updated!=='string'||!Number.isSafeInteger(d.version)||d.version<1)return Response.json({error:'Bitte einen gespeicherten Eintrag auswählen.'},{status:400});
 await requireArchiveAction(req,['request','withdraw','cancel'].includes(d.action)?'edit':'approve');const actor=await resolveArchiveActor(req),db=archiveDb(),token=crypto.randomUUID(),now=new Date().toISOString();
 const reviewArgs=d.reviewToken!==undefined&&['approve','reject'].includes(d.action)?[d.reviewToken]:[];if(reviewArgs.length&&typeof d.reviewToken!=='string')return Response.json({error:'Ungültige Anfrage.'},{status:400});
 const condition="id=? AND updated=? AND deleted=0 AND EXISTS(SELECT 1 FROM entry_versions v WHERE v.entry_id=entries.id AND v.version=? AND v.action='Gespeichert' AND json_extract(v.data,'$.updated')=entries.updated)"+(reviewArgs.length?" AND review_token=?":"");
 let statement:D1PreparedStatement;
 if(['withdraw','cancel'].includes(d.action))statement=db.prepare(`UPDATE entries SET publication_status='draft',approved_version=NULL,approved_by=NULL,approved_at=NULL,requested_version=NULL,requested_by=NULL,requested_at=NULL,review_token=? WHERE ${condition} AND publication_status=?`).bind(token,d.id,d.updated,d.version,d.action==='withdraw'?'approved':'pending');
 else statement=db.prepare(`UPDATE entries SET publication_status=?,approved_version=?,approved_by=?,approved_at=?,review_token=? WHERE ${condition} AND publication_status='pending' AND requested_version=?`).bind(d.action==='approve'?'approved':'rejected',d.action==='approve'?d.version:null,d.action==='approve'?actor!.id:null,d.action==='approve'?now:null,token,d.id,d.updated,d.version,...reviewArgs,d.version);
 const action=d.action==='withdraw'?'Veröffentlichung zurückgenommen':d.action==='cancel'?'Veröffentlichungsanfrage zurückgezogen':d.action==='request'?'Veröffentlichung angefragt':d.action==='approve'?'Veröffentlichung genehmigt':'Veröffentlichung abgelehnt';
 const r=await db.batch(d.action==='request'?publicationRequestStatements(db,{id:d.id,updated:d.updated,version:d.version,actor:actor!,token,now}):[statement,db.prepare('INSERT INTO entry_versions(entry_id,data,created,action,actor_id,actor_name) SELECT id,data,?,?,?,? FROM entries WHERE id=? AND review_token=?').bind(now,action,actor!.id,actor!.name,d.id,token),...(d.action==='approve'?[db.prepare("DELETE FROM qr_access_alerts WHERE entry_id=? AND EXISTS(SELECT 1 FROM entries WHERE id=? AND review_token=? AND publication_status='approved')").bind(d.id,d.id,token)]:[])]);
 if(!r[0].meta.changes)return Response.json({error:'Der Eintrag oder die Anfrage wurde inzwischen geändert. Bitte neu laden und die aktuelle Version prüfen.'},{status:409});return Response.json({id:d.id,status:['withdraw','cancel'].includes(d.action)?'draft':d.action==='request'?'pending':d.action==='approve'?'approved':'rejected'});
 }catch(e){const denied=accessResponse(e);if(denied)return denied;console.error(e);return Response.json({error:'Die Veröffentlichung konnte nicht geändert werden.'},{status:503})}finally{await scanPush()}}
