import {initializeAccountCodes,accountCode,renameAccount,deleteAccount} from './account-management.mjs';
import {welcomeNotice} from './welcome-notices.mjs';
import {guestSetupNotice} from './guest-setup-notice.mjs';
import {randomBytes,randomUUID,createHash,createHmac} from 'node:crypto';
import {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse} from '@simplewebauthn/server';
const digest=value=>createHash('sha256').update(value).digest('hex');
export function initializeAuth(db){db.exec(`CREATE TABLE IF NOT EXISTS linux_accounts(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,disabled INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS linux_credentials(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES linux_accounts(id),public_key TEXT NOT NULL,counter INTEGER NOT NULL,transports TEXT NOT NULL); CREATE TABLE IF NOT EXISTS linux_invites(hash TEXT PRIMARY KEY,email TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS linux_challenges(hash TEXT PRIMARY KEY,challenge TEXT NOT NULL,kind TEXT NOT NULL,invite TEXT,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS linux_credential_metadata(id TEXT PRIMARY KEY,name TEXT NOT NULL,created TEXT,last_used TEXT);
CREATE TABLE IF NOT EXISTS linux_login_metadata(account_id TEXT PRIMARY KEY,last_login TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS linux_account_security(account_id TEXT PRIMARY KEY,user_handle TEXT NOT NULL);`);initializeAccountCodes(db)}
export function authService(db,config){
 const origin=new URL(config.origin);if(origin.origin!==config.origin||origin.protocol!=='https:'&&!(origin.protocol==='http:'&&origin.hostname==='localhost'))throw Error('Anmeldung benötigt HTTPS oder http://localhost.');if(!/^[a-f0-9]{64}$/.test(config.sessionKey||''))throw Error('Sitzungsschlüssel fehlt.');initializeAuth(db);
 const rpID=origin.hostname,now=()=>Math.floor(Date.now()/1000);
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
 function invite(token){if(typeof token!=='string'||token.length>200)throw Error('Einladung ungültig oder abgelaufen.');const i=db.prepare('SELECT * FROM linux_invites WHERE hash=? AND used=0 AND expires>?').get(digest(token),now());if(!i)throw Error('Einladung ungültig oder abgelaufen.');return i;}
 function saveChallenge(kind,challenge,invitation=null){db.prepare('DELETE FROM linux_challenges WHERE expires<=?').run(now());if(db.prepare('SELECT count(*) AS n FROM linux_challenges').get().n>=1000)throw Error('Zu viele Anmeldeversuche. Bitte später erneut versuchen.');const token=randomBytes(32).toString('base64url');db.prepare('INSERT INTO linux_challenges VALUES(?,?,?,?,?)').run(digest(token),challenge,kind,invitation,now()+300);return token;}
 function consume(token,kind,actor=null){return transaction(()=>{const c=db.prepare('SELECT * FROM linux_challenges WHERE hash=? AND kind=? AND expires>?').get(digest(String(token)),kind,now());if(!c||actor&&c.invite!==actor)throw actionError('Bestätigung abgelaufen oder gehört zu einem anderen Konto. Bitte erneut bestätigen.');db.prepare('DELETE FROM linux_challenges WHERE hash=?').run(c.hash);return c})}
 function session(account){const t=now(),p=Buffer.from(JSON.stringify({issuer:'archive-linux-session-v1',subject:account.id,email:account.email,name:account.name,iat:t,exp:t+43200})).toString('base64url');return p+'.'+createHmac('sha256',config.sessionKey).update(p).digest('base64url')}
 function actionError(message){return Object.assign(Error(message),{publicMessage:message})}
 function accountFor(actor){const a=db.prepare('SELECT * FROM linux_accounts WHERE id=? AND disabled=0').get(actor);if(!a)throw actionError('Konto nicht verfügbar.');return a;}
 function keyName(name){if(typeof name!=='string'||!name.trim()||name.length>80||/[\x00-\x1f]/.test(name))throw actionError('Bitte einen Passkey-Namen mit 1 bis 80 Zeichen angeben.');return name.trim()}
 function keysFor(actor){return db.prepare("SELECT c.id,COALESCE(m.name,'Passkey') AS name,m.created,m.last_used AS lastUsed FROM linux_credentials c LEFT JOIN linux_credential_metadata m ON m.id=c.id WHERE c.account_id=? ORDER BY m.created,c.id").all(actor)}
 function touchLogin(actor){db.prepare('INSERT INTO linux_login_metadata VALUES(?,?) ON CONFLICT(account_id) DO UPDATE SET last_login=excluded.last_login').run(actor,new Date().toISOString())}
 function touchKey(id){db.prepare("INSERT INTO linux_credential_metadata(id,name,created,last_used) VALUES(?,'Passkey',NULL,?) ON CONFLICT(id) DO UPDATE SET last_used=excluded.last_used").run(id,new Date().toISOString())}
 async function verifyOwned(actor,challenge,response){const k=db.prepare('SELECT * FROM linux_credentials WHERE id=? AND account_id=?').get(response?.id,actor);if(!k)throw actionError('Bitte einen vorhandenen Passkey dieses Kontos verwenden.');const v=await verifyAuthenticationResponse({response,expectedChallenge:challenge,expectedOrigin:config.origin,expectedRPID:rpID,credential:{id:k.id,publicKey:new Uint8Array(Buffer.from(k.public_key,'base64url')),counter:k.counter,transports:JSON.parse(k.transports)},requireUserVerification:true});if(!v.verified)throw actionError('Passkey konnte nicht bestätigt werden.');transaction(()=>{if(!db.prepare('UPDATE linux_credentials SET counter=? WHERE id=? AND account_id=? AND counter=?').run(v.authenticationInfo.newCounter,k.id,actor,k.counter).changes)throw actionError('Parallel erfolgte Anmeldung. Bitte erneut bestätigen.');touchKey(k.id)});}
 return {
  invite({email,name,role},bootstrap=false){email=String(email||'').trim().toLowerCase();name=String(name||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>250||!name||name.length>200||!['admin','manager','user','guest'].includes(role))throw Error('Name, E-Mail und gültige Rolle erforderlich.');return transaction(()=>{if(bootstrap&&db.prepare('SELECT id FROM linux_accounts LIMIT 1').get())throw Error('Erster Administrator ist bereits angelegt.');if(db.prepare('SELECT id FROM linux_accounts WHERE email=?').get(email))throw Error('Für diese E-Mail existiert bereits ein Konto.');if(bootstrap)db.prepare("DELETE FROM linux_invites WHERE role='admin' AND used=0").run();const token=randomBytes(32).toString('base64url');db.prepare('INSERT INTO linux_invites VALUES(?,?,?,?,?,0)').run(digest(token),email,name,role,now()+(bootstrap?7:Math.min(30,Math.max(1,Number(config.inviteDays)||7)))*86400);if(role==='guest')guestSetupNotice(db,config.guestFieldLabels);return token})},
  async registrationOptions(token){const i=invite(token),options=await generateRegistrationOptions({rpName:'Digitales Geschichtsarchiv',rpID,userName:i.email,userDisplayName:i.name,userID:Buffer.from(i.hash,'hex'),attestationType:'none',authenticatorSelection:{residentKey:'required',userVerification:'required'}});return {options,challenge:saveChallenge('register',options.challenge,i.hash)}} ,
  async register(token,response,userAgent=''){const c=consume(token,'register'),i=db.prepare('SELECT * FROM linux_invites WHERE hash=? AND used=0 AND expires>?').get(c.invite,now());if(!i)throw Error('Einladung nicht mehr gültig.');const v=await verifyRegistrationResponse({response,expectedChallenge:c.challenge,expectedOrigin:config.origin,expectedRPID:rpID,requireUserVerification:true});if(!v.verified||!v.registrationInfo)throw Error('Passkey konnte nicht verifiziert werden.');const k=v.registrationInfo.credential,account={id:randomUUID(),email:i.email,name:i.name};transaction(()=>{const result=db.prepare('UPDATE linux_invites SET used=1 WHERE hash=? AND used=0 AND expires>?').run(i.hash,now());if(!result.changes)throw Error('Einladung bereits verwendet.');db.prepare('INSERT INTO linux_accounts(id,email,name) VALUES(?,?,?)').run(account.id,account.email,account.name);db.prepare('INSERT INTO linux_credentials VALUES(?,?,?,?,?)').run(k.id,account.id,Buffer.from(k.publicKey).toString('base64url'),k.counter,JSON.stringify(k.transports||[]));db.prepare('INSERT INTO linux_account_security VALUES(?,?)').run(account.id,Buffer.from(i.hash,'hex').toString('base64url'));db.prepare('INSERT INTO linux_credential_metadata VALUES(?,?,?,NULL)').run(k.id,'Erster Passkey',new Date().toISOString());db.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').run(account.id,'linux',account.id,account.name,new Date().toISOString(),i.role);touchLogin(account.id);welcomeNotice(db,account,i.role,userAgent);if(i.role==='guest')guestSetupNotice(db,config.guestFieldLabels)});return session(account)},
  async loginOptions(){const options=await generateAuthenticationOptions({rpID,userVerification:'required'});return {options,challenge:saveChallenge('login',options.challenge)}},
  async login(token,response){const c=consume(token,'login'),k=db.prepare('SELECT * FROM linux_credentials WHERE id=?').get(response.id);if(!k)throw Error('Anmeldung fehlgeschlagen.');const account=db.prepare('SELECT * FROM linux_accounts WHERE id=? AND disabled=0').get(k.account_id);if(!account)throw Error('Anmeldung fehlgeschlagen.');const v=await verifyAuthenticationResponse({response,expectedChallenge:c.challenge,expectedOrigin:config.origin,expectedRPID:rpID,credential:{id:k.id,publicKey:new Uint8Array(Buffer.from(k.public_key,'base64url')),counter:k.counter,transports:JSON.parse(k.transports)},requireUserVerification:true});if(!v.verified)throw Error('Anmeldung fehlgeschlagen.');const result=db.prepare('UPDATE linux_credentials SET counter=? WHERE id=? AND counter=?').run(v.authenticationInfo.newCounter,k.id,k.counter);if(!result.changes)throw Error('Parallel erfolgte Anmeldung. Bitte erneut anmelden.');touchKey(k.id);touchLogin(account.id);return session(account)},
  passkeys(actor){accountFor(actor);return keysFor(actor)},
  async passkeyAuthOptions(actor){accountFor(actor);const credentials=db.prepare('SELECT id,transports FROM linux_credentials WHERE account_id=?').all(actor);if(!credentials.length)throw actionError('Kein vorhandener Passkey verfügbar.');const options=await generateAuthenticationOptions({rpID,userVerification:'required',allowCredentials:credentials.map(k=>({id:k.id,transports:JSON.parse(k.transports)}))});return {options,challenge:saveChallenge('manage-auth',options.challenge,actor)}},
  async passkeyAuthVerify(actor,token,response){accountFor(actor);const c=consume(token,'manage-auth',actor);await verifyOwned(actor,c.challenge,response);return {proof:saveChallenge('manage-proof','',actor)}},
  async passkeyAddOptions(actor,proof){const a=accountFor(actor);consume(proof,'manage-proof',actor);if(keysFor(actor).length>=20)throw actionError('Pro Konto sind höchstens 20 Passkeys möglich.');let handle=db.prepare('SELECT user_handle FROM linux_account_security WHERE account_id=?').get(actor)?.user_handle;if(!handle){handle=Buffer.from(actor).toString('base64url');db.prepare('INSERT OR IGNORE INTO linux_account_security VALUES(?,?)').run(actor,handle)}const credentials=db.prepare('SELECT id,transports FROM linux_credentials WHERE account_id=?').all(actor);const options=await generateRegistrationOptions({rpName:'Digitales Geschichtsarchiv',rpID,userName:a.email,userDisplayName:a.name,userID:Buffer.from(handle,'base64url'),attestationType:'none',excludeCredentials:credentials.map(k=>({id:k.id,transports:JSON.parse(k.transports)})),authenticatorSelection:{residentKey:'required',userVerification:'required'}});return {options,challenge:saveChallenge('add-key',options.challenge,actor)}},
  async passkeyAdd(actor,token,response,name){accountFor(actor);name=keyName(name);const c=consume(token,'add-key',actor),v=await verifyRegistrationResponse({response,expectedChallenge:c.challenge,expectedOrigin:config.origin,expectedRPID:rpID,requireUserVerification:true});if(!v.verified||!v.registrationInfo)throw actionError('Neuer Passkey konnte nicht geprüft werden.');const k=v.registrationInfo.credential;transaction(()=>{accountFor(actor);if(keysFor(actor).length>=20)throw actionError('Pro Konto sind höchstens 20 Passkeys möglich.');db.prepare('INSERT INTO linux_credentials VALUES(?,?,?,?,?)').run(k.id,actor,Buffer.from(k.publicKey).toString('base64url'),k.counter,JSON.stringify(k.transports||[]));db.prepare('INSERT INTO linux_credential_metadata VALUES(?,?,?,NULL)').run(k.id,name,new Date().toISOString())});return keysFor(actor)},
  passkeyRename(actor,id,name){accountFor(actor);name=keyName(name);if(!db.prepare('SELECT id FROM linux_credentials WHERE id=? AND account_id=?').get(id,actor))throw actionError('Passkey nicht gefunden.');db.prepare('INSERT INTO linux_credential_metadata(id,name,created,last_used) VALUES(?,?,NULL,NULL) ON CONFLICT(id) DO UPDATE SET name=excluded.name').run(id,name);return keysFor(actor)},
  passkeyRemove(actor,id,proof){accountFor(actor);consume(proof,'manage-proof',actor);transaction(()=>{if(!db.prepare('SELECT id FROM linux_credentials WHERE id=? AND account_id=?').get(id,actor))throw actionError('Passkey nicht gefunden.');if(keysFor(actor).length<=1)throw actionError('Der letzte Passkey kann nicht entfernt werden. Bitte zuerst einen weiteren hinzufügen.');db.prepare('DELETE FROM linux_credentials WHERE id=? AND account_id=?').run(id,actor);db.prepare('DELETE FROM linux_credential_metadata WHERE id=?').run(id)});return keysFor(actor)},
  pending(){return db.prepare('SELECT hash,email,name,role,expires FROM linux_invites WHERE used=0 AND expires>? ORDER BY expires').all(now())},
  revoke(hash){db.prepare('DELETE FROM linux_invites WHERE hash=? AND used=0').run(hash)},
  accounts(){return db.prepare("SELECT a.id,a.email,a.name,a.disabled,u.role,(SELECT last_login FROM linux_login_metadata m WHERE m.account_id=a.id) AS lastLogin,(SELECT count(*) FROM linux_credentials c WHERE c.account_id=a.id) AS passkeyCount FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id AND NOT EXISTS(SELECT 1 FROM archive_settings s WHERE s.key='deleted-account:'||a.id) ORDER BY a.name").all().map(a=>({...a,code:accountCode(db,a.id)}))},
  rename(id,name,actor){return transaction(()=>renameAccount(db,id,name,actor))},
  delete(id,actor,confirmation){return transaction(()=>deleteAccount(db,id,actor,confirmation))},
  edit(id,role,disabled,actor){if(!['admin','manager','user','guest'].includes(role)||typeof disabled!=='boolean'||id===actor)throw Error('Das eigene Konto kann hier nicht geändert werden.');transaction(()=>{if(db.prepare('SELECT 1 FROM archive_settings WHERE key=?').get('deleted-account:'+id)||!db.prepare('SELECT id FROM linux_accounts WHERE id=?').get(id))throw Error('Konto nicht gefunden.');db.prepare('UPDATE linux_accounts SET disabled=? WHERE id=?').run(Number(disabled),id);db.prepare("UPDATE archive_users SET role=? WHERE identity_provider='linux' AND identity_subject=?").run(role,id);if(role==='guest'){if(db.prepare("SELECT 1 FROM sqlite_schema WHERE name='linux_push_queue'").get()){db.prepare("DELETE FROM linux_push_queue WHERE topic<>'message' AND subscription_id IN(SELECT id FROM linux_push_subscriptions WHERE account_id=?)").run(id);db.prepare("UPDATE linux_push_preferences SET data=json_object('message',json(CASE WHEN json_extract(data,'$.message')=0 THEN 'false' ELSE 'true' END)) WHERE account_id=?").run(id)}guestSetupNotice(db,config.guestFieldLabels)}})}
 };
}
