import {randomBytes,randomUUID,createHash,createHmac} from 'node:crypto';
import {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse} from '@simplewebauthn/server';
const digest=value=>createHash('sha256').update(value).digest('hex');
export function initializeAuth(db){db.exec(`CREATE TABLE IF NOT EXISTS linux_accounts(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,disabled INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS linux_credentials(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES linux_accounts(id),public_key TEXT NOT NULL,counter INTEGER NOT NULL,transports TEXT NOT NULL); CREATE TABLE IF NOT EXISTS linux_invites(hash TEXT PRIMARY KEY,email TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS linux_challenges(hash TEXT PRIMARY KEY,challenge TEXT NOT NULL,kind TEXT NOT NULL,invite TEXT,expires INTEGER NOT NULL);`)}
export function authService(db,config){
 const origin=new URL(config.origin);if(origin.origin!==config.origin||origin.protocol!=='https:'&&!(origin.protocol==='http:'&&origin.hostname==='localhost'))throw Error('Anmeldung benötigt HTTPS oder http://localhost.');if(!/^[a-f0-9]{64}$/.test(config.sessionKey||''))throw Error('Sitzungsschlüssel fehlt.');initializeAuth(db);
 const rpID=origin.hostname,now=()=>Math.floor(Date.now()/1000);
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
 function invite(token){if(typeof token!=='string'||token.length>200)throw Error('Einladung ungültig oder abgelaufen.');const i=db.prepare('SELECT * FROM linux_invites WHERE hash=? AND used=0 AND expires>?').get(digest(token),now());if(!i)throw Error('Einladung ungültig oder abgelaufen.');return i;}
 function saveChallenge(kind,challenge,invitation=null){db.prepare('DELETE FROM linux_challenges WHERE expires<=?').run(now());if(db.prepare('SELECT count(*) AS n FROM linux_challenges').get().n>=1000)throw Error('Zu viele Anmeldeversuche. Bitte später erneut versuchen.');const token=randomBytes(32).toString('base64url');db.prepare('INSERT INTO linux_challenges VALUES(?,?,?,?,?)').run(digest(token),challenge,kind,invitation,now()+300);return token;}
 function consume(token,kind){return transaction(()=>{const c=db.prepare('SELECT * FROM linux_challenges WHERE hash=? AND kind=? AND expires>?').get(digest(String(token)),kind,now());if(!c)throw Error('Anmeldeversuch abgelaufen. Bitte erneut starten.');db.prepare('DELETE FROM linux_challenges WHERE hash=?').run(c.hash);return c})}
 function session(account){const t=now(),p=Buffer.from(JSON.stringify({issuer:'archive-linux-session-v1',subject:account.id,email:account.email,name:account.name,iat:t,exp:t+43200})).toString('base64url');return p+'.'+createHmac('sha256',config.sessionKey).update(p).digest('base64url')}
 return {
  invite({email,name,role},bootstrap=false){email=String(email||'').trim().toLowerCase();name=String(name||'').trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>250||!name||name.length>200||!['admin','manager','user'].includes(role))throw Error('Name, E-Mail und gültige Rolle erforderlich.');return transaction(()=>{if(bootstrap&&db.prepare('SELECT id FROM linux_accounts LIMIT 1').get())throw Error('Erster Administrator ist bereits angelegt.');if(db.prepare('SELECT id FROM linux_accounts WHERE email=?').get(email))throw Error('Für diese E-Mail existiert bereits ein Konto.');if(bootstrap)db.prepare("DELETE FROM linux_invites WHERE role='admin' AND used=0").run();const token=randomBytes(32).toString('base64url');db.prepare('INSERT INTO linux_invites VALUES(?,?,?,?,?,0)').run(digest(token),email,name,role,now()+(bootstrap?7:Math.min(30,Math.max(1,Number(config.inviteDays)||7)))*86400);return token})},
  async registrationOptions(token){const i=invite(token),options=await generateRegistrationOptions({rpName:'Digitales Geschichtsarchiv',rpID,userName:i.email,userDisplayName:i.name,userID:randomBytes(32),attestationType:'none',authenticatorSelection:{residentKey:'required',userVerification:'required'}});return {options,challenge:saveChallenge('register',options.challenge,i.hash)}} ,
  async register(token,response){const c=consume(token,'register'),i=db.prepare('SELECT * FROM linux_invites WHERE hash=? AND used=0 AND expires>?').get(c.invite,now());if(!i)throw Error('Einladung nicht mehr gültig.');const v=await verifyRegistrationResponse({response,expectedChallenge:c.challenge,expectedOrigin:config.origin,expectedRPID:rpID,requireUserVerification:true});if(!v.verified||!v.registrationInfo)throw Error('Passkey konnte nicht verifiziert werden.');const k=v.registrationInfo.credential,account={id:randomUUID(),email:i.email,name:i.name};transaction(()=>{const result=db.prepare('UPDATE linux_invites SET used=1 WHERE hash=? AND used=0 AND expires>?').run(i.hash,now());if(!result.changes)throw Error('Einladung bereits verwendet.');db.prepare('INSERT INTO linux_accounts(id,email,name) VALUES(?,?,?)').run(account.id,account.email,account.name);db.prepare('INSERT INTO linux_credentials VALUES(?,?,?,?,?)').run(k.id,account.id,Buffer.from(k.publicKey).toString('base64url'),k.counter,JSON.stringify(k.transports||[]));db.prepare('INSERT INTO archive_users(id,identity_provider,identity_subject,display_name,created,role) VALUES(?,?,?,?,?,?)').run(account.id,'linux',account.id,account.name,new Date().toISOString(),i.role)});return session(account)},
  async loginOptions(){const options=await generateAuthenticationOptions({rpID,userVerification:'required'});return {options,challenge:saveChallenge('login',options.challenge)}},
  async login(token,response){const c=consume(token,'login'),k=db.prepare('SELECT * FROM linux_credentials WHERE id=?').get(response.id);if(!k)throw Error('Anmeldung fehlgeschlagen.');const account=db.prepare('SELECT * FROM linux_accounts WHERE id=? AND disabled=0').get(k.account_id);if(!account)throw Error('Anmeldung fehlgeschlagen.');const v=await verifyAuthenticationResponse({response,expectedChallenge:c.challenge,expectedOrigin:config.origin,expectedRPID:rpID,credential:{id:k.id,publicKey:new Uint8Array(Buffer.from(k.public_key,'base64url')),counter:k.counter,transports:JSON.parse(k.transports)},requireUserVerification:true});if(!v.verified)throw Error('Anmeldung fehlgeschlagen.');const result=db.prepare('UPDATE linux_credentials SET counter=? WHERE id=? AND counter=?').run(v.authenticationInfo.newCounter,k.id,k.counter);if(!result.changes)throw Error('Parallel erfolgte Anmeldung. Bitte erneut anmelden.');return session(account)},
  pending(){return db.prepare('SELECT hash,email,name,role,expires FROM linux_invites WHERE used=0 AND expires>? ORDER BY expires').all(now())},
  revoke(hash){db.prepare('DELETE FROM linux_invites WHERE hash=? AND used=0').run(hash)},
  accounts(){return db.prepare("SELECT a.id,a.email,a.name,a.disabled,u.role FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id ORDER BY a.name").all()},
  edit(id,role,disabled,actor){if(!['admin','manager','user'].includes(role)||typeof disabled!=='boolean'||id===actor)throw Error('Das eigene Konto kann hier nicht geändert werden.');transaction(()=>{if(!db.prepare('SELECT id FROM linux_accounts WHERE id=?').get(id))throw Error('Konto nicht gefunden.');db.prepare('UPDATE linux_accounts SET disabled=? WHERE id=?').run(Number(disabled),id);db.prepare("UPDATE archive_users SET role=? WHERE identity_provider='linux' AND identity_subject=?").run(role,id)})}
 };
}
