import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {Readable} from 'node:stream';
export function sqliteBinding(filename,migrations){
 fs.mkdirSync(path.dirname(filename),{recursive:true,mode:0o700});const db=new DatabaseSync(filename);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
 db.exec('CREATE TABLE IF NOT EXISTS _linux_migrations(name TEXT PRIMARY KEY,hash TEXT NOT NULL)');
 for(const name of fs.readdirSync(migrations).filter(n=>n.endsWith('.sql')).sort()){
  const sql=fs.readFileSync(path.join(migrations,name),'utf8'),hash=createHash('sha256').update(sql).digest('hex'),old=db.prepare('SELECT hash FROM _linux_migrations WHERE name=?').get(name);
  if(old){if(old.hash!==hash)throw Error('Applied migration changed: '+name);continue;}
  if(db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name='entries'").get()&&!db.prepare('SELECT name FROM _linux_migrations LIMIT 1').get())throw Error('Existing database has no migration ledger. Import it with the verified --linux restore tool.');
  db.exec('BEGIN IMMEDIATE');try{db.exec(sql);db.prepare('INSERT INTO _linux_migrations VALUES(?,?)').run(name,hash);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
 }
 function statement(sql,values=[]){const execute=(kind)=>{const s=db.prepare(sql);if(kind==='run'){const r=s.run(...values);return {success:true,results:[],meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};}return {success:true,results:s.all(...values),meta:{changes:0}};};return {bind(...args){return statement(sql,args.map(v=>v===undefined?null:typeof v==='boolean'?Number(v):v));},async first(column){const row=db.prepare(sql).get(...values);return column?row?.[column]??null:row??null;},async all(){return execute('all')},async run(){return execute('run')},async raw(){return execute('all').results.map(Object.values)},_execute:()=>execute('all'),_batch(){const s=db.prepare(sql);return s.columns().length?execute('all'):execute('run')}};}
 return {prepare:statement,async batch(statements){db.exec('BEGIN IMMEDIATE');try{const r=statements.map(s=>s._batch());db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}},async exec(sql){db.exec(sql);return {count:1,duration:0}},close(){db.close()},database:db};
}
export function fileBucket(root){
 fs.mkdirSync(root,{recursive:true,mode:0o700});const location=key=>path.join(root,createHash('sha256').update(key).digest('hex'));
 async function head(key){try{const base=location(key),m=JSON.parse(await fsp.readFile(base+'.json','utf8'));if(m.key!==key)throw Error('Object key mismatch');const stat=await fsp.stat(base+'.'+m.etag);return {...m,size:stat.size,uploaded:new Date(m.uploaded),writeHttpMetadata(headers){for(const [k,v] of Object.entries(m.httpMetadata||{}))headers.set(k,v)}}}catch(e){if(e.code==='ENOENT')return null;throw e}}
 return {head,async put(key,value,options={}){const base=location(key),temp=base+'.tmp-'+randomUUID(),hash=createHash('sha256');const handle=await fsp.open(temp,'wx',0o600);let size=0;try{const stream=value instanceof ReadableStream?Readable.fromWeb(value):typeof value==='string'||value instanceof ArrayBuffer||ArrayBuffer.isView(value)?[typeof value==='string'?Buffer.from(value):value instanceof ArrayBuffer?Buffer.from(value):Buffer.from(value.buffer,value.byteOffset,value.byteLength)]:value;for await(const chunk of stream){const b=Buffer.from(chunk);hash.update(b);size+=b.length;await handle.writeFile(b)}await handle.sync()}catch(e){await handle.close();await fsp.rm(temp,{force:true});throw e}await handle.close();const etag=hash.digest('hex'),m={key,size,etag,httpEtag:'"'+etag+'"',uploaded:new Date().toISOString(),httpMetadata:options.httpMetadata||{},customMetadata:options.customMetadata||{}};await fsp.rename(temp,base+'.'+etag);const mt=base+'.json.tmp-'+randomUUID();await fsp.writeFile(mt,JSON.stringify(m),{mode:0o600});await fsp.rename(mt,base+'.json');return m;},async get(key,options={}){const h=await head(key);if(!h)return null;const range=options.range;const body=Readable.toWeb(fs.createReadStream(location(key)+'.'+h.etag,range?{start:range.offset,end:range.offset+(range.length??h.size)-1}:{}));return {...h,body,async arrayBuffer(){return new Response(body).arrayBuffer()},async text(){return new Response(body).text()},async json(){return new Response(body).json()}}},async list(options={}){let objects=[];for(const n of await fsp.readdir(root))if(n.endsWith('.json')){const m=JSON.parse(await fsp.readFile(path.join(root,n),'utf8'));if(!options.prefix||m.key.startsWith(options.prefix))objects.push(m)}objects.sort((a,b)=>a.key.localeCompare(b.key,'en'));const start=options.cursor?objects.findIndex(o=>o.key===Buffer.from(options.cursor,'base64url').toString())+1:0,limit=Math.min(options.limit||1000,1000),selected=objects.slice(start,start+limit),truncated=start+limit<objects.length;return {objects:selected,truncated,cursor:truncated?Buffer.from(selected.at(-1).key).toString('base64url'):undefined}},async delete(keys){for(const key of Array.isArray(keys)?keys:[keys]){const base=location(key);await fsp.rm(base+'.json',{force:true});for(const n of await fsp.readdir(root))if(n.startsWith(path.basename(base)+'.'))await fsp.rm(path.join(root,n),{force:true})}}};
}
