import {randomUUID} from 'node:crypto';
export function messageService(db){
 function account(id){const a=db.prepare("SELECT a.id,a.name,u.role FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id WHERE a.id=? AND a.disabled=0 AND u.role IN ('user','manager','admin')").get(id);if(!a)throw Error('Bitte erneut anmelden.');return a}
 function member(actor,id){account(actor);if(!db.prepare('SELECT 1 FROM archive_message_members WHERE thread_id=? AND account_id=?').get(id,actor))throw Error('Diese Unterhaltung ist nicht verfügbar.');return db.prepare('SELECT * FROM archive_message_threads WHERE id=?').get(id)}
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
 function recipients(actor){account(actor);return db.prepare("SELECT a.id,a.name,u.role FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id WHERE a.disabled=0 AND u.role IN ('user','manager','admin') AND a.id<>? ORDER BY a.name,a.id").all(actor)}
 function count(actor){account(actor);return db.prepare('SELECT count(*) AS n FROM archive_messages m JOIN archive_message_members p ON p.thread_id=m.thread_id WHERE p.account_id=? AND m.sender_id<>? AND m.id>p.last_read_id').get(actor,actor).n}
 function list(actor){account(actor);return db.prepare(`SELECT t.*, (SELECT count(*) FROM archive_messages m WHERE m.thread_id=t.id AND m.sender_id<>? AND m.id>p.last_read_id) AS unread,
 (SELECT created FROM archive_messages m WHERE m.thread_id=t.id ORDER BY id DESC LIMIT 1) AS updated,
 (SELECT sender_name FROM archive_messages m WHERE m.thread_id=t.id ORDER BY id DESC LIMIT 1) AS sender,
 (SELECT substr(body,1,100) FROM archive_messages m WHERE m.thread_id=t.id ORDER BY id DESC LIMIT 1) AS preview
 FROM archive_message_threads t JOIN archive_message_members p ON p.thread_id=t.id WHERE p.account_id=? ORDER BY updated DESC,t.id DESC LIMIT 200`).all(actor,actor)}
 function detail(actor,id,before){const t=member(actor,id);const bound=before===undefined?Number.MAX_SAFE_INTEGER:Number(before);if(!Number.isSafeInteger(bound)||bound<1)throw Error('Ungültige Seitenangabe.');const messages=db.prepare('SELECT * FROM archive_messages WHERE thread_id=? AND id<? ORDER BY id DESC LIMIT 100').all(id,bound).reverse();return {...t,members:db.prepare('SELECT account_id AS id,name FROM archive_message_members WHERE thread_id=? ORDER BY name,account_id').all(id),messages,hasOlder:messages.length>0&&!!db.prepare('SELECT 1 FROM archive_messages WHERE thread_id=? AND id<? LIMIT 1').get(id,messages[0].id)}}
 function read(actor,id,lastId){member(actor,id);if(!Number.isSafeInteger(lastId)||!db.prepare('SELECT 1 FROM archive_messages WHERE thread_id=? AND id=?').get(id,lastId))throw Error('Ungültiger Lesestand.');db.prepare('UPDATE archive_message_members SET last_read_id=max(last_read_id,?) WHERE thread_id=? AND account_id=?').run(lastId,id,actor);return {unread:count(actor)}}
 function send(actor,d){return transaction(()=>{const a=account(actor),body=typeof d.body==='string'?d.body.trim():'';if(!body||body.length>4000)throw Error('Bitte einen Nachrichtentext mit höchstens 4.000 Zeichen eingeben.');let id=d.threadId;if(id){const t=member(actor,id);if(t.announcement)throw Error('Mitteilungen an alle können nur mit einer neuen Nachricht beantwortet werden.');if(d.recipients||d.all||d.announcement)throw Error('Die Empfänger einer bestehenden Unterhaltung können nicht geändert werden.')}else{const subject=typeof d.subject==='string'?d.subject.trim():'';if(!subject||subject.length>120)throw Error('Bitte einen Betreff mit höchstens 120 Zeichen eingeben.');if(d.announcement&&a.role!=='admin')throw Error('Nur Admins dürfen eine Mitteilung an alle senden.');if(d.announcement&&!d.all)throw Error('Eine Mitteilung an alle muss alle aktiven Konten erreichen.');const available=recipients(actor),ids=d.all?available.map(x=>x.id):d.recipients;if(!Array.isArray(ids)||!ids.length||ids.length>1000||ids.some(x=>typeof x!=='string'||!available.some(r=>r.id===x)))throw Error('Bitte gültige aktive Empfänger auswählen (höchstens 1.000).');const selected=available.filter(x=>new Set(ids).has(x.id));id=randomUUID();db.prepare('INSERT INTO archive_message_threads VALUES(?,?,?,?)').run(id,subject,new Date().toISOString(),Number(!!d.announcement));for(const r of [a,...selected])db.prepare('INSERT INTO archive_message_members(thread_id,account_id,name) VALUES(?,?,?)').run(id,r.id,r.name)}const result=db.prepare('INSERT INTO archive_messages(thread_id,sender_id,sender_name,body,created) VALUES(?,?,?,?,?)').run(id,actor,a.name,body,new Date().toISOString());return {threadId:id,messageId:Number(result.lastInsertRowid)}})}
 return {recipients,count,list,detail,read,send};
}
