import {randomUUID} from 'node:crypto';
export function messageService(db){
 function account(id){const a=db.prepare("SELECT a.id,a.name,u.role FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id WHERE a.id=? AND a.disabled=0 AND u.role IN ('user','manager','admin')").get(id);if(!a)throw Error('Bitte erneut anmelden.');return a}
 function member(actor,id){account(actor);if(!db.prepare('SELECT 1 FROM archive_message_members WHERE thread_id=? AND account_id=?').get(id,actor))throw Error('Diese Unterhaltung ist nicht verfügbar.');return db.prepare('SELECT * FROM archive_message_threads WHERE id=?').get(id)}
 function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
 function recipients(actor){account(actor);return db.prepare("SELECT a.id,a.name,u.role FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id WHERE a.disabled=0 AND u.role IN ('user','manager','admin') AND a.id<>? ORDER BY a.name,a.id").all(actor)}
 function count(actor){account(actor);return db.prepare('SELECT count(*) AS n FROM archive_messages m JOIN archive_message_members p ON p.thread_id=m.thread_id WHERE p.account_id=? AND m.sender_id<>? AND m.id>p.last_read_id AND m.id>p.hidden_through_id').get(actor,actor).n}
 function notificationRequester(id){const row=db.prepare("SELECT m.body,CASE WHEN r.review_key='notice:'||e.review_token THEN coalesce(nullif(a.name,''),nullif(u.display_name,'')) END AS name FROM archive_messages m JOIN archive_message_references r ON r.thread_id=m.thread_id LEFT JOIN entries e ON e.id=r.entry_id LEFT JOIN archive_users u ON u.id=e.requested_by LEFT JOIN linux_accounts a ON u.identity_provider='linux' AND a.id=u.identity_subject WHERE m.thread_id=? AND m.sender_id='system-publication-notices' ORDER BY m.id LIMIT 1").get(id);const prefix='Angefragt von: ';return row?.body?.startsWith(prefix)?row.body.split('\n')[0].slice(prefix.length):row?.name||'Nicht mehr ermittelbar'}
 function list(actor){account(actor);return db.prepare(`SELECT t.*, EXISTS(SELECT 1 FROM archive_message_references r WHERE r.thread_id=t.id AND r.review_key LIKE 'notice:%') AS notification, (SELECT count(*) FROM archive_messages m WHERE m.thread_id=t.id AND m.sender_id<>? AND m.id>p.last_read_id AND m.id>p.hidden_through_id) AS unread,
 (SELECT max(id) FROM archive_messages m WHERE m.thread_id=t.id) AS lastMessageId,
 (SELECT created FROM archive_messages m WHERE m.thread_id=t.id ORDER BY id DESC LIMIT 1) AS updated,
 (SELECT sender_name FROM archive_messages m WHERE m.thread_id=t.id ORDER BY id DESC LIMIT 1) AS sender,
 (SELECT substr(body,1,100) FROM archive_messages m WHERE m.thread_id=t.id ORDER BY id DESC LIMIT 1) AS preview
 FROM archive_message_threads t JOIN archive_message_members p ON p.thread_id=t.id WHERE p.account_id=? AND (p.hidden_through_id=0 OR EXISTS(SELECT 1 FROM archive_messages m WHERE m.thread_id=t.id AND m.id>p.hidden_through_id)) ORDER BY updated DESC,t.id DESC LIMIT 200`).all(actor,actor).map(t=>({...t,requester:t.notification?notificationRequester(t.id):null}))}
 function detail(actor,id,before){const t=member(actor,id);const visibility=db.prepare('SELECT hidden_through_id FROM archive_message_members WHERE thread_id=? AND account_id=?').get(id,actor);if(visibility.hidden_through_id>0&&!db.prepare('SELECT 1 FROM archive_messages WHERE thread_id=? AND id>?').get(id,visibility.hidden_through_id))throw Error('Diese Unterhaltung wurde für Sie gelöscht. Neue Antworten machen sie wieder sichtbar.');const bound=before===undefined?Number.MAX_SAFE_INTEGER:Number(before);if(!Number.isSafeInteger(bound)||bound<1)throw Error('Ungültige Seitenangabe.');const messages=db.prepare('SELECT * FROM archive_messages WHERE thread_id=? AND id<? ORDER BY id DESC LIMIT 100').all(id,bound).reverse();const reference=db.prepare('SELECT entry_id,review_key FROM archive_message_references WHERE thread_id=?').get(id);const linked=reference?entry(actor,reference.entry_id):null,notification=!!reference?.review_key?.startsWith('notice:');if(notification&&linked)linked.pending=null;return {...t,notification,requester:notification?notificationRequester(id):null,entry:linked,members:db.prepare('SELECT account_id AS id,name FROM archive_message_members WHERE thread_id=? ORDER BY name,account_id').all(id),messages,hasOlder:messages.length>0&&!!db.prepare('SELECT 1 FROM archive_messages WHERE thread_id=? AND id<? LIMIT 1').get(id,messages[0].id)}}
 function entry(actor,id){const a=account(actor),e=db.prepare("SELECT e.*,r.reference FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id WHERE e.id=?").get(id);if(!e||e.deleted)return {id,unavailable:true};const data=JSON.parse(e.data);return {id:e.id,title:data.title,reference:e.reference,pending:['admin','manager'].includes(a.role)&&e.publication_status==='pending'?{id:e.id,updated:e.updated,version:e.requested_version,reviewToken:e.review_token}:null}}
 function reviewDraft(actor,id){const a=account(actor);if(!['admin','manager'].includes(a.role))throw Error('Nur Admin oder Verwalter dürfen Freigabeanfragen besprechen.');const e=db.prepare("SELECT e.*,u.identity_subject AS recipient FROM entries e LEFT JOIN archive_users u ON u.id=e.requested_by AND u.identity_provider='linux' WHERE e.id=? AND e.deleted=0 AND e.publication_status='pending'").get(id);if(!e)throw Error('Keine offene Freigabeanfrage vorhanden.');const r=recipients(actor).find(r=>r.id===e.recipient);if(!r)throw Error('Der Antragsteller hat kein anderes aktives internes Konto. Bitte eine neue Nachricht mit Beitragsreferenz und passenden Empfängern schreiben.');const existing=db.prepare('SELECT t.id FROM archive_message_threads t JOIN archive_message_references r ON r.thread_id=t.id WHERE r.entry_id=? AND r.review_key=? AND t.announcement=0 AND (SELECT count(*) FROM archive_message_members WHERE thread_id=t.id)=2 AND EXISTS(SELECT 1 FROM archive_message_members WHERE thread_id=t.id AND account_id=?) AND EXISTS(SELECT 1 FROM archive_message_members WHERE thread_id=t.id AND account_id=?) ORDER BY t.created DESC LIMIT 1').get(id,e.review_token,actor,r.id);return {entry:entry(actor,id),recipient:r.id,reviewToken:e.review_token,threadId:existing?.id||null}}
 function read(actor,id,lastId){member(actor,id);if(!Number.isSafeInteger(lastId)||!db.prepare('SELECT 1 FROM archive_messages WHERE thread_id=? AND id=?').get(id,lastId))throw Error('Ungültiger Lesestand.');db.prepare('UPDATE archive_message_members SET last_read_id=max(last_read_id,?) WHERE thread_id=? AND account_id=?').run(lastId,id,actor);return {unread:count(actor)}}
 function send(actor,d){return transaction(()=>{const a=account(actor),body=typeof d.body==='string'?d.body.trim():'';if(!body||body.length>4000)throw Error('Bitte einen Nachrichtentext mit höchstens 4.000 Zeichen eingeben.');let id=d.threadId;if(id){const t=member(actor,id);if(t.announcement)throw Error('Mitteilungen an alle können nur mit einer neuen Nachricht beantwortet werden.');if(d.entryId||d.reviewToken||d.recipients||d.all||d.announcement)throw Error('Die Empfänger einer bestehenden Unterhaltung können nicht geändert werden.')}else{const subject=typeof d.subject==='string'?d.subject.trim():'';if(!subject||subject.length>120)throw Error('Bitte einen Betreff mit höchstens 120 Zeichen eingeben.');if(d.announcement&&a.role!=='admin')throw Error('Nur Admins dürfen eine Mitteilung an alle senden.');if(d.announcement&&!d.all)throw Error('Eine Mitteilung an alle muss alle aktiven Konten erreichen.');const available=recipients(actor),ids=d.all?available.map(x=>x.id):d.recipients;if(!Array.isArray(ids)||!ids.length||ids.length>1000||ids.some(x=>typeof x!=='string'||!available.some(r=>r.id===x)))throw Error('Bitte gültige aktive Empfänger auswählen (höchstens 1.000).');const selected=available.filter(x=>new Set(ids).has(x.id));let linked=null,review=null;if(d.entryId){linked=entry(actor,d.entryId);if(linked.unavailable)throw Error('Der verknüpfte Beitrag ist nicht mehr verfügbar.');if(d.reviewToken){review=reviewDraft(actor,d.entryId);if(review.reviewToken!==d.reviewToken||selected.length!==1||selected[0].id!==review.recipient||d.announcement)throw Error('Freigabeanfrage oder Empfänger wurden geändert. Bitte erneut öffnen.');if(review.threadId)id=review.threadId;}}else if(d.reviewToken)throw Error('Beitragsreferenz fehlt.');if(!id){id=randomUUID();db.prepare('INSERT INTO archive_message_threads VALUES(?,?,?,?)').run(id,subject,new Date().toISOString(),Number(!!d.announcement));for(const r of [a,...selected])db.prepare('INSERT INTO archive_message_members(thread_id,account_id,name) VALUES(?,?,?)').run(id,r.id,r.name);if(linked)db.prepare('INSERT INTO archive_message_references(thread_id,entry_id,review_key) VALUES(?,?,?)').run(id,linked.id,review?.reviewToken||null)}}const result=db.prepare('INSERT INTO archive_messages(thread_id,sender_id,sender_name,body,created) VALUES(?,?,?,?,?)').run(id,actor,a.name,body,new Date().toISOString());return {threadId:id,messageId:Number(result.lastInsertRowid)}})}
 function hide(actor,id,throughId){return transaction(()=>{member(actor,id);if(!Number.isSafeInteger(throughId)||throughId<1||!db.prepare('SELECT 1 FROM archive_messages WHERE thread_id=? AND id=?').get(id,throughId))throw Error('Ungültiger Nachrichtenstand. Bitte erneut öffnen.');db.prepare('UPDATE archive_message_members SET hidden_through_id=max(hidden_through_id,?),last_read_id=max(last_read_id,?) WHERE thread_id=? AND account_id=?').run(throughId,throughId,id,actor);
  if(db.prepare("SELECT 1 FROM sqlite_schema WHERE name='linux_push_queue'").get())db.prepare("DELETE FROM linux_push_queue WHERE topic='message' AND subscription_id IN (SELECT id FROM linux_push_subscriptions WHERE account_id=?) AND json_extract(payload,'$.tag') IN (SELECT 'archive-message-'||m.id||':'||? FROM archive_messages m WHERE m.thread_id=? AND m.id<=?)").run(actor,actor,id,throughId);
  return {unread:count(actor)};
 })}
 function openRequests(actor){const a=account(actor);if(!['admin','manager'].includes(a.role))return [];return db.prepare("SELECT e.id,json_extract(e.data,'$.title') AS title,r.reference,e.requested_at AS requestedAt,coalesce(nullif(a.name,''),nullif(u.display_name,''),'Unbekanntes Konto') AS requester FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id LEFT JOIN archive_users u ON u.id=e.requested_by LEFT JOIN linux_accounts a ON u.identity_provider='linux' AND a.id=u.identity_subject WHERE e.publication_status='pending' AND e.deleted=0 ORDER BY e.requested_at,e.id").all()}
 return {recipients,count,list,detail,read,send,hide,reviewDraft,entry,openRequests};
}
