import webpush from 'web-push';
import {createHash,randomUUID} from 'node:crypto';
import {topicsFor,defaultPreferences,canReceive} from './push-policy.mjs';
const eventSources=[
 ['comment',"SELECT id AS key FROM archive_comments WHERE status='pending'"],
 ['publication',"SELECT id||':'||requested_at AS key FROM entries WHERE deleted=0 AND publication_status='pending'"],
 ['backup',"SELECT id AS key FROM archive_backups WHERE status='error'"],
 ['account',"SELECT a.id AS key FROM linux_accounts a WHERE EXISTS(SELECT 1 FROM linux_credentials c WHERE c.account_id=a.id)"]
];
const texts={comment:'Ein neuer Kommentar wartet auf Freigabe.',publication:'Ein Beitrag wartet auf Genehmigung.',backup:'Eine Sicherung ist fehlgeschlagen. Bitte den Sicherungsstatus prüfen.',account:'Eine eingeladene Person hat ihr Konto mit einem Passkey aktiviert.',update:'Eine neue Softwareversion ist verfügbar.',qr:'QR-Codes sind nicht erreichbar. Bitte die Hinweise auf der Startseite prüfen.'};
export function validSubscription(s){if(!s||typeof s.endpoint!=='string'||s.endpoint.length>2000)throw Error('Ungültige Push-Adresse.');const u=new URL(s.endpoint);if(u.protocol!=='https:'||u.port||u.username||u.password||u.hash||!(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.notify.windows.com')))throw Error('Dieser Push-Anbieter wird nicht unterstützt.');for(const [key,size] of [['p256dh',65],['auth',16]]){const v=s.keys?.[key];if(typeof v!=='string'||!/^[-_A-Za-z0-9]+$/.test(v)||Buffer.from(v,'base64url').length!==size)throw Error('Ungültiger Push-Schlüssel.')}if(Buffer.from(s.keys.p256dh,'base64url')[0]!==4)throw Error('Ungültiger Push-Schlüssel.');return {endpoint:u.href,keys:{p256dh:s.keys.p256dh,auth:s.keys.auth}}}
function qrProblem(db){return !!db.prepare("SELECT 1 FROM qr_access_alerts a JOIN entries e ON e.id=a.entry_id WHERE e.publication_status<>'approved' LIMIT 1").get()}
export function initializePush(db){db.exec(`CREATE TABLE IF NOT EXISTS linux_push_config(key TEXT PRIMARY KEY,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS linux_push_preferences(account_id TEXT PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 0,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS linux_push_subscriptions(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,endpoint TEXT NOT NULL UNIQUE,data TEXT NOT NULL,created TEXT NOT NULL,last_error TEXT);
CREATE TABLE IF NOT EXISTS linux_push_seen(topic TEXT NOT NULL,event_key TEXT NOT NULL,PRIMARY KEY(topic,event_key));
CREATE TABLE IF NOT EXISTS linux_push_queue(id TEXT PRIMARY KEY,subscription_id TEXT NOT NULL,topic TEXT NOT NULL,payload TEXT NOT NULL,created INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL DEFAULT 0,lease INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_push_account ON linux_push_subscriptions(account_id);
CREATE INDEX IF NOT EXISTS idx_push_credentials_account ON linux_credentials(account_id);
CREATE INDEX IF NOT EXISTS idx_push_queue_due ON linux_push_queue(next_attempt,lease);`);
 if(!db.prepare("SELECT key FROM linux_push_config WHERE key='initialized'").get()){db.exec('BEGIN IMMEDIATE');try{for(const [topic,sql] of eventSources)db.prepare(`INSERT OR IGNORE INTO linux_push_seen SELECT ?,key FROM (${sql})`).run(topic);db.prepare("INSERT OR IGNORE INTO linux_push_config VALUES('qr',?)").run(JSON.stringify(qrProblem(db)));db.prepare("INSERT OR IGNORE INTO linux_push_config VALUES('initialized','true')").run();db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
 if(!db.prepare("SELECT key FROM linux_push_config WHERE key='vapid'").get())db.prepare("INSERT OR IGNORE INTO linux_push_config VALUES('vapid',?)").run(JSON.stringify(webpush.generateVAPIDKeys()));
}
export function pushService(db,{origin='',send=webpush.sendNotification}={}){
 function account(actor){const a=db.prepare("SELECT a.id,u.role FROM linux_accounts a JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id WHERE a.id=? AND a.disabled=0").get(actor);if(!a)throw Error('Bitte erneut anmelden.');return a}
 function settings(actor){const a=account(actor),p=db.prepare('SELECT * FROM linux_push_preferences WHERE account_id=?').get(actor);return {available:true,enabled:!!p?.enabled,preferences:{...defaultPreferences(a.role),...(p?Object.fromEntries(Object.entries(JSON.parse(p.data)).filter(([t])=>canReceive(a.role,t))):{})},topics:topicsFor(a.role),devices:db.prepare('SELECT count(*) AS n FROM linux_push_subscriptions WHERE account_id=?').get(actor).n,publicKey:JSON.parse(db.prepare("SELECT data FROM linux_push_config WHERE key='vapid'").get().data).publicKey,deliveryErrors:db.prepare('SELECT count(*) AS n FROM linux_push_subscriptions WHERE account_id=? AND last_error IS NOT NULL').get(actor).n}}
 function configure(actor,enabled,prefs){const a=account(actor);if(typeof enabled!=='boolean'||!prefs||typeof prefs!=='object'||Array.isArray(prefs)||Object.entries(prefs).some(([t,v])=>!canReceive(a.role,t)||typeof v!=='boolean'))throw Error('Ungültige Benachrichtigungseinstellungen.');db.prepare('INSERT INTO linux_push_preferences VALUES(?,?,?) ON CONFLICT(account_id) DO UPDATE SET enabled=excluded.enabled,data=excluded.data').run(actor,enabled?1:0,JSON.stringify({...defaultPreferences(a.role),...prefs}));if(!enabled)db.prepare('DELETE FROM linux_push_queue WHERE subscription_id IN(SELECT id FROM linux_push_subscriptions WHERE account_id=?)').run(actor);else for(const topic of ['qr','comment','publication','backup','account','update'])if(!canReceive(a.role,topic)||!(prefs[topic]??defaultPreferences(a.role)[topic]))db.prepare('DELETE FROM linux_push_queue WHERE topic=? AND subscription_id IN(SELECT id FROM linux_push_subscriptions WHERE account_id=?)').run(topic,actor);return settings(actor)}
 function subscribe(actor,raw){account(actor);const s=validSubscription(raw);const existing=db.prepare('SELECT account_id FROM linux_push_subscriptions WHERE endpoint=?').get(s.endpoint);if(existing&&existing.account_id!==actor)throw Error('Dieser Browser ist für ein anderes Konto registriert. Bitte dort Push deaktivieren und diesen Browser abmelden.');if(!existing&&settings(actor).devices>=20)throw Error('Es sind bereits 20 Geräte registriert.');db.prepare('INSERT INTO linux_push_subscriptions VALUES(?,?,?,?,?,NULL) ON CONFLICT(endpoint) DO UPDATE SET data=excluded.data,last_error=NULL').run(createHash('sha256').update(s.endpoint).digest('hex'),actor,s.endpoint,JSON.stringify(s),new Date().toISOString());return settings(actor)}
 function unsubscribe(actor){account(actor);db.prepare('DELETE FROM linux_push_queue WHERE subscription_id IN(SELECT id FROM linux_push_subscriptions WHERE account_id=?)').run(actor);db.prepare('DELETE FROM linux_push_subscriptions WHERE account_id=?').run(actor);return settings(actor)}
 function removeDevice(actor,endpoint){account(actor);db.prepare('DELETE FROM linux_push_queue WHERE subscription_id IN(SELECT id FROM linux_push_subscriptions WHERE account_id=? AND endpoint=?)').run(actor,endpoint);db.prepare('DELETE FROM linux_push_subscriptions WHERE account_id=? AND endpoint=?').run(actor,endpoint)}
 function enqueue(topic,key,body=texts[topic],target=null,url='/'){if(!db.prepare('INSERT OR IGNORE INTO linux_push_seen VALUES(?,?)').run(topic,key).changes)return;const subscribers=db.prepare("SELECT s.id,s.account_id,p.data,u.role FROM linux_push_subscriptions s JOIN linux_push_preferences p ON p.account_id=s.account_id JOIN linux_accounts a ON a.id=s.account_id JOIN archive_users u ON u.identity_provider='linux' AND u.identity_subject=a.id WHERE p.enabled=1 AND a.disabled=0").all();for(const s of subscribers)if((!target||s.account_id===target)&&canReceive(s.role,topic)&&(JSON.parse(s.data)[topic]??defaultPreferences(s.role)[topic]))db.prepare('INSERT INTO linux_push_queue(id,subscription_id,topic,payload,created) VALUES(?,?,?,?,?)').run(randomUUID(),s.id,topic,JSON.stringify({title:'Geschichtsarchiv',body,url,tag:topic==='message'?'archive-message-'+key:'archive-'+topic}),Date.now())}
 function scan(){db.exec('BEGIN IMMEDIATE');try{for(const [topic,sql] of eventSources){for(const r of db.prepare(`SELECT key FROM (${sql}) source WHERE NOT EXISTS(SELECT 1 FROM linux_push_seen x WHERE x.topic=? AND x.event_key=source.key) LIMIT 100`).all(topic))enqueue(topic,r.key)}for(const m of db.prepare("SELECT m.id,m.thread_id,p.account_id FROM archive_messages m JOIN archive_message_members p ON p.thread_id=m.thread_id JOIN linux_accounts a ON a.id=p.account_id AND a.disabled=0 WHERE m.sender_id<>p.account_id AND m.id>p.last_read_id AND NOT EXISTS(SELECT 1 FROM linux_push_seen s WHERE s.topic='message' AND s.event_key=CAST(m.id AS TEXT)||':'||p.account_id) ORDER BY m.id LIMIT 500").all())enqueue('message',m.id+':'+m.account_id,'Eine neue interne Nachricht liegt vor.',m.account_id,'/?ansicht=nachrichten&unterhaltung='+encodeURIComponent(m.thread_id));const old=JSON.parse(db.prepare("SELECT data FROM linux_push_config WHERE key='qr'").get().data),current=qrProblem(db);if(old!==current){const key=randomUUID();enqueue('qr',key,current?texts.qr:'Alle gemeldeten QR-Probleme sind behoben.');db.prepare("UPDATE linux_push_config SET data=? WHERE key='qr'").run(JSON.stringify(current))}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
 function updates(releases){for(const r of releases||[])if(!r.skipped&&/^v\d+\.\d+\.\d+$/.test(r.tag))enqueue('update',r.tag)}
 async function deliver(limit=5){if(!Number.isInteger(limit)||limit<1||limit>5)throw Error('Ungültiges Zustelllimit.');const vapid=JSON.parse(db.prepare("SELECT data FROM linux_push_config WHERE key='vapid'").get().data);db.prepare('DELETE FROM linux_push_queue WHERE created<? OR attempts>=6').run(Date.now()-86400000);let sent=0;for(let i=0;i<limit;i++){const now=Date.now(),q=db.prepare('UPDATE linux_push_queue SET lease=? WHERE id=(SELECT id FROM linux_push_queue WHERE next_attempt<=? AND lease<? ORDER BY created LIMIT 1) RETURNING *').get(now+60000,now,now);if(!q)break;const s=db.prepare('SELECT * FROM linux_push_subscriptions WHERE id=?').get(q.subscription_id);if(!s){db.prepare('DELETE FROM linux_push_queue WHERE id=?').run(q.id);continue}let state;try{state=settings(s.account_id)}catch{}if(!state?.enabled||!state.preferences[q.topic]){db.prepare('DELETE FROM linux_push_queue WHERE id=?').run(q.id);continue}try{await send(validSubscription(JSON.parse(s.data)),q.payload,{vapidDetails:{subject:origin?.startsWith('https:')?origin:'mailto:archive@example.invalid',...vapid},TTL:3600,urgency:'normal',timeout:8000});db.prepare('DELETE FROM linux_push_queue WHERE id=?').run(q.id);db.prepare('UPDATE linux_push_subscriptions SET last_error=NULL WHERE id=?').run(s.id);sent++}catch(e){if([404,410].includes(e.statusCode)){db.prepare('DELETE FROM linux_push_subscriptions WHERE id=?').run(s.id);db.prepare('DELETE FROM linux_push_queue WHERE subscription_id=?').run(s.id)}else{db.prepare('UPDATE linux_push_queue SET attempts=attempts+1,next_attempt=?,lease=0 WHERE id=?').run(now+Math.min(3600000,60000*2**q.attempts),q.id);db.prepare('UPDATE linux_push_subscriptions SET last_error=? WHERE id=?').run('Zustellung derzeit nicht möglich.',s.id)}}}return {sent,pending:db.prepare('SELECT count(*) AS n FROM linux_push_queue').get().n}}
 return {settings,configure,subscribe,unsubscribe,removeDevice,scan,updates,deliver};
}
