import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import http from 'node:http';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {UpdateEngine} from './update-engine.mjs';
import {acquireUpdateLock} from './update-lock.mjs';
import {createSourceManager,checkLocalRelease} from './update-source.mjs';
const exec=promisify(execFile),configFile=process.env.ARCHIVE_UPDATER_CONFIG||'/etc/geschichtsarchiv/updater.json',configStat=await fs.stat(configFile);if(configStat.mode&0o077)throw Error('Updater-Konfiguration muss ausschließlich für ihren Eigentümer lesbar sein (0600).');const cfg=JSON.parse(await fs.readFile(configFile,'utf8'));
if(!path.resolve(configFile).startsWith(path.resolve(cfg.configRoot)+path.sep))throw Error('Updater-Konfiguration muss in der gesicherten Konfigurationsablage liegen.');
if(!/^[a-f0-9]{64}$/.test(cfg.secret)||!/^\w[\w.-]*\/[\w.-]+$/.test(cfg.repository)||!path.isAbsolute(cfg.driver)||!Number.isInteger(cfg.port)||cfg.port<1024||cfg.port>65535)throw Error('Ungültige Updater-Konfiguration.');
await fs.mkdir(cfg.root,{recursive:true,mode:0o700});
await acquireUpdateLock(cfg.root);
const headers={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',...(cfg.githubToken?{Authorization:'Bearer '+cfg.githubToken}:{})};
async function listReleases(){const repository=cfg.repository;const result=[];for(let page=1;page<=10;page++){const r=await fetch('https://api.github.com/repos/'+repository+'/releases?per_page=100&page='+page,{headers,signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('GitHub-Prüfung fehlgeschlagen (HTTP '+r.status+').');const rows=await r.json();if(!Array.isArray(rows))throw Error('Ungültige Release-Antwort.');for(const v of rows)result.push({tag:v.tag_name,name:String(v.name||v.tag_name).slice(0,200),notes:String(v.body||'').slice(0,20000),url:v.html_url,prerelease:v.prerelease,draft:v.draft});if(rows.length<100)break}if(repository!==cfg.repository||sources.changing)throw Error('Update-Quelle hat sich während der Suche geändert. Bitte erneut suchen.');return result;}
async function runDriver(action,code,dataRoot=cfg.dataRoot,configRoot=cfg.configRoot){try{await exec(cfg.driver,[action,code,dataRoot,configRoot],{timeout:900000,maxBuffer:1024*1024})}catch{throw Error('Serverprüfung „'+action+'“ fehlgeschlagen.')}}
async function prepareRelease(release,report=async()=>{}){if(!/^v\d+\.\d+\.\d+$/.test(release.tag))throw Error('Ungültiges Release.');const repo=path.join(cfg.root,'source-cache');try{await exec('git',['init','--bare',repo]);}catch{throw Error('Quellcache konnte nicht vorbereitet werden.')}const env={...process.env,GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_COUNT:'2',GIT_CONFIG_KEY_0:'core.hooksPath',GIT_CONFIG_VALUE_0:'/dev/null',GIT_CONFIG_KEY_1:'http.https://github.com/.extraHeader',GIT_CONFIG_VALUE_1:cfg.githubToken?'Authorization: Basic '+Buffer.from('x-access-token:'+cfg.githubToken).toString('base64'):''};
 await report('downloading');try{await exec('git',['--git-dir',repo,'fetch','--no-tags','--depth=1','https://github.com/'+cfg.repository+'.git','refs/tags/'+release.tag],{env,timeout:180000,maxBuffer:1024*1024})}catch{throw Error('Release-Code konnte nicht geladen werden.')}const {stdout}=await exec('git',['--git-dir',repo,'rev-parse','FETCH_HEAD^{commit}']);const sha=stdout.trim();if(!/^[a-f0-9]{40}$/.test(sha))throw Error('Ungültiger Code-Commit.');const tree=await exec('git',['--git-dir',repo,'ls-tree','-rz',sha],{maxBuffer:16*1024*1024});for(const record of tree.stdout.split('\0').filter(Boolean)){const [meta,name]=record.split('\t');if(!/^(100644|100755) blob /.test(meta)||!name||path.isAbsolute(name)||name.split('/').some(s=>s==='.'||s==='..')||name.includes('\\'))throw Error('Release enthält nicht unterstützte Dateien.');}
 const target=path.join(cfg.root,'releases',release.tag+'-'+sha+'-'+crypto.randomUUID());await fs.mkdir(target,{recursive:true,mode:0o700});const git=spawn('git',['--git-dir',repo,'archive','--format=tar',sha],{stdio:['ignore','pipe','ignore']}),tar=spawn('tar',['-xf','-','-C',target,'--no-same-owner'],{stdio:['pipe','ignore','ignore']});git.stdout.pipe(tar.stdin);tar.stdin.on('error',()=>git.kill());const end=p=>new Promise((resolve,reject)=>{p.on('error',reject);p.on('exit',c=>c===0?resolve():reject(Error('Release konnte nicht entpackt werden.')))});await Promise.all([end(git),end(tar)]);const version=JSON.parse(await fs.readFile(path.join(target,'version.json'),'utf8'));version.codeCommit=sha;await fs.writeFile(path.join(target,'version.json'),JSON.stringify(version,null,2)+'\n');if(cfg.requireProjectContract)await checkLocalRelease(target,await engine.current(),release.tag);await report('building');await runDriver('prepare',target);return target;}
const engine=await new UpdateEngine({...cfg,driver:runDriver,listReleases,prepareRelease,validateRestore:(data,config,code)=>runDriver('verify-restore',code,data,config)}).init();
const sources=createSourceManager({cfg,configFile,engine,headers});await sources.reconcile();
const nonces=new Map();
http.createServer(async(req,res)=>{try{if(req.url!=='/updates'||!['GET','POST'].includes(req.method)){res.writeHead(404);res.end();return;}let body='';for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>16000)throw Error('Anfrage zu groß.');}const time=req.headers['x-archive-time'],nonce=req.headers['x-archive-nonce'],signature=req.headers['x-archive-signature'];const expected=crypto.createHmac('sha256',cfg.secret).update([time,nonce,req.method,req.url,body].join('\n')).digest('hex');if(typeof signature!=='string'||!/^\d{13}$/.test(time||'')||Math.abs(Date.now()-Number(time))>60000||!/^[-\w]{36}$/.test(nonce||'')||nonces.has(nonce)||!/^[a-f0-9]{64}$/.test(signature)||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected))){res.writeHead(403);res.end();return;}for(const [n,t] of nonces)if(t<Date.now()-60000)nonces.delete(n);nonces.set(nonce,Date.now());let result,status=200;if(req.method==='GET')result={...await engine.status(),...sources.info()};else{const d=JSON.parse(body);if(sources.changing)throw Error('Quellenwechsel läuft.');if(d.action==='source-forks')result=await sources.forks();else if(d.action==='source-inspect')result=await sources.inspect(d.repository);else if(d.action==='source-change')result=await sources.change(d);else if(d.action==='check')result=await engine.check(true);else if(d.action==='skip')result=await engine.skip(d.tag,d.skip!==false);else if(d.action==='install'){if(engine.busy||engine.state.job?.recoveryError)throw Error('Ein Update oder eine Wiederherstellung ist noch offen.');if(d.confirmation!=='UPDATE MIT GEPRÜFTER SICHERUNG')throw Error('Bitte den Bestätigungstext eingeben.');engine.state.updateError=null;await engine.persist();engine.startUpdate(d.tag).catch(async e=>{engine.state.updateError=String(e.message).slice(0,400);await engine.persist()});result={queued:true};status=202;}else if(d.action==='retry-recovery'){if(engine.busy)throw Error('Ein Update läuft.');engine.busy=true;engine.recover().finally(()=>{engine.busy=false});result={queued:true};status=202;}else throw Error('Unbekannte Aktion.');}if(result?.enabled)result={...result,...sources.info()};res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(result));}catch(e){res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:String(e.message).slice(0,400)}));}}).listen(cfg.port,'127.0.0.1');
async function automatic(){if(engine.busy||sources.changing)return;try{await engine.check(false)}catch(e){engine.state.checkError=String(e.message).slice(0,400);await engine.persist()}}automatic();setInterval(automatic,6*60*60*1000).unref();
