import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
export const compareVersions=(a,b)=>{const x=a.replace(/^v/,'').split('.').map(Number),y=b.replace(/^v/,'').split('.').map(Number);for(let i=0;i<3;i++)if(x[i]!==y[i])return x[i]-y[i];return 0};
const validTag=t=>/^v(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/.test(t);
async function atomic(file,data){await fs.mkdir(path.dirname(file),{recursive:true,mode:0o700});const temp=file+'.'+crypto.randomUUID();const handle=await fs.open(temp,'wx',0o600);try{await handle.writeFile(JSON.stringify(data,null,2));await handle.sync()}finally{await handle.close()}await fs.rename(temp,file)}
async function inventory(root,allowLinks=false){const rows=[];async function walk(relative=''){for(const item of await fs.readdir(path.join(root,relative),{withFileTypes:true})){const name=path.join(relative,item.name),file=path.join(root,name),stat=await fs.lstat(file);if(stat.isSymbolicLink()&&allowLinks){const link=await fs.readlink(file),resolved=await fs.realpath(file);if(path.isAbsolute(link)||!resolved.startsWith(root+path.sep))throw Error('Code-Verknüpfung verlässt die Release-Ablage.');rows.push({name,link});continue;}if(stat.isSymbolicLink()||!stat.isFile()&&!stat.isDirectory())throw Error('Die Sicherung enthält eine nicht unterstützte Verknüpfung oder Spezialdatei.');if(stat.isDirectory())await walk(name);else{const hash=crypto.createHash('sha256');const h=await fs.open(file);try{for await(const chunk of h.createReadStream())hash.update(chunk)}finally{await h.close()}rows.push({name,size:stat.size,sha256:hash.digest('hex')});if(/\.(sqlite|db)$/.test(file)){const db=new DatabaseSync(file,{readOnly:true});try{if(db.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('Datenbankprüfung fehlgeschlagen.')}finally{db.close()}}}}}await walk();return rows.sort((a,b)=>a.name.localeCompare(b.name))}
async function copyVerified(source,target,allowLinks=false){const before=await inventory(source,allowLinks);await fs.cp(source,target,{recursive:true,errorOnExist:true,force:false,verbatimSymlinks:true});const after=await inventory(target,allowLinks);if(JSON.stringify(before)!==JSON.stringify(after))throw Error('Sicherungsprüfung fehlgeschlagen.');return after}
export class UpdateEngine{
 constructor({root,dataRoot,configRoot,driver,listReleases,prepareRelease,validateRestore}){Object.assign(this,{root:path.resolve(root),dataRoot:path.resolve(dataRoot),configRoot:path.resolve(configRoot),driver,listReleases,prepareRelease,validateRestore});this.stateFile=path.join(this.root,'update-state.json');this.busy=false;}
 async init(){if(!this.driver||!this.validateRestore)throw Error('Serveradapter und Probe-Wiederherstellung müssen konfiguriert sein.');const paths=[this.root,this.dataRoot,this.configRoot];if(paths.some((p,i)=>paths.some((q,j)=>i!==j&&(p===q||p.startsWith(q+path.sep)))))throw Error('Updater-, Daten- und Konfigurationsablage müssen getrennt sein.');await fs.mkdir(this.root,{recursive:true,mode:0o700});try{this.state=JSON.parse(await fs.readFile(this.stateFile,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;this.state={skipped:[],releases:[],history:[],job:null,lastCheck:null,lastBackup:null}}if(this.state.job&&!['complete','rolled_back'].includes(this.state.job.status)){await this.recover();}else if(this.state.job?.status==='complete'){const c=await this.current();await this.driver('health',c.code);await this.driver('commit',c.code);}await this.current();return this;}
 async persist(){this.persistChain=(this.persistChain||Promise.resolve()).catch(()=>{}).then(()=>atomic(this.stateFile,this.state));await this.persistChain}
 async current(){const code=await fs.realpath(path.join(this.root,'current')),v=JSON.parse(await fs.readFile(path.join(code,'version.json'),'utf8'));if(!/^[a-f0-9]{40}$/.test(v.codeCommit||''))throw Error('Code-Commit des installierten Stands fehlt.');if(!code.startsWith(path.join(this.root,'releases')+path.sep))throw Error('Programmstand liegt außerhalb der Release-Ablage.');return {code,...v};}
 async check(manual=false){if(this.busy)throw Error('Eine Aktualisierung läuft bereits.');const releases=await this.listReleases();if(this.busy)return this.status(manual);this.state.releases=releases.filter(r=>!r.draft&&!r.prerelease&&validTag(r.tag)).sort((a,b)=>compareVersions(b.tag,a.tag));this.state.lastCheck=new Date().toISOString();this.state.checkError=null;await this.persist();return this.status(manual)}
 async status(manual=false){const current=await this.current();return {enabled:true,currentVersion:current.version,lastCheck:this.state.lastCheck,checkError:this.state.checkError,updateError:this.state.updateError,lastBackup:this.state.lastBackup,job:this.state.job,history:this.state.history.slice(-20).reverse(),releases:this.state.releases.filter(r=>compareVersions(r.tag,current.version)>0&&(manual||!this.state.skipped.includes(r.tag))).map(r=>({...r,skipped:this.state.skipped.includes(r.tag)}))};}
 async skip(tag,skip=true){if(this.busy)throw Error('Eine Aktualisierung läuft bereits.');if(!validTag(tag)||!this.state.releases.some(r=>r.tag===tag))throw Error('Unbekannte Version.');this.state.skipped=this.state.skipped.filter(t=>t!==tag);if(skip)this.state.skipped.push(tag);await this.persist();return this.status(true)}
 async phase(status){const j=this.state.job;j.status=status;j.updated=new Date().toISOString();j.events=[...(j.events||[]),{status,at:j.updated}].slice(-100);await this.persist()}
 async snapshot(current){const dest=path.join(this.root,'backups',this.state.job.id);await fs.mkdir(dest,{recursive:true,mode:0o700});const data=await copyVerified(this.dataRoot,path.join(dest,'data')),config=await copyVerified(this.configRoot,path.join(dest,'config')),code=await copyVerified(current.code,path.join(dest,'code'),true);const manifest={created:new Date().toISOString(),applicationVersion:current.version,codeCommit:current.codeCommit||null,databaseSchemaVersion:current.databaseSchemaVersion,backupFormatVersion:current.backupFormatVersion,data,config,code};await atomic(path.join(dest,'manifest.json'),manifest);
 // Rehearse restoration into an independent directory and run application-level validation.
 await this.phase('verifying_backup');const trial=path.join(dest,'restore-test');await fs.mkdir(trial,{mode:0o700});await copyVerified(path.join(dest,'data'),path.join(trial,'data'));await copyVerified(path.join(dest,'config'),path.join(trial,'config'));await this.validateRestore(path.join(trial,'data'),path.join(trial,'config'),current.code);await fs.rm(trial,{recursive:true});this.state.lastBackup={id:this.state.job.id,version:current.version,created:manifest.created,verified:new Date().toISOString(),restoreTested:true};this.state.job.backup=dest;await this.persist();return dest;}
 async switchCode(code){const link=path.join(this.root,'current'),temp=link+'.'+crypto.randomUUID();await fs.symlink(code,temp);await fs.rename(temp,link)}
 async startUpdate(tag){if(this.state.job?.recoveryError)throw Error('Wiederherstellung muss zuerst abgeschlossen werden.');if(this.busy)throw Error('Eine Aktualisierung läuft bereits.');this.busy=true;try{const current=await this.current();const available=(await this.listReleases()).find(r=>r.tag===tag&&!r.prerelease&&!r.draft);if(!available||!validTag(tag)||compareVersions(tag,current.version)<=0)throw Error('Version ist nicht als neues stabiles Release freigegeben.');this.state.updateError=null;this.state.job={id:crypto.randomUUID(),status:'preparing',tag,previous:current.code,created:new Date().toISOString(),previousVersion:current.version,stopped:false,dataMayChange:false};await this.phase('preparing');try{
 const code=await this.prepareRelease(available,status=>this.phase(status));const next=JSON.parse(await fs.readFile(path.join(code,'version.json'),'utf8'));if(next.version!==tag.slice(1)||!Number.isInteger(next.databaseSchemaVersion)||next.databaseSchemaVersion<current.databaseSchemaVersion)throw Error('Release-Metadaten sind nicht kompatibel.');this.state.job.next=code;await this.phase('stopping');this.state.job.stopped=true;await this.persist();await this.driver('stop',current.code);await this.phase('backing_up');await this.snapshot(current);await this.phase('migrating');this.state.job.dataMayChange=true;await this.persist();await this.driver('migrate',code);await this.switchCode(code);await this.phase('starting');await this.driver('start',code);await this.phase('checking');await this.driver('health',code);await this.driver('commit',code);this.state.job.finished=new Date().toISOString();await this.phase('complete');this.state.history.push({...this.state.job});await this.persist();
 }catch(e){this.state.job.error=String(e.message).slice(0,400);await this.persist();await this.recover();}return this.status(true);}finally{this.busy=false}}
 async recover(){const j=this.state.job;if(!j)return;try{await this.phase('rolling_back');if(j.stopped){await this.driver('stop',j.next||j.previous);if(j.dataMayChange){if(!j.backup)throw Error('Geprüfte Sicherung fehlt. Wartungsmodus bleibt aktiv.');const m=JSON.parse(await fs.readFile(path.join(j.backup,'manifest.json'),'utf8'));for(const [kind,target] of [['data',this.dataRoot],['config',this.configRoot]]){if(JSON.stringify(await inventory(path.join(j.backup,kind)))!==JSON.stringify(m[kind]))throw Error('Rollback-Sicherung ist beschädigt.');const restored=target+'.restore-'+j.id,failed=target+'.failed-'+j.id;await fs.rm(restored,{recursive:true,force:true});await copyVerified(path.join(j.backup,kind),restored);const retained=failed+'-'+crypto.randomUUID();try{await fs.rename(target,retained)}catch(e){if(e.code!=='ENOENT')throw e}await fs.rename(restored,target);}await this.validateRestore(this.dataRoot,this.configRoot,j.previous);}await this.switchCode(j.previous);await this.driver('start',j.previous);await this.driver('health',j.previous);await this.driver('commit',j.previous);}delete j.recoveryError;j.finished=new Date().toISOString();await this.phase('rolled_back');this.state.history.push({...j});}catch(e){j.recoveryError=String(e.message).slice(0,400);await this.phase('error');}await this.persist();}
}
