import {archiveDb} from './archive-db';
import {timelineRevision,saveTimelineSelection} from './archive-timeline-selections';
import {matchesRotation,nextRotation,rotatingSelection} from './archive-timeline-rotation-rules';
export async function rotationPlan(){const db=archiveDb();await db.prepare("INSERT OR IGNORE INTO timeline_rotation(id,revision,enabled,filters,amount,cadence,first_local,updated) VALUES('main','initial',0,?,5,'weekly','',?)").bind(JSON.stringify({query:'',category:'all',media:'all',from:'',to:''}),new Date().toISOString()).run();const row=await db.prepare("SELECT * FROM timeline_rotation WHERE id='main'").first<any>();return {...row,enabled:!!row.enabled,filters:JSON.parse(row.filters)}}
export async function runDueRotation(){const plan=await rotationPlan(),now=new Date(),stamp=now.toISOString();if(!plan.enabled||!plan.next_run||plan.next_run>stamp)return {changed:false,enabled:plan.enabled,nextRun:plan.next_run,lastRun:plan.last_run,lastResult:plan.last_result};const db=archiveDb(),revision=await timelineRevision();
 const rows=await db.prepare('SELECT e.id,e.timeline_visible,r.reference,v.data FROM entries e LEFT JOIN entry_references r ON r.entry_id=e.id LEFT JOIN entry_versions v ON v.entry_id=e.id AND v.version=e.approved_version WHERE e.deleted=0 AND e.publication_status=\'approved\' AND e.approved_by IS NOT NULL AND e.approved_at IS NOT NULL AND v.data IS NOT NULL').all();
 const candidates=rows.results.filter((r:any)=>{const d=JSON.parse(r.data);return matchesRotation({...d,reference:r.reference,images:d.files.some((f:any)=>f.type.startsWith('image/')),audio:d.files.some((f:any)=>f.type.startsWith('audio/')),documents:d.files.some((f:any)=>!f.type.startsWith('image/')&&!f.type.startsWith('audio/'))},plan.filters)}).map((r:any)=>r.id as string);
 const previousRows=await db.prepare('SELECT id FROM entries WHERE deleted=0 AND timeline_visible=1').all(),previous=new Set(previousRows.results.map(r=>r.id as string)),selected=rotatingSelection(candidates,previous,plan.amount),nextRun=nextRotation(plan.first_local,plan.cadence,now);
 if(!selected.size){const result='Keine passenden freigegebenen Beiträge. Die bisherige Auswahl bleibt erhalten.';await db.prepare("UPDATE timeline_rotation SET revision=?,next_run=?,last_run=?,last_result=?,updated=? WHERE id='main' AND enabled=1 AND revision=? AND EXISTS(SELECT 1 FROM timeline_control WHERE id='main' AND revision=?)").bind(crypto.randomUUID(),nextRun,stamp,result,stamp,plan.revision,revision).run();return {changed:false,enabled:true,nextRun,lastResult:result}}
 const result=`${selected.size} von ${candidates.length} passenden Beiträgen ausgewählt${selected.size<plan.amount?' (weniger als gewünscht verfügbar)':''}.`;
 await saveTimelineSelection({add:[...selected].filter(id=>!previous.has(id)),remove:[...previous].filter(id=>!selected.has(id)),baseRevision:revision,label:'Automatische Rotation',actorName:'Zeitplan · Öffentliche Zeitleiste',automatic:{revision:plan.revision,nextRun,result,now:stamp}});
 return {changed:true,enabled:true,nextRun,lastRun:stamp,lastResult:result,selectedCount:selected.size};
}
