import version from '@/version.json';
import {installation} from './archive-installation';
import {env} from '@/lib/runtime-env';
import {createHash} from 'node:crypto';
import {archiveDb} from './archive-db';
import {systemSettings,davRequest,ensureDavFolder} from './archive-system-settings';
export const backupBucket=()=> (env as unknown as {BUCKET:R2Bucket}).BUCKET;
const tables=['archive_message_threads','archive_message_members','archive_messages','qr_access_alerts','storage_places','archive_users','entries','entry_versions','archive_settings','archive_comments','entry_references','qr_print_jobs','qr_print_items','timeline_control','timeline_selections','timeline_selection_members','timeline_rotation','public_page_views','archive_backups'];
const prefix=(id:string)=>'_backups/'+id+'/';
function withoutPasswords(table:string,rows:any[]){return rows.map(row=>{if(table==='archive_settings'&&row.key==='system_settings'){const d=JSON.parse(row.data);d.webdav.password='';d.smtp.password='';d.webdav.tested=null;d.webdav.daily=false;return {...row,data:JSON.stringify(d)}}if(table==='archive_backups'){const d=JSON.parse(row.data);if(d.webdav)d.webdav.password='';return {...row,data:JSON.stringify(d)}}return row})}
export async function createBackup(destination:'local'|'webdav',actor:string){const settings=await systemSettings();if(destination==='webdav'&&(!settings.webdav.tested||!settings.webdav.url||!settings.webdav.password))throw Error('Bitte WebDAV zunächst speichern und erfolgreich testen.');const db=archiveDb(),id=crypto.randomUUID(),created=new Date().toISOString();const rows=await db.batch(tables.map(t=>db.prepare(`SELECT * FROM ${t}`)));const manifest:any={format:'history-archive-backup-v2',applicationVersion:version.version,codeCommit:(env as unknown as {ARCHIVE_CODE_COMMIT?:string}).ARCHIVE_CODE_COMMIT||version.codeCommit||null,databaseSchemaVersion:version.databaseSchemaVersion,backupFormatVersion:version.backupFormatVersion,installation:await installation(),created,tables:[],files:[],passwordsIncluded:false,restore:'Tabellen auf einem getrennten Testsystem importieren; Dateien anhand der ursprünglichen R2-Schlüssel und Metadaten wiederherstellen. Zugangspasswörter neu hinterlegen.'};const schema=await db.prepare("SELECT name,sql FROM sqlite_schema WHERE type IN ('table','index','trigger') AND sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY type,name").all();const items:any[]=[];
 for(let i=0;i<tables.length;i++){const name='tables/'+tables[i]+'.json',body=JSON.stringify(withoutPasswords(tables[i],rows[i].results as any[])),sha256=createHash('sha256').update(body).digest('hex');await backupBucket().put(prefix(id)+name,body);const item={name,size:new TextEncoder().encode(body).length,sha256,rows:rows[i].results.length};manifest.tables.push(item);items.push(item)}const schemaText=JSON.stringify(schema.results);await backupBucket().put(prefix(id)+'schema.json',schemaText);manifest.schema={name:'schema.json',size:new TextEncoder().encode(schemaText).length,sha256:createHash('sha256').update(schemaText).digest('hex')};items.push(manifest.schema);let cursor:string|undefined;do{const list=await backupBucket().list({limit:1000,cursor});for(const o of list.objects)if(!o.key.startsWith('_backups/'))manifest.files.push({key:o.key,name:'files/'+manifest.files.length,size:o.size,etag:o.etag,httpMetadata:o.httpMetadata,customMetadata:o.customMetadata});cursor=list.truncated?list.cursor:undefined}while(cursor);await backupBucket().put(prefix(id)+'manifest.json',JSON.stringify(manifest));await db.prepare('INSERT INTO archive_backups(id,created,status,destination,data,actor) VALUES(?,?,?,?,?,?)').bind(id,created,'copying',destination,JSON.stringify({items,index:0,uploadIndex:0,folder:'backup-'+id,webdav:destination==='webdav'?settings.webdav:null,retention:settings.webdav.retention}),actor).run();return id}
export async function backupManifest(id:string){const object=await backupBucket().get(prefix(id)+'manifest.json');if(!object)throw Error('Sicherungsmanifest nicht gefunden.');return object.json<any>()}
async function hashStream(body:ReadableStream<Uint8Array>){const hash=createHash('sha256'),reader=body.getReader();while(true){const r=await reader.read();if(r.done)break;hash.update(r.value)}return hash.digest('hex')}
export async function advanceBackup(id:string){const db=archiveDb(),row=await db.prepare('SELECT * FROM archive_backups WHERE id=?').bind(id).first<any>();if(!row)throw Error('Sicherung nicht gefunden.');if(['complete','error','deleted','expired'].includes(row.status))return {id:row.id,status:row.status,error:row.error};const token=crypto.randomUUID();const claim=await db.prepare("UPDATE archive_backups SET verified=? WHERE id=? AND (verified IS NULL OR verified NOT LIKE 'lock:%' OR substr(verified,6,24)<?)").bind('lock:'+new Date().toISOString()+':'+token,id,new Date(Date.now()-300000).toISOString()).run();if(!claim.meta.changes)return {id:row.id,status:row.status,error:row.error};const lock='lock:';const data=JSON.parse(row.data),manifest=await backupManifest(id);let status=row.status;try{
 if(status==='copying'){for(let step=0;step<3&&data.index<manifest.files.length;step++,data.index++){const f=manifest.files[data.index],object=await backupBucket().get(f.key);if(!object||object.etag!==f.etag)throw Error('Eine Datei wurde während der Sicherung geändert oder entfernt. Bitte neu sichern.');f.httpMetadata=object.httpMetadata;f.customMetadata=object.customMetadata;const hash=createHash('sha256');const stream=object.body.pipeThrough(new TransformStream<Uint8Array,Uint8Array>({transform(chunk,controller){hash.update(chunk);controller.enqueue(chunk)}}));const Fixed=(globalThis as any).FixedLengthStream;if(Fixed){const fixed=new Fixed(f.size);await Promise.all([stream.pipeTo(fixed.writable),backupBucket().put(prefix(id)+f.name,fixed.readable)]);}else await backupBucket().put(prefix(id)+f.name,stream);f.sha256=hash.digest('hex');data.items.push({name:f.name,size:f.size,sha256:f.sha256})}await backupBucket().put(prefix(id)+'manifest.json',JSON.stringify(manifest));if(data.index>=manifest.files.length){const text=JSON.stringify(manifest);data.items.push({name:'manifest.json',size:new TextEncoder().encode(text).length,sha256:createHash('sha256').update(text).digest('hex')});status='verifying';data.verifyIndex=0}}
 else if(status==='verifying'){for(let step=0;step<3&&data.verifyIndex<data.items.length;step++,data.verifyIndex++){const item=data.items[data.verifyIndex],object=await backupBucket().get(prefix(id)+item.name);if(!object||object.size!==item.size||await hashStream(object.body)!==item.sha256)throw Error('Integritätsprüfung fehlgeschlagen: '+item.name)}if(data.verifyIndex>=data.items.length){status=row.destination==='webdav'?'uploading':'complete';if(status==='uploading'){await ensureDavFolder(data.webdav,data.folder);await ensureDavFolder(data.webdav,data.folder+'/tables');await ensureDavFolder(data.webdav,data.folder+'/files')}}}
 else if(status==='uploading'){for(let step=0;step<2&&data.uploadIndex<data.items.length;step++,data.uploadIndex++){const item=data.items[data.uploadIndex],object=await backupBucket().get(prefix(id)+item.name);if(!object)throw Error('Sicherungsdatei fehlt.');const put=await davRequest(data.webdav,data.folder+'/'+item.name,'PUT',object.body,{'Content-Type':'application/octet-stream'});if(!put.ok)throw Error('WebDAV-Upload fehlgeschlagen (HTTP '+put.status+').');const get=await davRequest(data.webdav,data.folder+'/'+item.name,'GET');if(!get.ok||!get.body||await hashStream(get.body)!==item.sha256)throw Error('WebDAV-Dateiprüfung fehlgeschlagen: '+item.name)}if(data.uploadIndex>=data.items.length)status='complete'}
 await db.prepare('UPDATE archive_backups SET data=?,status=?,verified=?,finished=? WHERE id=? AND verified LIKE ?').bind(JSON.stringify(data),status,status==='complete'?new Date().toISOString():null,status==='complete'?new Date().toISOString():null,id,lock+'%'+token).run();if(status==='complete'&&row.destination==='webdav')try{await pruneDavBackups(id)}catch(e:any){data.cleanupWarning=e.message;await db.prepare('UPDATE archive_backups SET data=? WHERE id=?').bind(JSON.stringify(data),id).run()}return await db.prepare('SELECT id,created,finished,status,destination,error,verified FROM archive_backups WHERE id=?').bind(id).first();
 }catch(e:any){await db.prepare('UPDATE archive_backups SET status=\'error\',error=?,verified=NULL WHERE id=? AND verified LIKE ?').bind(e.message||'Sicherung fehlgeschlagen.',id,lock+'%'+token).run();throw e}}
function tarHeader(name:string,size:number){const a=new Uint8Array(512),write=(offset:number,value:string)=>a.set(new TextEncoder().encode(value),offset);write(0,name);write(100,'0000644\0');write(108,'0000000\0');write(116,'0000000\0');write(124,size.toString(8).padStart(11,'0')+'\0');write(136,Math.floor(Date.now()/1000).toString(8).padStart(11,'0')+'\0');a.fill(32,148,156);a[156]=48;write(257,'ustar\0');write(263,'00');const sum=a.reduce((n,v)=>n+v,0);write(148,sum.toString(8).padStart(6,'0')+'\0 ');return a}
export function backupTar(id:string,items:any[]){async function* content(){for(const item of items){yield tarHeader(item.name,item.size);const object=await backupBucket().get(prefix(id)+item.name);if(!object)throw Error('Sicherungsdatei fehlt.');const reader=object.body.getReader();while(true){const r=await reader.read();if(r.done)break;yield r.value}const pad=(512-item.size%512)%512;if(pad)yield new Uint8Array(pad)}yield new Uint8Array(1024)}const iterator=content();return new ReadableStream<Uint8Array>({async pull(controller){try{const next=await iterator.next();if(next.done)controller.close();else controller.enqueue(next.value)}catch(e){controller.error(e)}},async cancel(){await iterator.return(undefined)}})}

export async function pruneDavBackups(id:string){const db=archiveDb(),current=await db.prepare('SELECT data FROM archive_backups WHERE id=?').bind(id).first<{data:string}>();if(!current)return;const data=JSON.parse(current.data);if(!data.webdav)return;const cutoff=new Date(Date.now()-data.retention*86400000).toISOString(),rows=await db.prepare("SELECT id,data FROM archive_backups WHERE destination='webdav' AND status='complete' AND created<? AND id<>? ORDER BY created LIMIT 5").bind(cutoff,id).all();for(const row of rows.results as any[]){const old=JSON.parse(row.data);if(old.webdav?.url!==data.webdav.url||old.webdav?.folder!==data.webdav.folder)continue;const r=await davRequest(data.webdav,old.folder+'/','DELETE');if(!r.ok&&r.status!==404)throw Error('Alte WebDAV-Sicherung konnte nicht entfernt werden (HTTP '+r.status+').');await db.prepare("UPDATE archive_backups SET status='expired' WHERE id=? AND status='complete'").bind(row.id).run();const keys=old.items.map((item:any)=>prefix(row.id)+item.name);for(let at=0;at<keys.length;at+=1000)await backupBucket().delete(keys.slice(at,at+1000))}}
