import {randomTimelineSelection} from './archive-timeline-random';
export type RotationFilters={query:string,category:string,media:string,from:string,to:string};
const formatter=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
export function berlinLocal(date:Date){return formatter.format(date).replace(' ','T')}
// Resolve German wall time. A missing spring hour moves forward; in autumn use the first occurrence.
export function localToUtc(local:string){const target=Date.parse(local+'Z');if(!Number.isFinite(target))throw Error('Bitte einen gültigen Termin wählen.');let guess=target;for(let i=0;i<4;i++){const delta=target-Date.parse(berlinLocal(new Date(guess))+'Z');if(!delta)break;guess+=delta}const candidates=[guess-3600000,guess,guess+3600000].filter(t=>berlinLocal(new Date(t))===local);return new Date(candidates.length?Math.min(...candidates):Math.min(...[guess-3600000,guess,guess+3600000].filter(t=>berlinLocal(new Date(t))>local))).toISOString()}
export function validFirstLocal(value:unknown):value is string{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:00$/.test(value))return false;const d=new Date(value+'Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,16)===value}
export function nextRotation(firstLocal:string,cadence:string,after:Date){const anchor=new Date(firstLocal+'Z'),nowLocal=new Date(berlinLocal(after)+'Z');let step=cadence==='weekly'?Math.max(0,Math.floor((nowLocal.getTime()-anchor.getTime())/(7*86400000))):Math.max(0,(nowLocal.getUTCFullYear()-anchor.getUTCFullYear())*12+nowLocal.getUTCMonth()-anchor.getUTCMonth());for(let i=0;i<3;i++,step++){let candidate:Date;if(cadence==='weekly')candidate=new Date(anchor.getTime()+step*7*86400000);else {candidate=new Date(Date.UTC(anchor.getUTCFullYear(),anchor.getUTCMonth()+step,1,anchor.getUTCHours()));const last=new Date(Date.UTC(candidate.getUTCFullYear(),candidate.getUTCMonth()+1,0)).getUTCDate();candidate.setUTCDate(Math.min(anchor.getUTCDate(),last))}const utc=localToUtc(candidate.toISOString().slice(0,16));if(Date.parse(utc)>after.getTime())return utc}throw Error('Nächster Termin konnte nicht berechnet werden.')}
export function validRotationFilters(f:any):f is RotationFilters{return !!f&&typeof f.query==='string'&&f.query.length<=250&&['all','Ereignis','Ort / Gebäude','Person / Familie','Thema','Bild / Dokument','Artefakt'].includes(f.category)&&['all','images','audio','documents'].includes(f.media)&&['from','to'].every(k=>typeof f[k]==='string'&&(f[k]===''||/^-?\d{1,6}$/.test(f[k])))&&(!f.from||!f.to||Number(f.from)<=Number(f.to))}
export function matchesRotation(e:any,f:RotationFilters){return (!f.query||[e.title,e.reference,e.place,e.tags].join(' ').toLocaleLowerCase('de').includes(f.query.toLocaleLowerCase('de')))&&(f.category==='all'||e.category===f.category)&&(f.media==='all'||e[f.media])&&(!f.from||e.start!==''&&Number(e.end||e.start)>=Number(f.from))&&(!f.to||e.start!==''&&Number(e.start)<=Number(f.to))}
export function rotatingSelection(ids:string[],previous:Set<string>,amount:number){const count=Math.min(amount,ids.length),fresh=ids.filter(id=>!previous.has(id)),old=ids.filter(id=>previous.has(id));if(!count)return new Set<string>();const result=fresh.length?randomTimelineSelection(fresh,new Set(),Math.min(count,fresh.length),true):new Set<string>();if(result.size<count){const repeats=randomTimelineSelection(old,new Set(),count-result.size,true);repeats.forEach(id=>result.add(id))}return result}
