import {installation} from './archive-installation';
import {env} from '@/lib/runtime-env';
import {archiveDb} from './archive-db';
export const defaultSystemSettings={domain:'',webdav:{url:'',folder:'Geschichtsarchiv-Sicherungen',username:'',password:'',daily:false,hour:3,retention:14,tested:null as string|null},smtp:{host:'',port:587,tls:'starttls',username:'',password:'',from:'',sender:'Geschichtsverein',tested:null as string|null},invitations:{expiryDays:7,defaultRole:'user'}};
export async function systemSettings(){const r=await archiveDb().prepare("SELECT data FROM archive_settings WHERE key='system_settings'").first<{data:string}>();if(r)return JSON.parse(r.data);const s=structuredClone(defaultSystemSettings);s.smtp.sender=(await installation()).association||s.smtp.sender;return s}
async function encryptionKey(){const value=(env as unknown as {ARCHIVE_SETTINGS_KEY?:string}).ARCHIVE_SETTINGS_KEY;if(!value||!/^[a-f0-9]{64}$/.test(value))throw Error('Die sichere Speicherung von Zugangsdaten ist noch nicht eingerichtet.');const bytes=Uint8Array.from(value.match(/../g)!,v=>parseInt(v,16));return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt'])}
export async function sealSecret(value:string){if(!value)return '';const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),new TextEncoder().encode(value));return JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(data))})}
export async function openSecret(value:string){if(!value)return '';const d=JSON.parse(value);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(d.iv)},await encryptionKey(),new Uint8Array(d.data)))}
export function sanitizedSettings(s:any){return {...s,webdav:{...s.webdav,password:'',hasPassword:!!s.webdav.password},smtp:{...s.smtp,password:'',hasPassword:!!s.smtp.password}}}
export function webdavBase(s:any){const u=new URL(s.url);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||!u.hostname.includes('.')||/^\d+\.\d+\.\d+\.\d+$/.test(u.hostname)||u.hostname.includes(':')||/\.(local|internal|localhost)$/i.test(u.hostname))throw Error('Bitte eine öffentliche HTTPS-WebDAV-Adresse ohne Zugangsdaten in der URL angeben.');if(typeof s.folder!=='string'||!s.folder.trim()||s.folder.length>150||s.folder.split('/').some((p:string)=>!p||p==='.'||p==='..'||/[\\\x00-\x1f]/.test(p)))throw Error('Bitte einen gültigen relativen Zielordner wählen.');u.pathname=u.pathname.replace(/\/?$/,'/');return u.href+s.folder.split('/').map(encodeURIComponent).join('/')+'/'}
export async function davRequest(s:any,path:string,method:string,body?:BodyInit,headers:Record<string,string>={}){const password=await openSecret(s.password),authorization='Basic '+btoa(unescape(encodeURIComponent(s.username+':'+password)));return fetch(new URL(path,webdavBase(s)),{method,body,headers:{Authorization:authorization,...headers},redirect:'manual',signal:AbortSignal.timeout(30000)})}
export async function ensureDavFolder(s:any,path=''){const root=new URL(s.url);webdavBase(s);root.pathname=root.pathname.replace(/\/?$/,'/');let relative='';for(const segment of [...s.folder.split('/'),...path.split('/').filter(Boolean)]){relative+=encodeURIComponent(segment)+'/';const password=await openSecret(s.password);const r=await fetch(new URL(relative,root.href),{method:'MKCOL',headers:{Authorization:'Basic '+btoa(unescape(encodeURIComponent(s.username+':'+password)))},redirect:'manual',signal:AbortSignal.timeout(30000)});if(![201,405].includes(r.status))throw Error('WebDAV-Zielordner nicht erreichbar (HTTP '+r.status+').')}}
export async function testWebdav(s:any){await ensureDavFolder(s);const name='verbindungstest-'+crypto.randomUUID()+'.txt',value='Geschichtsarchiv WebDAV-Test '+crypto.randomUUID();const put=await davRequest(s,name,'PUT',value,{'Content-Type':'text/plain'});if(!put.ok)throw Error('Testdatei konnte nicht geschrieben werden (HTTP '+put.status+').');try{const get=await davRequest(s,name,'GET');if(!get.ok||await get.text()!==value)throw Error('Testdatei konnte nicht korrekt gelesen werden.')}finally{const del=await davRequest(s,name,'DELETE');if(!del.ok)throw Error('Testdatei konnte nicht entfernt werden (HTTP '+del.status+').')}return new Date().toISOString()}
