import {installation} from '@/lib/archive-installation';
import {archiveAccess,accessResponse} from '@/lib/archive-access';
import {archiveDb} from '@/lib/archive-db';
import {systemSettings} from '@/lib/archive-system-settings';
import {checkHostingDomain,normalizeHostingDomain,domainConfirmation} from '@/lib/archive-qr-domain';
import {sameOrigin} from '@/lib/archive-comments';
export async function GET(req:Request){try{const config=await installation(),access=await archiveAccess(req);let restored=null;if(!config.completed&&access?.actualRole==='admin'){const db=archiveDb();const stats=await db.prepare('SELECT count(*) AS entries FROM entries').first();restored={...stats,sourceCreated:config.sourceCreated||null,restored:!!config.restored,domain:(await systemSettings()).domain||''}}return Response.json({...config,canSetup:access?.actualRole==='admin',restored},{headers:{'Cache-Control':'no-store'}})}catch(e){return accessResponse(e)||Response.json({error:'Einrichtung konnte nicht gelesen werden.'},{status:503})}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});const access=await archiveAccess(req);if(access?.actualRole!=='admin')return Response.json({error:'Nur Administratoren dürfen die Einrichtung und Archivbezeichnungen ändern.'},{status:403});const input=await req.json() as any;
if(input.action==='save-title'||input.action==='save-branding'){
 const old=await installation();if(!old.completed)return Response.json({error:'Bitte zuerst die Einrichtung abschließen.'},{status:409});
 if(typeof input.title!=='string'||input.title.length>200||/[\x00-\x1f]/.test(input.title))return Response.json({error:'Bitte einen Titel mit höchstens 200 Zeichen angeben.'},{status:400});
 if(input.action==='save-branding'&&(typeof input.association!=='string'||!input.association.trim()||input.association.length>200||/[\x00-\x1f]/.test(input.association)))return Response.json({error:'Bitte einen Vereinsnamen mit 1 bis 200 Zeichen angeben.'},{status:400});
 const updated={...old,title:input.title.trim(),association:input.action==='save-branding'?input.association.trim():old.association};
 const result=await archiveDb().prepare("INSERT INTO archive_settings(key,data,updated,updated_by) VALUES('installation',?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated=excluded.updated,updated_by=excluded.updated_by WHERE archive_settings.data=?").bind(JSON.stringify(updated),new Date().toISOString(),access.identity.name,JSON.stringify(old)).run();
 if(!result.meta.changes)return Response.json({error:'Die Einstellungen wurden inzwischen geändert. Bitte neu laden.'},{status:409});
 return Response.json(updated);
}
if((await installation()).completed)return Response.json({error:'Die Installation ist bereits eingerichtet.'},{status:409});const d=input;if(d.action==='check-domain')return Response.json(await checkHostingDomain(d.domain));if(typeof d.place!=='string'||typeof d.association!=='string'||!d.place.trim()||!d.association.trim()||d.place.length>120||d.association.length>200||/[\x00-\x1f]/.test(d.place+d.association))return Response.json({error:'Bitte Ort und vollständigen Vereinsnamen angeben.'},{status:400});const s=await systemSettings(),domain=d.domain?normalizeHostingDomain(d.domain):'';if(domain){const check=await checkHostingDomain(domain);if(!check.reachable&&!d.allowUnreachable)return Response.json({error:check.message},{status:400})}if(s.domain&&s.domain!==domain&&d.confirmation!==domainConfirmation)return Response.json({error:'Bitte den Wechsel der QR-Domain ausdrücklich bestätigen.'},{status:400});const old=await installation(),data=JSON.stringify({...old,place:d.place.trim(),association:d.association.trim(),completed:true,nonce:crypto.randomUUID()}),now=new Date().toISOString(),db=archiveDb();s.domain=domain;const results=await db.batch([db.prepare("INSERT INTO archive_settings(key,data,updated,updated_by) VALUES('installation',?,?,?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated=excluded.updated,updated_by=excluded.updated_by WHERE json_extract(archive_settings.data,'$.completed')=0").bind(data,now,access.identity.name),db.prepare("INSERT INTO archive_settings(key,data,updated,updated_by) SELECT 'system_settings',?,?,? WHERE EXISTS(SELECT 1 FROM archive_settings WHERE key='installation' AND data=?) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated=excluded.updated,updated_by=excluded.updated_by").bind(JSON.stringify(s),now,access.identity.name,data)]);if(!results[0].meta.changes)return Response.json({error:'Die Einrichtung wurde inzwischen abgeschlossen.'},{status:409});return Response.json({completed:true})}catch(e:any){return accessResponse(e)||Response.json({error:e.message||'Einrichtung fehlgeschlagen.'},{status:400})}}
