import {env} from '@/lib/runtime-env';
import {createHmac} from 'node:crypto';
import {requireArchiveAction,accessResponse} from '@/lib/archive-access';
import {hostingCapabilities} from '@/lib/archive-hosting';
import {sameOrigin} from '@/lib/archive-comments';
import version from '@/version.json';
async function agent(method:string,body=''){const e=env as unknown as {ARCHIVE_UPDATER_URL:string,ARCHIVE_UPDATER_SECRET:string},u=new URL(e.ARCHIVE_UPDATER_URL);if(u.protocol!=='http:'||u.hostname!=='127.0.0.1'||u.pathname!=='/'||u.username||u.password||u.search||u.hash)throw Error('Updater muss ausschließlich über die lokale Serveradresse angebunden werden.');const time=String(Date.now()),nonce=crypto.randomUUID(),signature=createHmac('sha256',e.ARCHIVE_UPDATER_SECRET).update([time,nonce,method,'/updates',body].join('\n')).digest('hex');const r=await fetch(new URL('/updates',u),{method,headers:{'Content-Type':'application/json','X-Archive-Time':time,'X-Archive-Nonce':nonce,'X-Archive-Signature':signature},...(body?{body}:{}),signal:AbortSignal.timeout(25000),redirect:'error'});const d=await r.json();return Response.json(d,{status:r.status,headers:{'Cache-Control':'no-store'}});}
export async function GET(req:Request){try{const a=await requireArchiveAction(req,'manageSettings');if(a.actualRole!=='admin')return Response.json({error:'Nur Administratoren.'},{status:403});const capabilities=hostingCapabilities();if(new URL(req.url).searchParams.has('hosting'))return Response.json(capabilities,{headers:{'Cache-Control':'no-store'}});if(!capabilities.updates)return Response.json({enabled:false,currentVersion:version.version,reason:capabilities.runtime==='sites'?'Diese Arbeitsumgebung wird zentral aktualisiert.':'Der sichere Server-Update-Dienst ist noch nicht eingerichtet.'},{headers:{'Cache-Control':'no-store'}});return await agent('GET')}catch(e){return accessResponse(e)||Response.json({error:'Update-Dienst ist nicht erreichbar.'},{status:503})}}
export async function POST(req:Request){try{if(!sameOrigin(req))return Response.json({error:'Bitte die Website direkt öffnen.'},{status:403});const a=await requireArchiveAction(req,'manageSettings');if(a.actualRole!=='admin')return Response.json({error:'Nur Administratoren.'},{status:403});if(!hostingCapabilities().updates)return Response.json({error:'Serverupdates sind auf dieser Instanz nicht aktiviert.'},{status:409});const d=await req.json() as any;if(!['check','skip','install','retry-recovery'].includes(d.action)||JSON.stringify(d).length>8000)return Response.json({error:'Ungültige Updateaktion.'},{status:400});return await agent('POST',JSON.stringify({action:d.action,tag:d.tag,skip:d.skip,confirmation:d.confirmation}))}catch(e){return accessResponse(e)||Response.json({error:'Update-Dienst ist nicht erreichbar.'},{status:503})}}
